/* Generated by Yosys 0.66+70 (git sha1 8eb313307, Release, Clang /usr/bin/clang++ 18.1.8) */

module dom_and(ClkxCI, AxDI, BxDI, ZxDI, CxDO);
  (* SILVER="clock" *) input ClkxCI;
  (* SILVER="[0:0]_0,[0:0]_1" *) input [1:0] AxDI;
  (* SILVER="[1:1]_0,[1:1]_1" *) input [1:0] BxDI;
  (* SILVER="refresh" *) input ZxDI;
  (* SILVER="[2:2]_0,[2:2]_1" *) output [1:0] CxDO;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  wire r00;
  wire r01;
  wire r10;
  wire r11;
  XOR2_X1 _06_ (
    .A(r00),
    .B(r01),
    .Z(CxDO[0])
  );
  NAND2_X1 _07_ (
    .A1(AxDI[1]),
    .A2(BxDI[0]),
    .ZN(_00_)
  );
  XNOR2_X1 _08_ (
    .A(ZxDI),
    .B(_00_),
    .ZN(p10)
  );
  NAND2_X1 _09_ (
    .A1(AxDI[0]),
    .A2(BxDI[1]),
    .ZN(_01_)
  );
  XNOR2_X1 _10_ (
    .A(ZxDI),
    .B(_01_),
    .ZN(p01)
  );
  AND2_X1 _11_ (
    .A1(AxDI[1]),
    .A2(BxDI[1]),
    .ZN(p11)
  );
  AND2_X1 _12_ (
    .A1(BxDI[0]),
    .A2(AxDI[0]),
    .ZN(p00)
  );
  XOR2_X1 _13_ (
    .A(r11),
    .B(r10),
    .Z(CxDO[1])
  );
  DFF_X1 _14_ (
    .CK(ClkxCI),
    .D(p00),
    .Q(r00),
    .QN(_02_)
  );
  DFF_X1 _15_ (
    .CK(ClkxCI),
    .D(p11),
    .Q(r11),
    .QN(_05_)
  );
  DFF_X1 _16_ (
    .CK(ClkxCI),
    .D(p01),
    .Q(r01),
    .QN(_04_)
  );
  DFF_X1 _17_ (
    .CK(ClkxCI),
    .D(p10),
    .Q(r10),
    .QN(_03_)
  );
endmodule
