/* Generated by Yosys 0.66+70 (git sha1 8eb313307, Release, Clang /usr/bin/clang++ 18.1.8) */

module hpc2_top(ClkxCI, AxDI, BxDI, RxDI, CxDO);
  (* SILVER="clock" *) input ClkxCI;
  (* SILVER="[0:0]_0,[0:0]_1" *) input [1:0] AxDI;
  (* SILVER="[1:1]_0,[1:1]_1" *) input [1:0] BxDI;
  (* SILVER="refresh" *) input RxDI;
  (* SILVER="[2:2]_0,[2:2]_1" *) output [1:0] CxDO;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [0:0] \dut.inner.REGin_rnd_prev.out ;
  wire [0:0] \dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_u.in ;
  wire [0:0] \dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_u.out ;
  wire [0:0] \dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_v.in ;
  wire [0:0] \dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_v.out ;
  wire [0:0] \dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_w.in ;
  wire [0:0] \dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_w.out ;
  wire [0:0] \dut.inner.gen_ParProdI[0].gen_inner.REGin_aibi.in ;
  wire [0:0] \dut.inner.gen_ParProdI[0].gen_inner.REGin_aibi.out ;
  wire [0:0] \dut.inner.gen_ParProdI[0].gen_inner.REGin_inb_prev.out ;
  wire [0:0] \dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_u.in ;
  wire [0:0] \dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_u.out ;
  wire [0:0] \dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_v.in ;
  wire [0:0] \dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_v.out ;
  wire [0:0] \dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_w.in ;
  wire [0:0] \dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_w.out ;
  wire [0:0] \dut.inner.gen_ParProdI[1].gen_inner.REGin_aibi.in ;
  wire [0:0] \dut.inner.gen_ParProdI[1].gen_inner.REGin_aibi.out ;
  wire [0:0] \dut.inner.gen_ParProdI[1].gen_inner.REGin_inb_prev.out ;
  INV_X1 _15_ (
    .A(AxDI[1]),
    .ZN(_00_)
  );
  INV_X1 _16_ (
    .A(AxDI[0]),
    .ZN(_01_)
  );
  XNOR2_X1 _17_ (
    .A(\dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_u.out ),
    .B(\dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_w.out ),
    .ZN(_02_)
  );
  XNOR2_X1 _18_ (
    .A(\dut.inner.gen_ParProdI[1].gen_inner.REGin_aibi.out ),
    .B(_02_),
    .ZN(CxDO[1])
  );
  XOR2_X1 _19_ (
    .A(BxDI[0]),
    .B(RxDI),
    .Z(\dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_v.in )
  );
  AND2_X1 _20_ (
    .A1(AxDI[1]),
    .A2(\dut.inner.gen_ParProdI[1].gen_inner.REGin_inb_prev.out ),
    .ZN(\dut.inner.gen_ParProdI[1].gen_inner.REGin_aibi.in )
  );
  AND2_X1 _21_ (
    .A1(AxDI[0]),
    .A2(\dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_v.out ),
    .ZN(\dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_w.in )
  );
  XOR2_X1 _22_ (
    .A(RxDI),
    .B(BxDI[1]),
    .Z(\dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_v.in )
  );
  AND2_X1 _23_ (
    .A1(_01_),
    .A2(\dut.inner.REGin_rnd_prev.out ),
    .ZN(\dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_u.in )
  );
  XNOR2_X1 _24_ (
    .A(\dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_u.out ),
    .B(\dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_w.out ),
    .ZN(_03_)
  );
  XNOR2_X1 _25_ (
    .A(\dut.inner.gen_ParProdI[0].gen_inner.REGin_aibi.out ),
    .B(_03_),
    .ZN(CxDO[0])
  );
  AND2_X1 _26_ (
    .A1(AxDI[1]),
    .A2(\dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_v.out ),
    .ZN(\dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_w.in )
  );
  AND2_X1 _27_ (
    .A1(AxDI[0]),
    .A2(\dut.inner.gen_ParProdI[0].gen_inner.REGin_inb_prev.out ),
    .ZN(\dut.inner.gen_ParProdI[0].gen_inner.REGin_aibi.in )
  );
  AND2_X1 _28_ (
    .A1(_00_),
    .A2(\dut.inner.REGin_rnd_prev.out ),
    .ZN(\dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_u.in )
  );
  DFF_X1 _29_ (
    .CK(ClkxCI),
    .D(BxDI[0]),
    .Q(\dut.inner.gen_ParProdI[0].gen_inner.REGin_inb_prev.out ),
    .QN(_14_)
  );
  DFF_X1 _30_ (
    .CK(ClkxCI),
    .D(\dut.inner.gen_ParProdI[0].gen_inner.REGin_aibi.in ),
    .Q(\dut.inner.gen_ParProdI[0].gen_inner.REGin_aibi.out ),
    .QN(_13_)
  );
  DFF_X1 _31_ (
    .CK(ClkxCI),
    .D(\dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_w.in ),
    .Q(\dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_w.out ),
    .QN(_12_)
  );
  DFF_X1 _32_ (
    .CK(ClkxCI),
    .D(\dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_u.in ),
    .Q(\dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_u.out ),
    .QN(_10_)
  );
  DFF_X1 _33_ (
    .CK(ClkxCI),
    .D(\dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_v.in ),
    .Q(\dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_v.out ),
    .QN(_09_)
  );
  DFF_X1 _34_ (
    .CK(ClkxCI),
    .D(\dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_w.in ),
    .Q(\dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_w.out ),
    .QN(_08_)
  );
  DFF_X1 _35_ (
    .CK(ClkxCI),
    .D(BxDI[1]),
    .Q(\dut.inner.gen_ParProdI[1].gen_inner.REGin_inb_prev.out ),
    .QN(_07_)
  );
  DFF_X1 _36_ (
    .CK(ClkxCI),
    .D(\dut.inner.gen_ParProdI[1].gen_inner.REGin_aibi.in ),
    .Q(\dut.inner.gen_ParProdI[1].gen_inner.REGin_aibi.out ),
    .QN(_06_)
  );
  DFF_X1 _37_ (
    .CK(ClkxCI),
    .D(\dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_v.in ),
    .Q(\dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_v.out ),
    .QN(_05_)
  );
  DFF_X1 _38_ (
    .CK(ClkxCI),
    .D(\dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_u.in ),
    .Q(\dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_u.out ),
    .QN(_11_)
  );
  DFF_X1 _39_ (
    .CK(ClkxCI),
    .D(RxDI),
    .Q(\dut.inner.REGin_rnd_prev.out ),
    .QN(_04_)
  );
endmodule
