#!/usr/bin/env python3
"""Emit the EVM-compliant masked DIV/MOD tops (q = B==0 ? 0 : A/B,
rem = B==0 ? 0 : A%B) — the "DIV-by-zero wrapper" composition flagged in
SWAP_DATAPATH.md, over the MATCHI-passed O-PINI2 gadget (MSKand_opini2_d2,
byte-identical leaf from ./, read-only reference).

Composition of three ALREADY-VERIFIED dataflows, no new gadget types:
  1. DIV CORE — verbatim structural copy of the gen_div256.py restoring
     divider (3N+2 gadgets: 2(N+1) subtract + N borrow-mux, bubble-free reuse
     across N iterations with genuine feedback — the OPINI regime). Internal
     Q/R registers; B=0 yields garbage here, gated off below.
  2. NONZERO TREE — the gen_iszero256.py OR-reduction tree (N-1 gadgets,
     De Morgan OR, per-gadget ina balance registers) over B captured at go.
     The gate we need is NOT(ISZERO(B)) = OR-reduce(B) = (B != 0), so the
     tree ROOT is used directly — the two share-local NOTs cancel; z itself
     is never materialized. Root captured into nzr at cnt==Z_CAP (any
     post-settle cycle gives a consistent share pair; recombined value is
     rnd-independent).
  3. GATING — qe[j] = Q[j] AND nz, reme[j] = R[j] AND nz (2N gadgets): the
     broadcast-AND pattern verified in mul256 PP gating and the div mux
     (inb = registered broadcast nzr, ina = 1-cycle per-share delay of Q/R).

Gadget budget NG = 6N+1, each with a DEDICATED r[k]/s[k] pair:
  div core r[0..3N+1]; tree r[3N+2..4N]; gating r[4N+1..6N].
Every XOR/NOT is strictly share-local; shares never recombine.

Schedule (copied from gen_div256.py; the tree+gating hang off the same
idempotent cycle counter): load @0; div iterations [1, K*N]; Q/R stable from
OUT_STABLE = K*N+1; nzr captured at Z_CAP << OUT_STABLE; gated outputs
recombine stably from ~OUT_STABLE+4; state cleared at CLR_AT; windows never
close inside the trace (tb randfills to $finish — the keccak f2e50d60f rule).

Emits (suffix = N): divevm{N}.v (OPINI target), divevm{N}_pini.v (label
control, LIVE: div-core bubble-free reuse), divevm{N}_rndreuse.v (NEG, must
FAIL: gating u_gq_1 reuses u_gq_0's r/s), divevm{N}_recomb.v (NEG, must FAIL:
register recombining qe[0]^qe[1]); tb_divevm{N}.v; tb_smoke_divevm{N}.v
(includes B=0 vectors, the semantics under test).
Generated by gen_divevm.py; do not hand-edit — regenerate instead.
Usage: gen_divevm.py [N]   (default 256)
"""
import sys

N = int(sys.argv[1]) if len(sys.argv) > 1 else 256
GADGET = "MSKand_opini2_d2"
LEVELS = (N - 1).bit_length()   # log2(N), N a power of two
NG_DIV = 3 * N + 2
NG_TREE = N - 1
NG_GATE = 2 * N
NG = NG_DIV + NG_TREE + NG_GATE          # = 6N+1
TREE_BASE = NG_DIV                        # first tree random index
GATE_BASE = NG_DIV + NG_TREE              # first gating random index
ITW = max(2, (N - 1).bit_length() + 1)

# ---- schedule constants (identical to gen_div256.py; cycle 0 = go) ----
M1 = 2 * N + 8
K = M1 + 8
OUT_STABLE = K * N + 1
Z_CAP = 8 * LEVELS + 16         # tree root settled well before this (~4/level)
CLR_AT = K * N + 16
OUT_HI = CLR_AT + 2 * N + 20    # div-core subtract-chain drain dominates the
                                # tail; tree/gating drain within +6 of clr
R_HI = OUT_HI + 2
S_HI = R_HI + 1
CNTW = max(ITW + 6, (S_HI + 2).bit_length() + 1)
TB_CYC = S_HI + 30
SMOKE_SAMPLE = CLR_AT - 5       # Q/R stable @OUT_STABLE, gated outs ~+4; this
                                # is OUT_STABLE+10 — stable, before clr
SMOKE_GAP = 60

assert Z_CAP < OUT_STABLE - 10, "tree capture must precede div completion"


def share_concat(port, share, n=N):
    """Dense sharing unpack: {port[2*(n-1)+share], ..., port[share]}."""
    return "{" + ", ".join(f"{port}[{2*j+share}]" for j in range(n - 1, -1, -1)) + "}"


def header(modname, leaf, comment, recomb=False):
    ep = ", leak_o" if recomb else ""
    lk = ('\n(* matchi_type = "sharing", matchi_active = "out_act" *) '
          "output [1:0] leak_o;") if recomb else ""
    return f"""{comment}
// EVM DIV/MOD (B==0 -> 0): restoring-divider core ({NG_DIV} gadgets, bubble-
// free reuse) + OR-reduce nonzero tree over B ({NG_TREE} gadgets) + broadcast-
// AND output gating ({NG_GATE} gadgets). NG={NG}, each with a DEDICATED
// r[k]/s[k] random bit. Every XOR/NOT is strictly share-local.
// Dense sharing layout (share index fastest): port[2i]=share0, port[2i+1]=share1.
// Schedule: load @0; div iterations [1, {K*N}]; nzr (=B!=0) captured @{Z_CAP};
// qe/rem_e recombine stably from ~{OUT_STABLE+4}; state cleared @{CLR_AT};
// randoms fresh [0,{R_HI}].
(* matchi_prop = "PINI", matchi_strat = "composite_top", matchi_arch = "loopy", matchi_shares = 2 *)
module {modname} (clk, rst, go, a, b, r, s, qe, reme{ep});
(* matchi_type = "clock" *)   input clk;
(* matchi_type = "control" *) input rst;
(* matchi_type = "control" *) input go;
(* matchi_type = "sharings_dense", matchi_active = "a_act" *) input [{2*N-1}:0] a;
(* matchi_type = "sharings_dense", matchi_active = "b_act" *) input [{2*N-1}:0] b;
(* matchi_type = "random", matchi_active = "r_act" *) input [{NG-1}:0] r;
(* matchi_type = "random", matchi_active = "s_act" *) input [{NG-1}:0] s;
(* matchi_type = "sharings_dense", matchi_active = "out_act" *) output [{2*N-1}:0] qe;
(* matchi_type = "sharings_dense", matchi_active = "out_act" *) output [{2*N-1}:0] reme;{lk}

// ---- activity windows from an idempotent cycle counter (public control) ----
reg [{CNTW-1}:0] cnt;
always @(posedge clk) begin
    if (rst)                       cnt <= {CNTW}'d0;
    else if (go)                   cnt <= {CNTW}'d1;
    else if (cnt != {CNTW}'d0 && cnt != {CNTW}'d{S_HI + 2}) cnt <= cnt + {CNTW}'d1;
end
(* keep *) wire a_act   = go || (cnt == {CNTW}'d1);   // operands consumed at load
(* keep *) wire b_act   = go || (cnt == {CNTW}'d1);
(* keep *) wire r_act   = go || (cnt >= {CNTW}'d1 && cnt <= {CNTW}'d{R_HI});
(* keep *) wire s_act   =       (cnt >= {CNTW}'d1 && cnt <= {CNTW}'d{S_HI});
(* keep *) wire out_act = go || (cnt >= {CNTW}'d1 && cnt <= {CNTW}'d{OUT_HI});
(* keep *) wire clr     = (cnt == {CNTW}'d{CLR_AT});  // bounded sensitivity
(* keep *) wire zcap    = (cnt == {CNTW}'d{Z_CAP});   // nonzero-tree capture

// ---- public FSM: iteration counter + phase (control only, data-independent) ----
reg running;
reg [{ITW-1}:0] it;
reg [{(K-1).bit_length()-1}:0] ph;
always @(posedge clk) begin
    if (rst) begin running <= 1'b0; it <= 0; ph <= 0; end
    else if (go) begin running <= 1'b1; it <= 0; ph <= 0; end
    else if (running) begin
        if (ph == {K-1}) begin
            ph <= 0;
            if (it == {ITW}'d{N-1}) begin running <= 1'b0; it <= 0; end
            else it <= it + {ITW}'d1;
        end else ph <= ph + 1'b1;
    end
end

// ---- div-core state registers (per-share; NEVER mix share 0 and share 1) ----
reg [{N-1}:0] R0, R1;            // partial remainder
reg [{N-1}:0] A0, A1;            // dividend, shifts left (public 0 in)
reg [{N-1}:0] Q0, Q1;            // quotient, shifts left (cout in)
reg [{N-1}:0] Bn0, Bn1;          // ~B, complement share-local (share 0 only)
reg [{N-1}:0] Bz0, Bz1;          // B held for the nonzero tree (per-share)
reg [{N-1}:0] Treg0, Treg1;      // registered subtract result (settled)
reg coutr0, coutr1;              // registered carry-out = quotient bit
reg nzr0, nzr1;                  // registered tree root = (B != 0) sharing
wire [{N}:0] Rsh0 = {{R0, A0[{N-1}]}};   // Rsh = R<<1 | msb(A), per share
wire [{N}:0] Rsh1 = {{R1, A1[{N-1}]}};
wire [{N-1}:0] w_m0, w_m1;       // borrow-mux gadget outputs
wire nz0, nz1;                   // nonzero-tree root wires (pre-capture)
// (* keep *): T/coutw feed only register inputs; without keep, abc absorbs
// their XOR drivers into the register cone and MATCHI hits a driverless wire.
(* keep *) wire [{N-1}:0] T0, T1;   // subtract difference bits (settled by M1)
(* keep *) wire coutw0, coutw1;     // subtract carry-out = NOT borrow

always @(posedge clk) begin
    if (rst || clr) begin
        R0 <= 0; R1 <= 0; A0 <= 0; A1 <= 0; Q0 <= 0; Q1 <= 0;
        Bn0 <= 0; Bn1 <= 0; Bz0 <= 0; Bz1 <= 0; Treg0 <= 0; Treg1 <= 0;
        coutr0 <= 0; coutr1 <= 0; nzr0 <= 0; nzr1 <= 0;
    end else if (go) begin        // dense-share unpack, share-local
        A0 <= {share_concat('a', 0)};
        A1 <= {share_concat('a', 1)};
        Bn0 <= ~{share_concat('b', 0)};   // share-local NOT: complement share 0
        Bn1 <= {share_concat('b', 1)};    // share 1 untouched
        Bz0 <= {share_concat('b', 0)};    // uncomplemented copy for the tree
        Bz1 <= {share_concat('b', 1)};
        R0 <= 0; R1 <= 0; Q0 <= 0; Q1 <= 0;
        Treg0 <= 0; Treg1 <= 0; coutr0 <= 0; coutr1 <= 0;
        nzr0 <= 0; nzr1 <= 0;
    end else begin
        if (running) begin
            if (ph == {M1-1}) begin   // subtract ripple settled: capture T, cout
                Treg0 <= T0; Treg1 <= T1;
                coutr0 <= coutw0; coutr1 <= coutw1;
            end
            if (ph == {K-1}) begin    // iteration update (all share-local)
                R0 <= Rsh0[{N-1}:0] ^ w_m0;   // R' = cout ? T : Rsh
                R1 <= Rsh1[{N-1}:0] ^ w_m1;
                Q0 <= {{Q0[{N-2}:0], coutr0}};   // quotient bit, MSB first
                Q1 <= {{Q1[{N-2}:0], coutr1}};
                A0 <= {{A0[{N-2}:0], 1'b0}};     // A <<= 1 (per-share)
                A1 <= {{A1[{N-2}:0], 1'b0}};
            end
        end
        if (zcap) begin               // consistent share pair of (B != 0)
            nzr0 <= nz0; nzr1 <= nz1;
        end
    end
end

// ---- 1-cycle per-share balance registers: every gadget ina arrives one
// cycle after its inb (gadget contract ina@1/inb@0 — the iszero256 pattern).
// Unconditional, so they drain by themselves one cycle after clr.
reg [{N}:0] Rsh_d0, Rsh_d1;      // ina of u_g_*  (inb = Bn)
reg [{N-1}:0] xm_d0, xm_d1;      // ina of u_m_*  (inb = coutr); xm = Rsh^Treg
reg [{N-1}:0] q_d0, q_d1;        // ina of u_gq_* (inb = nzr broadcast)
reg [{N-1}:0] rm_d0, rm_d1;      // ina of u_gr_* (inb = nzr broadcast)
always @(posedge clk) begin
    Rsh_d0 <= Rsh0;                       Rsh_d1 <= Rsh1;
    xm_d0  <= Rsh0[{N-1}:0] ^ Treg0;      xm_d1  <= Rsh1[{N-1}:0] ^ Treg1;
    q_d0   <= Q0;                         q_d1   <= Q1;
    rm_d0  <= R0;                         rm_d1  <= R1;
end
"""


def sub_body(leaf):
    """(N+1)-bit ripple subtract — verbatim gen_div256.py dataflow."""
    L = []
    o = L.append
    o(f"""
// ===== (N+1)-bit ripple subtract: T = Rsh + ~B + 1 (verified-adder dataflow, sub=1) =====
// fc[0] = carry-in = public 1 (share pair (1,0)); Bn bit {N} = ~0 = public 1.
wire [{N}:0] fc0, fc1;
assign fc0[0] = 1'b1;
assign fc1[0] = 1'b0;""")
    for j in range(N + 1):
        b0 = f"Bn0[{j}]" if j < N else "1'b1"
        b1 = f"Bn1[{j}]" if j < N else "1'b0"
        cl0, cl1 = (f"assign fc0[{j+1}]", f"assign fc1[{j+1}]") if j < N else \
                   ("assign coutw0", "assign coutw1")
        o(f"""wire p0_{j} = Rsh_d0[{j}] ^ {b0};
wire p1_{j} = Rsh_d1[{j}] ^ {b1};
wire g0_{j}, g1_{j}, t0_{j}, t1_{j};
{leaf} u_g_{j} (
    .ina({{Rsh_d1[{j}], Rsh_d0[{j}]}}), .inb({{{b1}, {b0}}}),
    .rnd(r[{2*j}]), .s(s[{2*j}]), .clk(clk), .out({{g1_{j}, g0_{j}}}));
{leaf} u_t_{j} (
    .ina({{fc1[{j}], fc0[{j}]}}), .inb({{p1_{j}, p0_{j}}}),
    .rnd(r[{2*j+1}]), .s(s[{2*j+1}]), .clk(clk), .out({{t1_{j}, t0_{j}}}));
{cl0} = g0_{j} ^ t0_{j};
{cl1} = g1_{j} ^ t1_{j};""")
    o(f"// difference bits (only [{N-1}:0] needed: both R' branches are < B < 2^{N})")
    for j in range(N):
        o(f"assign T0[{j}] = p0_{j} ^ fc0[{j}];  assign T1[{j}] = p1_{j} ^ fc1[{j}];")
    return "\n".join(L)


def mux_body(leaf):
    """Borrow-mux — verbatim gen_div256.py dataflow (no control bug here;
    the rndreuse control lives in the NEW gating stage instead)."""
    L = []
    o = L.append
    base = 2 * (N + 1)
    o(f"\n// ===== borrow-mux: w_m[j] = coutr AND xm[j]  (coutr broadcast to both shares) =====")
    for j in range(N):
        o(f"""{leaf} u_m_{j} (
    .ina({{xm_d1[{j}], xm_d0[{j}]}}), .inb({{coutr1, coutr0}}),
    .rnd(r[{base+j}]), .s(s[{base+j}]), .clk(clk), .out({{w_m1[{j}], w_m0[{j}]}}));""")
    return "\n".join(L)


def tree_body(leaf):
    """OR-reduction nonzero tree over Bz — verbatim gen_iszero256.py pattern
    (De Morgan OR, per-gadget ina balance register). Root = (B != 0); the
    final ISZERO NOT and the gating NOT cancel, so the root is used directly."""
    L = []
    o = L.append
    cur = [(f"Bz0[{j}]", f"Bz1[{j}]") for j in range(N)]
    k = 0
    for lvl in range(LEVELS):
        o(f"\n// ===== nonzero-tree OR-reduce level {lvl}: {len(cur)} masked bits -> {len(cur)//2} =====")
        nxt = []
        for m in range(len(cur) // 2):
            (x0, x1) = cur[2 * m]
            (y0, y1) = cur[2 * m + 1]
            rk, sk = f"r[{TREE_BASE+k}]", f"s[{TREE_BASE+k}]"
            o(f"""wire nx0_{k} = {x0} ^ 1'b1;   // NOT childA, share-local (share 0)
wire ny0_{k} = {y0} ^ 1'b1;   // NOT childB, share-local (share 0)
(* keep = "yes" *) reg ina0_{k}, ina1_{k};   // 1-cycle ina balance reg (per-share)
always @(posedge clk) begin
    ina0_{k} <= nx0_{k};
    ina1_{k} <= {x1};
end
wire w0_{k}, w1_{k};
{leaf} u_or_{k} (
    .ina({{ina1_{k}, ina0_{k}}}), .inb({{{y1}, ny0_{k}}}),
    .rnd({rk}), .s({sk}), .clk(clk), .out({{w1_{k}, w0_{k}}}));
wire or0_{k} = w0_{k} ^ 1'b1;   // OR = NOT(AND(..)), share-local (share 0)
wire or1_{k} = w1_{k};""")
            nxt.append((f"or0_{k}", f"or1_{k}"))
            k += 1
        cur = nxt
    assert len(cur) == 1 and k == NG_TREE
    o(f"""
// tree root = OR-reduce(B) = (B != 0) — exactly the gate NOT(ISZERO(B))
assign nz0 = {cur[0][0]};
assign nz1 = {cur[0][1]};""")
    return "\n".join(L)


def gate_body(leaf, rndreuse=False):
    """Output gating qe = Q AND nz, reme = R AND nz — the broadcast-AND
    pattern verified in mul256 PP gating and the div borrow-mux
    (inb = registered broadcast nzr, ina = 1-cycle per-share delay)."""
    L = []
    o = L.append
    o(f"\n// ===== EVM zero-gating: qe[j] = Q[j] AND (B!=0), reme[j] = R[j] AND (B!=0) =====")
    for j in range(N):
        if rndreuse and j == 1:
            rk, sk = f"r[{GATE_BASE}]", f"s[{GATE_BASE}]"
            note = "  // BUG UNDER TEST: reuses u_gq_0's randomness"
        else:
            rk, sk = f"r[{GATE_BASE+j}]", f"s[{GATE_BASE+j}]"
            note = ""
        o(f"""wire wq0_{j}, wq1_{j};
{leaf} u_gq_{j} ({note}
    .ina({{q_d1[{j}], q_d0[{j}]}}), .inb({{nzr1, nzr0}}),
    .rnd({rk}), .s({sk}), .clk(clk), .out({{wq1_{j}, wq0_{j}}}));
assign qe[{2*j}] = wq0_{j};  assign qe[{2*j+1}] = wq1_{j};""")
    for j in range(N):
        rk, sk = f"r[{GATE_BASE+N+j}]", f"s[{GATE_BASE+N+j}]"
        o(f"""wire wr0_{j}, wr1_{j};
{leaf} u_gr_{j} (
    .ina({{rm_d1[{j}], rm_d0[{j}]}}), .inb({{nzr1, nzr0}}),
    .rnd({rk}), .s({sk}), .clk(clk), .out({{wr1_{j}, wr0_{j}}}));
assign reme[{2*j}] = wr0_{j};  assign reme[{2*j+1}] = wr1_{j};""")
    return "\n".join(L)


def build(modname, leaf, comment, rndreuse=False, recomb=False):
    parts = [header(modname, leaf, comment, recomb=recomb),
             sub_body(leaf),
             mux_body(leaf),
             tree_body(leaf),
             gate_body(leaf, rndreuse=rndreuse)]
    if recomb:
        parts.append("""
// BUG UNDER TEST: recombine the two shares of qe bit 0. leak0 holds
// qe[0]^qe[1] (both shares) -> the XOR gate is sensitive in ShareSet{0}
// AND ShareSet{1} -> MATCHI glitch leakage. Driven onto share 0 of leak_o.
(* keep = "yes" *) reg leak0, leak1;
always @(posedge clk) begin
    leak0 <= qe[0] ^ qe[1];
    leak1 <= 1'b0;
end
assign leak_o = {leak1, leak0};""")
    parts.append("\nendmodule\n")
    return "\n".join(parts)


def emit(fn, text, leaf, expect_count):
    n = text.count(leaf + " u_")
    assert n == expect_count, f"{fn}: leaf {leaf} x{n}, expected {expect_count}"
    with open(fn, "w") as f:
        f.write(text)
    print(f"wrote {fn}: {n} {leaf} instances")


C_MAIN = (f"// {N}-bit masked EVM DIV/MOD (q = B==0 ? 0 : A/B, rem = B==0 ? 0 : A%B)\n"
          f"// — restoring-divider core + nonzero tree + zero-gating, {NG} O-PINI2\n"
          "// masked-AND leaves. VERIFIED TARGET. Closes the SWAP_DATAPATH.md\n"
          "// 'EVM DIV/MOD by zero -> 0' composition note with MATCHI evidence.")
C_PINI = ("// LABEL CONTROL: identical netlist but instantiates the PINI-relabelled\n"
          "// leaf MSKand_opini2_d2_pini. The div core REUSES gadgets bubble-free\n"
          "// with feedback, the structure MATCHI's transition rule guards for PINI\n"
          "// leaves (cf. div256_pini LIVE FAIL). Verdict recorded either way.")
C_RND = ("// NEGATIVE CONTROL (must FAIL): identical to the target except gating\n"
         "// gadget u_gq_1 consumes the SAME random bits as u_gq_0, active in the\n"
         "// same cycles — the bug is in the NEW composition stage, so the control\n"
         "// exercises exactly what this top adds. MATCHI must report multi-use.")
C_RCB = ("// NEGATIVE CONTROL (must FAIL): identical to the target plus one share-\n"
         "// recombining register (leak0 <= qe[0]^qe[1]). MATCHI must flag the\n"
         "// gate sensitive in multiple shares (glitch leakage).")

emit(f"divevm{N}.v", build(f"divevm{N}", GADGET, C_MAIN), GADGET, NG)
emit(f"divevm{N}_pini.v", build(f"divevm{N}_pini", GADGET + "_pini", C_PINI),
     GADGET + "_pini", NG)
emit(f"divevm{N}_rndreuse.v", build(f"divevm{N}_rndreuse", GADGET, C_RND, rndreuse=True),
     GADGET, NG)
emit(f"divevm{N}_recomb.v", build(f"divevm{N}_recomb", GADGET, C_RCB, recomb=True),
     GADGET, NG)

# ---------------- MATCHI testbench ----------------
AB_W = 2 * N
RS_W = NG
AB_WW = (AB_W + 31) // 32
RS_WW = (RS_W + 31) // 32
tb = f"""// MATCHI testbench for the divevm{N} tops. Same convention as the verified
// adder/iszero/mul/div tbs: values are irrelevant to MATCHI (symbolic); only
// signal-activity timing is read from the VCD. Inputs re-randomized every
// cycle so the annotated activity windows match physics. Run length covers
// the deepest window (r [0,{R_HI}]) plus margin.
// Generated by gen_divevm.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD divevm{N}
`endif
module tb ();
parameter HP = 5;
reg clk, rst, go;
reg [{AB_WW*32-1}:0] a, b;
reg [{RS_WW*32-1}:0] r, s;
wire [{AB_W-1}:0] qe, reme;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .go(go),
             .a(a[{AB_W-1}:0]), .b(b[{AB_W-1}:0]),
             .r(r[{RS_W-1}:0]), .s(s[{RS_W-1}:0]), .qe(qe), .reme(reme)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < {AB_WW}; w = w + 1) begin
            a[w*32 +: 32] = $random;
            b[w*32 +: 32] = $random;
        end
        for (w = 0; w < {RS_WW}; w = w + 1) begin
            r[w*32 +: 32] = $random;
            s[w*32 +: 32] = $random;
        end
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; go = 1'b0;
    a = 0; b = 0; r = 0; s = 0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // cycle 0: one-cycle go pulse
    @(negedge clk); go = 1'b1; randfill;
    @(negedge clk); go = 1'b0; randfill;
    for (i = 0; i < {TB_CYC}; i = i + 1) begin
        @(negedge clk); randfill;
    end
    $finish;
end
endmodule
"""
with open(f"tb_divevm{N}.v", "w") as f:
    f.write(tb)
print(f"wrote tb_divevm{N}.v")

# ---------------- functional smoke testbench ----------------
NW = (N + 31) // 32
smoke = f"""// Functional smoke test for divevm{N} (NOT a security check — MATCHI is the
// separate verification step). Shares each operand with a random mask, pulses
// go, waits out the {N} restoring iterations, recombines the qe/reme shares,
// compares against EVM semantics: q = (y==0) ? 0 : x/y, rem = (y==0) ? 0 : x%y.
// B=0 vectors are INCLUDED — that gating is exactly what this unit adds over
// the bare div core. Fresh gadget randoms every cycle (the recombined outputs
// are mask-independent).
// Generated by gen_divevm.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [{2*N-1}:0] a, b;
reg [{RS_WW*32-1}:0] rr, ss;
wire [{2*N-1}:0] qe, reme;

divevm{N} dut (.clk(clk), .rst(rst), .go(go), .a(a), .b(b),
               .r(rr[{RS_W-1}:0]), .s(ss[{RS_W-1}:0]), .qe(qe), .reme(reme));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < {RS_WW}; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [{N-1}:0] am, bm, gotq, gotr, expq, expr;
integer j;
task check(input [{N-1}:0] x, input [{N-1}:0] y);
    begin
        for (j = 0; j < {NW}; j = j + 1) begin
            am[j*32 +: 32] = $random;
            bm[j*32 +: 32] = $random;
        end
        for (j = 0; j < {N}; j = j + 1) begin
            a[2*j] = x[j] ^ am[j];  a[2*j+1] = am[j];
            b[2*j] = y[j] ^ bm[j];  b[2*j+1] = bm[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat ({SMOKE_SAMPLE}) @(negedge clk);
        for (j = 0; j < {N}; j = j + 1) begin
            gotq[j] = qe[2*j] ^ qe[2*j+1];
            gotr[j] = reme[2*j] ^ reme[2*j+1];
        end
        if (y == 0) begin
            expq = 0;
            expr = 0;
        end else begin
            expq = x / y;
            expr = x % y;
        end
        if (gotq !== expq || gotr !== expr) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  x   =%h", x);
            $display("  y   =%h", y);
            $display("  gotq=%h expq=%h", gotq, expq);
            $display("  gotr=%h expr=%h", gotr, expr);
        end else begin
            $display("PASS q=%h rem=%h (y==0:%0d)", gotq, gotr, y == 0);
        end
        repeat ({SMOKE_GAP}) @(negedge clk);   // past clr before the next check
    end
endtask

reg [{N-1}:0] xv, yv;
initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    check({{{{{N-1}{{1'b0}}}}, 1'b1}}, {{{{{N-1}{{1'b0}}}}, 1'b1}}); // 1 / 1
    check({{{{{N-1}{{1'b0}}}}, 1'b1}}, {{{N}{{1'b0}}}});            // 1 / 0 = 0, rem 0 (EVM)
    check({{{N}{{1'b0}}}}, {{{N}{{1'b0}}}});                        // 0 / 0 = 0, rem 0 (EVM)
    for (j = 0; j < {NW}; j = j + 1) xv[j*32 +: 32] = $random;
    check(xv, {{{N}{{1'b0}}}});                                     // x / 0 = 0, rem 0 (EVM)
    check(xv, {{{{{N-1}{{1'b0}}}}, 1'b1}});                         // x / 1 = x, rem 0
    check(xv, xv);                                                  // x / x = 1, rem 0
    check({{{N}{{1'b1}}}}, {{{{{N-2}{{1'b0}}}}, 2'b11}});           // max / 3
    for (j = 0; j < {NW}; j = j + 1) begin
        xv[j*32 +: 32] = $random;
        yv[j*32 +: 32] = $random;
    end
    yv[{N-1}:{N//2}] = 0;                                           // small-ish divisor
    if (yv == 0) yv = 7;
    check(xv, yv);                                                  // random / random
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
"""
with open(f"tb_smoke_divevm{N}.v", "w") as f:
    f.write(smoke)
print(f"wrote tb_smoke_divevm{N}.v")

print(f"N={N} NG={NG} (div {NG_DIV} + tree {NG_TREE} + gate {NG_GATE}) "
      f"K={K} OUT_STABLE={OUT_STABLE} Z_CAP={Z_CAP} CLR_AT={CLR_AT} "
      f"R_HI={R_HI} S_HI={S_HI} TB_CYC={TB_CYC}")
