#!/usr/bin/env python3
"""Emit the sponge100 tops — the KECCAK256 SPONGE ABSORB stage as a MATCHI-
verifiable pilot at w=4 (keccak-f[100]), upgrading the SWAP_DATAPATH.md
composition note ("sponge padding / rate XOR: share-local XOR ... no gadgets")
from smoke-only (gen_keccak256_smoke.py, 3/3 PASS at f[1600]) to a full
MATCHI matrix, the same pilot pattern as swap16 / divevm16.

DUT = final-block absorb + permutation, ONE flat module built by minimal
textual surgery on the VERIFIED keccakf100 variant files (the permutation
body is byte-identical; input `a` becomes an internal wire):

    a(share0) = st(share0) ^ zext(m(share0)) ^ PAD     -- public constants
    a(share1) = st(share1) ^ zext(m(share1))           -- share-local, 0 gadgets

Keccak-256 analog at w=4: rate = 17 lanes = 68 bits, capacity = 8 lanes =
32 bits, message = 8 lanes = 32 bits (the keccak256(key||slot) two-word
mapping-slot pattern scaled 64->4), pad10*1 constants at flat bits 32 (first
bit after the message) and 67 (last rate bit) — exactly the lane positions
the f[1600] sponge uses (lane 8 bit 0, lane 16 bit w-1).

Emits: sponge100.v (OPINI target, clean keccakf100 core), sponge100_pini.v
(label control on the _pini core — EXPECTED transition-leakage FAIL, the
bubble-free round reuse, cf. keccakf100_pini), sponge100_rndreuse.v (NEG,
must FAIL: core u_chi_1 reuses u_chi_0's r/s), sponge100_recomb.v (NEG, must
FAIL: planted in the NEW ABSORB STAGE — register recombining the two shares
of absorbed state bit 0, on a CLEAN core: demonstrates MATCHI checks the
wrapper wiring itself); tb_sponge100.v; tb_smoke_sponge100.v.
Generated by gen_sponge100.py; do not hand-edit — regenerate instead.
"""
import random as _rnd
import re

W, NR, L = 4, 16, 2
B = 100
RATE = 68          # bits (17 lanes)
MSGB = 32          # message bits (8 lanes)
PAD_BITS = (MSGB, RATE - 1)   # pad10*1: flat bits 32 and 67
GADGET = "MSKand_opini2_d2"
NGAD = 100

# ---------------- spec reference (same derivation as gen_keccakf.py) --------
def rho_offsets():
    r = [[0] * 5 for _ in range(5)]
    x, y = 1, 0
    for t in range(24):
        r[x][y] = ((t + 1) * (t + 2) // 2) % W
        x, y = y, (2 * x + 3 * y) % 5
    return r

def rc_bit(t):
    if t % 255 == 0:
        return 1
    R = 1
    for _ in range(t % 255):
        R <<= 1
        if R & 0x100:
            R ^= 0x171
        R &= 0xFF
    return R & 1

RHO = rho_offsets()
RC = []
for ir in range(NR):
    v = 0
    for j in range(L + 1):
        v |= rc_bit(j + 7 * ir) << (2 ** j - 1)
    RC.append(v & ((1 << W) - 1))
# cross-check against the rc_cur table in the verified keccakf100.v
assert RC[:6] == [0x1, 0x2, 0xa, 0x0, 0xb, 0x1], RC[:6]

def keccakf_ref(lanes):
    lanes = list(lanes)
    M = (1 << W) - 1
    def rotl(v, n):
        n %= W
        return ((v << n) | (v >> (W - n))) & M if n else v
    for ir in range(NR):
        C = [lanes[x] ^ lanes[x + 5] ^ lanes[x + 10] ^ lanes[x + 15] ^ lanes[x + 20]
             for x in range(5)]
        D = [C[(x - 1) % 5] ^ rotl(C[(x + 1) % 5], 1) for x in range(5)]
        A = [lanes[5 * y + x] ^ D[x] for y in range(5) for x in range(5)]
        Bl = [0] * 25
        for x in range(5):
            for y in range(5):
                Bl[5 * ((2 * x + 3 * y) % 5) + y] = rotl(A[5 * y + x], RHO[x][y])
        lanes = [Bl[5 * y + x] ^ ((~Bl[5 * y + (x + 1) % 5]) & Bl[5 * y + (x + 2) % 5]) & M
                 for y in range(5) for x in range(5)]
        lanes[0] ^= RC[ir]
    return lanes

def flat(lanes):
    v = 0
    for i in range(25):
        v |= lanes[i] << (i * W)
    return v

def unflat(v):
    return [(v >> (i * W)) & ((1 << W) - 1) for i in range(25)]

# anchor: the VERIFIED keccakf100 unit's own zero-state smoke vector
# (tb_smoke_keccakf100.v) ties this reference to the verified RTL.
assert flat(keccakf_ref([0] * 25)) == 0x10aae77d05820f26dabedc566, \
    hex(flat(keccakf_ref([0] * 25)))
print("anchor OK: f[100](0) matches the verified keccakf100 smoke vector")

PAD = 0
for pb in PAD_BITS:
    PAD |= 1 << pb

def sponge_ref(st, m):
    """absorbed = st XOR zext(m) XOR PAD; return f[100](absorbed)."""
    return flat(keccakf_ref(unflat(st ^ m ^ PAD)))

# ---------------- textual surgery on the verified core files ----------------
def subst_once(text, old, new, fn):
    assert text.count(old) == 1, f"{fn}: pattern not unique ({text.count(old)}x): {old!r}"
    return text.replace(old, new)

def absorb_block(recomb=False):
    L = ["""
// ---- SPONGE ABSORB (final-block, Keccak-256 analog at w=4): rate = 68 bits
// (lanes 0..16), capacity = 32 bits (lanes 17..24), message = 32 bits
// (lanes 0..7 — the keccak256(key||slot) mapping-slot pattern), pad10*1
// public constants at flat bits 32 and 67 (lane 8 bit 0, lane 16 bit 3 —
// the same lane positions as the f[1600] sponge). STRICTLY SHARE-LOCAL,
// ZERO gadgets: share 0 = st0 ^ m0 ^ pad_const, share 1 = st1 ^ m1;
// two shares of one secret never meet. Per-bit wires ab_<k> (not a packed
// vector: yosys leaves a partially-aliased packed netname dangling in the
// JSON — "unused_bits" — which MATCHI's netlist builder rejects; single-bit
// wires sweep cleanly, cf. eq256's d0_*). The verified permutation body
// below is byte-identical to keccakf100 up to the a-to-ab_ bit rename."""]
    for j in range(B):
        pad = " ^ 1'b1" if j in PAD_BITS else ""
        if j < MSGB:
            L.append(f"wire ab_{2*j} = st[{2*j}] ^ m[{2*j}]{pad};  "
                     f"wire ab_{2*j+1} = st[{2*j+1}] ^ m[{2*j+1}];")
        else:
            L.append(f"wire ab_{2*j} = st[{2*j}]{pad};  "
                     f"wire ab_{2*j+1} = st[{2*j+1}];")
    if recomb:
        L.append("""
// BUG UNDER TEST (planted in the NEW absorb stage, core is CLEAN): register
// recombining the two shares of absorbed state bit 0. Its input XOR gate is
// sensitive in ShareSet{0} AND ShareSet{1} -> MATCHI glitch leakage.
(* keep = "yes" *) reg leak0, leak1;
always @(posedge clk) begin
    leak0 <= ab_0 ^ ab_1;
    leak1 <= 1'b0;
end
assign leak_o = {leak1, leak0};""")
    return "\n".join(L)

def build(core_file, core_mod, sponge_mod, comment, recomb=False):
    text = open(core_file).read()
    ep = ", leak_o" if recomb else ""
    lk = ('\n(* matchi_type = "sharing", matchi_active = "out_act" *) '
          "output [1:0] leak_o;") if recomb else ""
    text = subst_once(
        text,
        f"module {core_mod} (clk, rst, go, a, r, s, o);",
        f"module {sponge_mod} (clk, rst, go, st, m, r, s, o{ep});",
        core_file)
    text = subst_once(
        text,
        '(* matchi_type = "sharings_dense", matchi_active = "a_act" *) '
        "input [199:0] a;",
        '(* matchi_type = "sharings_dense", matchi_active = "a_act" *) '
        "input [199:0] st;\n"
        '(* matchi_type = "sharings_dense", matchi_active = "a_act" *) '
        "input [63:0] m;",
        core_file)
    # absorb block goes right after the output declaration, before the
    # counter/window section — `a` is now an internal wire, body unchanged.
    o_decl = ('(* matchi_type = "sharings_dense", matchi_active = "out_act" *)'
              " output [199:0] o;")
    text = subst_once(text, o_decl, o_decl + lk + "\n" + absorb_block(recomb),
                      core_file)
    # rename former input refs to ab_<k> in the (two) load lines; the absorb block uses st[]/m[]
    # only, so word-boundary a[ matches exactly the former input references.
    text, nsub = re.subn(r"\ba\[(\d+)\]", r"ab_\1", text)
    assert nsub == 200, f"{core_file}: substituted {nsub} a[k] refs, expected 200"
    assert not re.search(r"\ba\[", text)
    return comment + "\n" + text

C_MAIN = ("// sponge100 — KECCAK256 sponge absorb pilot at w=4: share-local\n"
          "// final-block absorb (zero gadgets) + the VERIFIED keccakf100\n"
          "// permutation body byte-identical below. VERIFIED TARGET.")
C_PINI = ("// LABEL CONTROL (EXPECTED transition-leakage FAIL): sponge absorb on\n"
          "// the keccakf100_pini core (PINI-relabelled leaf, bubble-free round\n"
          "// reuse — cf. keccakf100_pini). Verdict recorded either way.")
C_RND = ("// NEGATIVE CONTROL (must FAIL): sponge absorb on the\n"
         "// keccakf100_rndreuse core (u_chi_1 reuses u_chi_0's r/s).")
C_RCB = ("// NEGATIVE CONTROL (must FAIL): CLEAN keccakf100 core; the bug is\n"
         "// planted in the NEW absorb stage (leak0 <= a[0]^a[1]) — proves\n"
         "// MATCHI checks the sponge wiring itself, not just the core.")

def emit(fn, text, leaf):
    n = text.count(leaf + " u_")
    assert n == NGAD, f"{fn}: leaf {leaf} x{n}, expected {NGAD}"
    with open(fn, "w") as f:
        f.write(text)
    print(f"wrote {fn}: {n} {leaf} instances")

emit("sponge100.v",
     build("keccakf100.v", "keccakf100", "sponge100", C_MAIN), GADGET)
emit("sponge100_pini.v",
     build("keccakf100_pini.v", "keccakf100_pini", "sponge100_pini", C_PINI),
     GADGET + "_pini")
emit("sponge100_rndreuse.v",
     build("keccakf100_rndreuse.v", "keccakf100_rndreuse",
           "sponge100_rndreuse", C_RND), GADGET)
emit("sponge100_recomb.v",
     build("keccakf100.v", "keccakf100", "sponge100_recomb", C_RCB,
           recomb=True), GADGET)

# ---------------- MATCHI testbench (mirror tb_keccakf100.v) ----------------
tb = """// MATCHI testbench for the sponge100 tops. Same convention as
// tb_keccakf100.v: values are irrelevant to MATCHI (symbolic); only
// signal-activity timing is read from the VCD. Run length covers the deepest
// window (r [0,118]) plus margin — the absorb stage is combinational and
// adds zero cycles, so all keccakf100 window constants carry over unchanged.
// Generated by gen_sponge100.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD sponge100
`endif
module tb ();
parameter HP = 5;
reg clk, rst, go;
reg [223:0] st;
reg [63:0] m;
reg [127:0] r, s;
wire [199:0] o;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .go(go), .st(st[199:0]), .m(m),
             .r(r[99:0]), .s(s[99:0]), .o(o)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < 7; w = w + 1) st[w*32 +: 32] = $random;
        for (w = 0; w < 2; w = w + 1) m[w*32 +: 32] = $random;
        for (w = 0; w < 4; w = w + 1) begin
            r[w*32 +: 32] = $random;
            s[w*32 +: 32] = $random;
        end
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; go = 1'b0;
    st = 0; m = 0; r = 0; s = 0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // cycle 0: one-cycle go pulse
    @(negedge clk); go = 1'b1; randfill;
    @(negedge clk); go = 1'b0; randfill;
    for (i = 0; i < 149; i = i + 1) begin
        @(negedge clk); randfill;
    end
    $finish;
end
endmodule
"""
with open("tb_sponge100.v", "w") as f:
    f.write(tb)
print("wrote tb_sponge100.v")

# ---------------- functional smoke testbench ----------------
_rnd.seed(0x5B0A6E)
vecs = [
    (0, 0, "st=0 m=0 (first block, empty message: absorbed = PAD only)"),
    (0, 0xDEADBEEF, "st=0, m=deadbeef (first block with message)"),
    (_rnd.getrandbits(B), _rnd.getrandbits(MSGB),
     "chained block: random incoming state + random message"),
    (_rnd.getrandbits(B), _rnd.getrandbits(MSGB),
     "chained block: second random vector"),
]
checks = []
for stv, mv, note in vecs:
    exp = sponge_ref(stv, mv)
    print(f"vector: {note}\n  out = {exp:025x}")
    checks.append(f"    // {note}\n"
                  f"    check(100'h{stv:025x}, 32'h{mv:08x}, 100'h{exp:025x});")
checks = "\n".join(checks)

smoke = f"""// Functional smoke test for sponge100 (NOT a security check — MATCHI is the
// separate verification step). Shares the incoming state AND the message with
// independent random masks, pulses go, waits out the 16 rounds, recombines
// the output shares, compares against absorb+permute computed by the spec
// reference (gen_sponge100.py — anchored on the verified keccakf100 unit's
// own zero-state vector 10aae77d05820f26dabedc566). Fresh gadget randoms
// every cycle.
// Generated by gen_sponge100.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [199:0] st;
reg [63:0] m;
reg [127:0] rr, ss;
wire [199:0] o;

sponge100 dut (.clk(clk), .rst(rst), .go(go), .st(st), .m(m),
          .r(rr[99:0]), .s(ss[99:0]), .o(o));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 4; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [99:0] am, got;
reg [31:0] bm;
integer j;
task check(input [99:0] x, input [31:0] mx, input [99:0] expd);
    begin
        for (j = 0; j < 4; j = j + 1) am[j*32 +: 32] = $random;
        bm = $random;
        for (j = 0; j < 100; j = j + 1) begin
            st[2*j] = x[j] ^ am[j];  st[2*j+1] = am[j];
        end
        for (j = 0; j < 32; j = j + 1) begin
            m[2*j] = mx[j] ^ bm[j];  m[2*j+1] = bm[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat (103) @(negedge clk);
        for (j = 0; j < 100; j = j + 1) got[j] = o[2*j] ^ o[2*j+1];
        if (got !== expd) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  st =%h m=%h", x, mx);
            $display("  got=%h", got);
            $display("  exp=%h", expd);
        end else begin
            $display("PASS out=%h", got);
        end
        repeat (30) @(negedge clk);   // past clr before the next check
    end
endtask

initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
{checks}
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
"""
with open("tb_smoke_sponge100.v", "w") as f:
    f.write(smoke)
print("wrote tb_smoke_sponge100.v")
