#!/usr/bin/env python3
"""Emit the 256-bit masked ISZERO tops — a balanced binary OR-reduction tree
over the MATCHI-passed O-PINI2 gadget (MSKand_opini2_d2, byte-identical leaf
from ./, read-only reference).

Masked OR via De Morgan:  OR(x,y) = NOT( AND( NOT x, NOT y ) )
  A 2-share masking of bit v is (v0, v1) with v = v0 ^ v1.
  NOT is strictly SHARE-LOCAL: ~v = 1 ^ v0 ^ v1 = (v0^1, v1)  -> XOR 1 into
  share 0 only. AND is the O-PINI2 gadget (masked AND). So
  OR-out = NOT( gadget-out ) = (w0^1, w1).

ISZERO(a) = NOT( OR-reduce_{j=0..255} a_j ). The OR-reduce recombines to
(a != 0); complementing it (share-local) gives (a == 0). Exactly 255 OR
nodes -> 255 gadgets (128+64+32+16+8+4+2+1), one gadget per node, 8 levels.

Single-pass: each gadget fires once; the tree is feed-forward (no gadget
output re-enters the same gadget). Dedicated randoms per gadget: gadget k ->
r[k]/s[k]. Every XOR/NOT is strictly share-local (never mixes share 0 with
share 1 of the same masked value). Gadget is INSTANTIATED, never inlined —
the only occurrences of the module name are the 255 instantiations.

Emits four tops (identical tree; differ only by the injected control):
  iszero256.v          — OPINI target (verified deliverable)
  iszero256_pini.v     — LABEL control: PINI-relabelled leaf (single-pass =>
                         EXPECTED PASS; recorded, NOT counted as non-vacuity)
  iszero256_rndreuse.v — NEG control (must FAIL): gadget 1 reuses gadget 0's
                         randomness r[0]/s[0]
  iszero256_recomb.v   — NEG control (must FAIL): a top-level register
                         recombines the two shares of the ISZERO output

Activity schedule (mirrors the verified adder's shift-register model): a
single go-pulse is shifted; |act[HI:LO] realises each input's sensitive
window. E = 32 overlapped executions streamed one/cycle; the tree pipeline is
8 gadget-levels deep (gadget out latency 3 => level-k fires at cycle 3k,
final output at cycle 24). Windows cover the deepest consumption of the last
streamed execution (exec 31): randoms up to 31+21=52, output up to 31+24=55.
Generated by gen_iszero256.py; do not hand-edit — regenerate instead.
"""
import sys

N = 256
LEVELS = 8            # log2(256)
NGAD = N - 1          # 255 OR gadgets
GADGET = "MSKand_opini2_d2"

E = 32               # overlapped (streamed) executions
# With the per-gadget ina balance register, MATCHI's latency accounting adds
# ~1 cycle/level on top of the gadget out@3, so the 8-level tree is ~32 cycles
# deep in MATCHI cycles (empirically the deepest gadget u_or_254 consumes its
# randomness at cur_lat 59 for E=32 streamed executions). Windows are sized to
# comfortably cover that deepest consumption (the safe over-approximation
# direction: a/r/s windows must be a SUPERSET of the sensitive/fresh cycles).
A_HI = E + 8          # 40  a sensitive [0,40]  (level-0 inb@e U ina@e+1, e<=31 + margin)
R_HI = E + 36         # 68  r fresh    [0,68]  (deepest rnd consumption ~59 + margin)
S_HI = E + 37         # 69  s fresh    [1,69]  (s latency 1)
OUT_HI = E + 40       # 72  out valid  [0,72]  (deepest output ~62, recomb leak +1 + margin)


def header(modname, comment, recomb=False):
    ep = ", leak_o" if recomb else ""
    # leak_o is a bogus "sharing" output: its share 0 is driven by the
    # recombined (out[0]^out[1]) value, so the recombining XOR gate spans both
    # share sets -> MATCHI's per-gate glitch analysis reports "sensitive in
    # multiple shares" (the same, recombination-specific, class as the adder's
    # recomb control — a single share would span only one share set and pass).
    lk = '\n(* matchi_type = "sharing", matchi_active = "out_act" *) output [1:0] leak_o;' if recomb else ""
    return f"""{comment}
(* matchi_prop = "PINI", matchi_strat = "composite_top", matchi_arch = "loopy", matchi_shares = 2 *)
module {modname} (clk, rst, go, a, r, s, out{ep});
(* matchi_type = "clock" *)   input clk;
(* matchi_type = "control" *) input rst;
(* matchi_type = "control" *) input go;
(* matchi_type = "sharings_dense", matchi_active = "a_act" *) input [{2*N-1}:0] a;
(* matchi_type = "random", matchi_active = "r_act" *) input [{N-1}:0] r;
(* matchi_type = "random", matchi_active = "s_act" *) input [{N-1}:0] s;
(* matchi_type = "sharing", matchi_active = "out_act" *) output [1:0] out;{lk}

// ---- activity shift register (single go-pulse propagated; E={E} overlapped execs) ----
(* keep *) wire act0 = go;
(* keep *) reg [{OUT_HI}:1] actr;
always @(posedge clk) begin
    if (rst) actr <= {OUT_HI}'b0;
    else     actr <= {{actr[{OUT_HI-1}:1], act0}};
end
wire [{OUT_HI}:0] act = {{actr, act0}};
(* keep *) wire a_act   = |act[{A_HI}:0];
(* keep *) wire r_act   = |act[{R_HI}:0];
(* keep *) wire s_act   = |act[{S_HI}:1];
(* keep *) wire out_act = |act[{OUT_HI}:0];
"""


def tree_body(leaf, rndreuse=False):
    """Build the unrolled OR-reduction tree. Returns (verilog_text,
    (final_share0_name, final_share1_name))."""
    L = []
    o = L.append
    # level 0 masked bits: bit j = (a[2j], a[2j+1])
    cur = [(f"a[{2*j}]", f"a[{2*j+1}]") for j in range(N)]
    k = 0  # global gadget index
    for lvl in range(LEVELS):
        o(f"\n// ===== OR-reduce level {lvl}: {len(cur)} masked bits -> {len(cur)//2} =====")
        nxt = []
        for m in range(len(cur) // 2):
            (x0, x1) = cur[2 * m]
            (y0, y1) = cur[2 * m + 1]
            if rndreuse and k == 1:
                rk, sk = "r[0]", "s[0]"
                note = "  // BUG UNDER TEST: reuses gadget 0's randomness r[0]/s[0]"
            else:
                rk, sk = f"r[{k}]", f"s[{k}]"
                note = ""
            o(f"""wire nx0_{k} = {x0} ^ 1'b1;   // NOT childA, share-local (share 0)
wire ny0_{k} = {y0} ^ 1'b1;   // NOT childB, share-local (share 0)
// 1-cycle balance reg on the ina path (share-local, per-share): presents ina
// one cycle after inb, matching the gadget's ina@1 / inb@0 latency contract —
// the tree analog of the adder's staggered a_act/b_act windows.
(* keep = "yes" *) reg ina0_{k}, ina1_{k};
always @(posedge clk) begin
    ina0_{k} <= nx0_{k};
    ina1_{k} <= {x1};
end
wire w0_{k}, w1_{k};
{leaf} u_or_{k} ({note}
    .ina({{ina1_{k}, ina0_{k}}}), .inb({{{y1}, ny0_{k}}}),
    .rnd({rk}), .s({sk}), .clk(clk), .out({{w1_{k}, w0_{k}}}));
wire or0_{k} = w0_{k} ^ 1'b1;   // OR = NOT(AND(..)), share-local (share 0)
wire or1_{k} = w1_{k};""")
            nxt.append((f"or0_{k}", f"or1_{k}"))
            k += 1
        cur = nxt
    assert len(cur) == 1, f"tree did not reduce to 1 bit: {len(cur)}"
    assert k == NGAD, f"{k} gadgets emitted, expected {NGAD}"
    return "\n".join(L), cur[0]


def build(modname, leaf, comment, rndreuse=False, recomb=False):
    body, (f0, f1) = tree_body(leaf, rndreuse=rndreuse)
    parts = [header(modname, comment, recomb=recomb), body]
    parts.append(f"""
// ---- ISZERO = NOT( OR-reduce ) : share-local complement of share 0 ----
assign out[0] = {f0} ^ 1'b1;
assign out[1] = {f1};""")
    if recomb:
        parts.append("""
// BUG UNDER TEST: recombine the two shares of the ISZERO output. leak0 holds
// out[0]^out[1] (both shares) -> its input XOR gate is sensitive in ShareSet{0}
// AND ShareSet{1} -> MATCHI glitch leakage. Driven onto share 0 of leak_o.
(* keep = "yes" *) reg leak0, leak1;
always @(posedge clk) begin
    leak0 <= out[0] ^ out[1];
    leak1 <= 1'b0;
end
assign leak_o = {leak1, leak0};""")
    parts.append("\nendmodule\n")
    return "\n".join(parts)


def emit(fn, text, leaf, expect_count):
    n = text.count(leaf + " u_")          # count instantiations, not comment mentions
    assert n == expect_count, f"{fn}: leaf {leaf} x{n}, expected {expect_count}"
    with open(fn, "w") as f:
        f.write(text)
    print(f"wrote {fn}: {n} {leaf} instances")


C_MAIN = ("// 256-bit masked ISZERO — balanced binary OR-reduction tree over 255 O-PINI2\n"
          "// masked-AND leaves (De Morgan OR; share-local NOT/XOR). VERIFIED TARGET.\n"
          "// out recombines to 1 iff the masked 256-bit input a recombines to 0.\n"
          "// EQ(A,B) = ISZERO(A ^ B) (share-local XOR of the two operands first) — noted,\n"
          "// not built here. Unsigned LT/GT come from the subtractor borrow-out (add256).")
C_PINI = ("// LABEL CONTROL (EXPECTED PASS, single-pass): identical tree to iszero256 but\n"
          "// instantiates the PINI-relabelled leaf MSKand_opini2_d2_pini. Single-pass =>\n"
          "// PINI composition already suffices => PASS. Recorded, NOT counted as\n"
          "// non-vacuity (same reasoning as the adder's top_add256_pini).")
C_RND = ("// NEGATIVE CONTROL (must FAIL): identical to iszero256 except gadget 1 consumes\n"
         "// r[0]/s[0] — the SAME random bits as gadget 0 (both at level 0, same cycle) —\n"
         "// instead of its dedicated r[1]/s[1]. MATCHI must report the multi-use.")
C_RCB = ("// NEGATIVE CONTROL (must FAIL): identical to iszero256 plus one share-recombining\n"
         "// register (leak <= out[0] ^ out[1]). MATCHI must flag the gate sensitive in\n"
         "// multiple shares (glitch leakage).")

emit("iszero256.v",
     build("iszero256", GADGET, C_MAIN),
     GADGET, NGAD)
emit("iszero256_pini.v",
     build("iszero256_pini", GADGET + "_pini", C_PINI),
     GADGET + "_pini", NGAD)
emit("iszero256_rndreuse.v",
     build("iszero256_rndreuse", GADGET, C_RND, rndreuse=True),
     GADGET, NGAD)
emit("iszero256_recomb.v",
     build("iszero256_recomb", GADGET, C_RCB, recomb=True),
     GADGET, NGAD)

print(f"E={E} A_HI={A_HI} R_HI={R_HI} S_HI={S_HI} OUT_HI={OUT_HI}")
