#!/usr/bin/env python3
"""Emit top_add256_opini2.v — the 256-bit widening of the MATCHI-passed
top_add8_opini2.v (./). Same dataflow per bit, fully unrolled
so every one of the 512 gadget instances is textually explicit:

  b0_eff = b0 ^ sub (share 0 only); p = a ^ b_eff (share-wise);
  g = OPINI2-AND(a, b_eff); t = OPINI2-AND(carry, p);
  carry[i+1] = g ^ t; sum = p ^ carry; carry[0] = {share1=0, share0=sub}.

Dedicated randoms per instance: r[2i]/s[2i] -> u_generate_i,
r[2i+1]/s[2i+1] -> u_propagate_i (identical indexing to the 8-bit top).

Activity windows scale by the 8-bit formulas with E = 2N+2 overlapped
executions (8-bit: N=8, E=18 -> b [0,17], a [1,18], r [0,35], s [1,36],
out [0,38]).  N=256, E=514 -> b [0,513], a [1,514], r [0,1027], s [1,1028],
out [0,1030].

Invariant: the ONLY occurrences of the gadget module name in the output are
the 512 instantiations (grep -c of the name == 512).
"""
import sys

N = 256
E = 2 * N + 2          # overlapped executions (8-bit reference: 18)
B_HI = E - 1           # 513
A_HI = E               # 514
R_HI = 2 * E - 1       # 1027
S_HI = 2 * E           # 1028
OUT_HI = 2 * E + 2     # 1030
GADGET = "MSKand_opini2_d2"

L = []
o = L.append

o(f"""// {N}-bit two's-complement masked ripple adder — direct widening of the
// MATCHI-passed 8-bit top (./top_add8_opini2.v). EXACT same
// per-bit dataflow:
//   b0_eff = b0 ^ sub (share 0 only); p = a ^ b_eff (share-wise);
//   g = OPINI2-AND(a, b_eff); t = OPINI2-AND(carry, p);
//   carry[i+1] = g ^ t; sum = p ^ carry; carry[0] = {{share1=0, share0=sub}}.
// {2*N} assumed-OPINI gadget leaves (2 per bit; the byte-identical O-PINI2
// leaf from ./), each with a DEDICATED r and s random bit:
// r[2i]/s[2i] -> u_generate_i, r[2i+1]/s[2i+1] -> u_propagate_i — the same
// per-instance indexing as the 8-bit top. Every XOR is strictly share-local.
//
// Unrolled (no generate loop) so each gadget instance is textually explicit.
// Generated by gen_add256.py; do not hand-edit — regenerate instead.
//
// Dense sharing layout (share index fastest): port[2i] = share0 of bit i,
// port[2i+1] = share1 of bit i.
//
// Schedule (cycle 0 = go), scaled from the 8-bit top by E = 2N+2 = {E}
// back-to-back overlapped executions: b sensitive [0,{B_HI}], a sensitive
// [1,{A_HI}] (the HPC2 inb@0/ina@1 stagger). Randoms fresh per cycle over the
// whole sensitive-execution span (r [0,{R_HI}], s [1,{S_HI}] — covers the
// carry ripple tail: bit-i propagate has sensitive executions up to
// ~cycle {B_HI}+2i). Outputs windowed [0,{OUT_HI}].
(* matchi_prop = "PINI", matchi_strat = "composite_top", matchi_arch = "loopy", matchi_shares = 2 *)
module top_add{N}_opini2 (clk, rst, go, sub, a, b, r, s, sum, cout);
(* matchi_type = "clock" *)   input clk;
(* matchi_type = "control" *) input rst;
(* matchi_type = "control" *) input go;
(* matchi_type = "control" *) input sub;
(* matchi_type = "sharings_dense", matchi_active = "a_act" *) input [{2*N-1}:0] a;
(* matchi_type = "sharings_dense", matchi_active = "b_act" *) input [{2*N-1}:0] b;
(* matchi_type = "random", matchi_active = "r_act" *) input [{2*N-1}:0] r;
(* matchi_type = "random", matchi_active = "s_act" *) input [{2*N-1}:0] s;
(* matchi_type = "sharings_dense", matchi_active = "out_act" *) output [{2*N-1}:0] sum;
(* matchi_type = "sharing", matchi_active = "out_act" *) output [1:0] cout;

// ---- activity shift register ----
(* keep *) wire act0 = go;
(* keep *) reg [{OUT_HI}:1] actr;
always @(posedge clk) begin
    if (rst) actr <= {OUT_HI}'b0;
    else     actr <= {{actr[{OUT_HI-1}:1], act0}};
end
wire [{OUT_HI}:0] act = {{actr, act0}};
(* keep *) wire b_act   = |act[{B_HI}:0];
(* keep *) wire a_act   = |act[{A_HI}:1];
(* keep *) wire r_act   = |act[{R_HI}:0];
(* keep *) wire s_act   = |act[{S_HI}:1];
(* keep *) wire out_act = |act[{OUT_HI}:0];

// ---- the adder netlist (verbatim 8-bit dataflow, unrolled to {N} bits) ----
wire [{N}:0] carry0, carry1;
assign carry0[0] = sub;
assign carry1[0] = 1'b0;""")

for i in range(N):
    o(f"""
// ---- bit {i} ----
wire b0_eff_{i} = b[{2*i}] ^ sub;
wire p0_{i} = a[{2*i}]   ^ b0_eff_{i};
wire p1_{i} = a[{2*i+1}] ^ b[{2*i+1}];
wire g0_{i}, g1_{i}, t0_{i}, t1_{i};
{GADGET} u_generate_{i} (
    .ina({{a[{2*i+1}], a[{2*i}]}}), .inb({{b[{2*i+1}], b0_eff_{i}}}),
    .rnd(r[{2*i}]), .s(s[{2*i}]), .clk(clk), .out({{g1_{i}, g0_{i}}}));
{GADGET} u_propagate_{i} (
    .ina({{carry1[{i}], carry0[{i}]}}), .inb({{p1_{i}, p0_{i}}}),
    .rnd(r[{2*i+1}]), .s(s[{2*i+1}]), .clk(clk), .out({{t1_{i}, t0_{i}}}));
assign carry0[{i+1}] = g0_{i} ^ t0_{i};
assign carry1[{i+1}] = g1_{i} ^ t1_{i};
assign sum[{2*i}]   = p0_{i} ^ carry0[{i}];
assign sum[{2*i+1}] = p1_{i} ^ carry1[{i}];""")

o(f"""
assign cout = {{carry1[{N}], carry0[{N}]}};
endmodule""")

text = "\n".join(L) + "\n"
count = text.count(GADGET)
assert count == 2 * N, f"gadget name occurs {count} times, expected {2*N}"

out = sys.argv[1] if len(sys.argv) > 1 else "top_add256_opini2.v"
with open(out, "w") as f:
    f.write(text)
print(f"wrote {out}: {count} {GADGET} occurrences, {len(L)} chunks")
