#!/usr/bin/env python3
"""Emit the masked KECCAK-f permutation tops — a dedicated masked ROUND UNIT
(theta/rho/pi/iota share-local, chi via the MATCHI-passed O-PINI2 gadget
MSKand_opini2_d2, byte-identical leaf from ./, read-only
reference) iterated in place by a public FSM over all 12+2*log2(w) rounds.
Default w=64 = Keccak-f[1600], the EVM KECCAK256 permutation.

Design record:
  * State A[x][y][z]: 25 lanes of w bits, two shares, flat index
    idx = w*(5y+x)+z (the Keccak spec ordering). Dense sharing on the ports
    (port[2i]=share0, port[2i+1]=share1).
  * Per round (one FSM iteration, period K=6):
      theta: C[x]=xor_y A[x][y]; D[x]=C[x-1]^rot1(C[x+1]); A^=D  — share-local
      rho/pi: B[y][(2x+3y)%5] = rot(A[x][y], r[x][y])            — wiring only
      chi:   A'[x][y] = B[x][y] ^ (~B[x+1][y] AND B[x+2][y])
             NOT = complement share 0 only; AND = one O-PINI2 gadget per state
             bit (25w gadgets, each with a DEDICATED r[k]/s[k] random bit);
             the outer XOR is share-local.
      iota:  A'[0][0] ^= RC[round] (public constant, XORed into share 0 only).
  * The 25w gadgets are REUSED bubble-free across all rounds with genuine
    feedback (each gadget's next inputs depend on all gadgets' previous
    outputs through theta) — the OPINI regime. The PINI label control is
    EXPECTED to fail with the transition-leakage error (cf. div16_pini), which
    is the live OPINI-vs-PINI non-vacuity evidence.
  * Gadget latency contract (inb@0, rnd@0, ina@1, s@1, out@3): inb = B[x+2]
    (combinational from the stable round register), ina = nb_d (1-cycle
    per-share balance register of ~B[x+1] — the iszero256 pattern).
    Executions are consistent from round offset e=1; out stable during
    offsets 4..; the round register updates at the edge ending offset K-1=5.
  * Rho offsets and round constants are DERIVED FROM THE SPEC in this
    generator (offsets via the (t+1)(t+2)/2 walk, RC via the degree-8 LFSR)
    and asserted against published values; the w=64 smoke additionally anchors
    on the XKCP zero-state test vector lane(0,0) = 0xF1258F7940E1DDE7.
  * Activity windows from the idempotent cycle counter (public control),
    validated by the div16 pilot matrix.

State-register sensitivity is BOUNDED IN TIME (mul256/div256 pattern): clr
zeroes the state register after the output window; the balance registers
drain one cycle later; there is no carry chain, so the drain tail is short.

Emits (suffix = 25*w): keccakf{25w}.v (OPINI target), _pini (label control,
expected transition-leakage FAIL), _rndreuse (NEG control, must FAIL: u_chi_1
reuses u_chi_0's r/s), _recomb (NEG control, must FAIL: register recombining
o[0]^o[1]); tb_keccakf{25w}.v (MATCHI tb); tb_smoke_keccakf{25w}.v.
Generated by gen_keccakf.py; do not hand-edit — regenerate instead.
Usage: gen_keccakf.py [w]   (default 64; pilot: 4)
"""
import sys

W = int(sys.argv[1]) if len(sys.argv) > 1 else 64
L = W.bit_length() - 1
assert 2 ** L == W, "w must be a power of two"
NR = 12 + 2 * L                 # rounds
B = 25 * W                      # state bits
GADGET = "MSKand_opini2_d2"
NG = B                          # one chi gadget per state bit

# ---- Keccak spec tables, derived then asserted against published values ----
def rho_offsets():
    r = [[0] * 5 for _ in range(5)]
    x, y = 1, 0
    for t in range(24):
        r[x][y] = ((t + 1) * (t + 2) // 2) % W
        x, y = y, (2 * x + 3 * y) % 5
    return r

def rc_bit(t):
    if t % 255 == 0:
        return 1
    R = 1
    for _ in range(t % 255):
        R <<= 1
        if R & 0x100:
            R ^= 0x171
        R &= 0xFF
    return R & 1

def round_constants():
    RC = []
    for ir in range(NR):
        v = 0
        for j in range(L + 1):
            v |= rc_bit(j + 7 * ir) << (2 ** j - 1)
        RC.append(v)
    return RC

RHO = rho_offsets()
RC = round_constants()
if W == 64:
    assert RHO[1][0] == 1 and RHO[2][2] == 43 and RHO[3][2] == 25 and RHO[0][4] == 18
    assert RC[0] == 0x1 and RC[1] == 0x8082 and RC[23] == 0x8000000080008008

def idx(x, y, z):
    return W * (5 * y + x) + z

def rot(x, y, z):
    """source bit z' of A[x][y] that lands in B position bit z after rho."""
    return (z - RHO[x][y]) % W

# ---- reference permutation (for smoke expected values) ----
def keccakf_ref(lanes):
    lanes = list(lanes)
    M = (1 << W) - 1
    def rotl(v, n):
        n %= W
        return ((v << n) | (v >> (W - n))) & M
    for ir in range(NR):
        C = [lanes[x] ^ lanes[x + 5] ^ lanes[x + 10] ^ lanes[x + 15] ^ lanes[x + 20]
             for x in range(5)]
        D = [C[(x - 1) % 5] ^ rotl(C[(x + 1) % 5], 1) for x in range(5)]
        A = [lanes[5 * y + x] ^ D[x] for y in range(5) for x in range(5)]
        Bl = [0] * 25
        for x in range(5):
            for y in range(5):
                Bl[5 * ((2 * x + 3 * y) % 5) + y] = rotl(A[5 * y + x], RHO[x][y])
        lanes = [Bl[5 * y + x] ^ ((~Bl[5 * y + (x + 1) % 5]) & Bl[5 * y + (x + 2) % 5]) & M
                 for y in range(5) for x in range(5)]
        lanes[0] ^= RC[ir]
    return lanes

if W == 64:   # XKCP KeccakF-1600-IntermediateValues.txt anchor
    z = keccakf_ref([0] * 25)
    assert z[0] == 0xF1258F7940E1DDE7, hex(z[0])
    assert z[1] == 0x84D5CCF933C0478A, hex(z[1])

# ---- schedule constants (cycle 0 = go; registers load at edge into cycle 1) ----
import os
K = 6                           # round period
OUT_STABLE = K * NR + 1         # o (register) stable from here
CLR_AT = K * NR + 12            # state register cleared at this count
# DEFAULT: the activity windows NEVER CLOSE inside the trace — the permutation
# state is persistent-sensitive by nature and MATCHI does not drain its
# sensitivity after the share-local clear at w>=16 (w<=8 happened to drain —
# an abc cone-factoring accident, not a property to rely on; measured live:
# bounded windows PASS at w=4/8 and FAIL with "output share ... not at a valid
# latency, but it is (glitch-)sensitive" at w=16/64). The tb randfills r/s
# every cycle and $finishes while the windows are still open — conservative:
# every cycle of the trace is annotated sensitive-and-fresh.
# KECCAK_BOUNDED_WINDOWS=1 restores the (w<=8-only) bounded annotation for the
# record/repro of that finding.
if os.environ.get("KECCAK_BOUNDED_WINDOWS"):
    OUT_HI = CLR_AT + 8         # short drain: balance regs + gadget latency
    R_HI = OUT_HI + 2
    S_HI = R_HI + 1
    TB_CYC_OVERRIDE = None
else:
    OUT_HI = CLR_AT + 500       # far past every cycle the trace can reach
    R_HI = OUT_HI + 2
    S_HI = R_HI + 1
    TB_CYC_OVERRIDE = CLR_AT + 40
CNTW = (S_HI + 2).bit_length() + 1
TB_CYC = TB_CYC_OVERRIDE if TB_CYC_OVERRIDE else S_HI + 30
SMOKE_SAMPLE = CLR_AT - 5
SMOKE_GAP = 30
ITW = max(2, (NR - 1).bit_length())


def share_concat(port, share, n):
    return "{" + ", ".join(f"{port}[{2*j+share}]" for j in range(n - 1, -1, -1)) + "}"


def header(modname, leaf, comment, recomb=False):
    ep = ", leak_o" if recomb else ""
    lk = ('\n(* matchi_type = "sharing", matchi_active = "out_act" *) '
          "output [1:0] leak_o;") if recomb else ""
    # chained ternary, NOT a case block: yosys would infer the case table as a
    # $memrd_v2 memory cell, which MATCHI rejects as neither module nor gate.
    rc_mux = " :\n               ".join(
        f"(rnd_i == {ITW}'d{i}) ? {W}'h{RC[i]:0{(W+3)//4}x}" for i in range(NR))
    rc_mux += f" :\n               {W}'d0"
    return f"""{comment}
// Masked Keccak-f[{B}] ({NR} rounds, w={W}): one masked round unit — chi via
// {NG} assumed-OPINI gadget leaves u_chi_* (one per state bit, DEDICATED
// r[k]/s[k] each), theta/rho/pi/iota strictly share-local — iterated in place
// by a public FSM. Dense sharing layout: port[2i]=share0, port[2i+1]=share1,
// state flat index w*(5y+x)+z (Keccak spec ordering).
// Schedule: load @0; round i occupies cycles [1+{K}i, {K}+{K}i]; o (register)
// stable from cycle {OUT_STABLE}; state cleared (share-local, to public 0) at
// cycle {CLR_AT}; randoms fresh [0,{R_HI}].
(* matchi_prop = "PINI", matchi_strat = "composite_top", matchi_arch = "loopy", matchi_shares = 2 *)
module {modname} (clk, rst, go, a, r, s, o{ep});
(* matchi_type = "clock" *)   input clk;
(* matchi_type = "control" *) input rst;
(* matchi_type = "control" *) input go;
(* matchi_type = "sharings_dense", matchi_active = "a_act" *) input [{2*B-1}:0] a;
(* matchi_type = "random", matchi_active = "r_act" *) input [{NG-1}:0] r;
(* matchi_type = "random", matchi_active = "s_act" *) input [{NG-1}:0] s;
(* matchi_type = "sharings_dense", matchi_active = "out_act" *) output [{2*B-1}:0] o;{lk}

// ---- activity windows from an idempotent cycle counter (public control;
// counts 1.. from the go pulse, saturates — the div256 pattern) ----
reg [{CNTW-1}:0] cnt;
always @(posedge clk) begin
    if (rst)                       cnt <= {CNTW}'d0;
    else if (go)                   cnt <= {CNTW}'d1;
    else if (cnt != {CNTW}'d0 && cnt != {CNTW}'d{S_HI + 2}) cnt <= cnt + {CNTW}'d1;
end
(* keep *) wire a_act   = go || (cnt == {CNTW}'d1);   // operand consumed at load
(* keep *) wire r_act   = go || (cnt >= {CNTW}'d1 && cnt <= {CNTW}'d{R_HI});
(* keep *) wire s_act   =       (cnt >= {CNTW}'d1 && cnt <= {CNTW}'d{S_HI});
(* keep *) wire out_act = go || (cnt >= {CNTW}'d1 && cnt <= {CNTW}'d{OUT_HI});
(* keep *) wire clr     = (cnt == {CNTW}'d{CLR_AT});  // bounded sensitivity

// ---- public FSM: round counter + phase (control only, data-independent) ----
reg running;
reg [{ITW-1}:0] rnd_i;
reg [2:0] ph;
always @(posedge clk) begin
    if (rst) begin running <= 1'b0; rnd_i <= 0; ph <= 0; end
    else if (go) begin running <= 1'b1; rnd_i <= 0; ph <= 0; end
    else if (running) begin
        if (ph == {K-1}) begin
            ph <= 0;
            if (rnd_i == {ITW}'d{NR-1}) begin running <= 1'b0; rnd_i <= 0; end
            else rnd_i <= rnd_i + {ITW}'d1;
        end else ph <= ph + 3'd1;
    end
end

// ---- iota round constant (public, XORed into share 0 of lane (0,0)) ----
wire [{W-1}:0] rc_cur = {rc_mux};

// ---- state registers (per-share; NEVER mix share 0 and share 1) ----
reg [{B-1}:0] St0, St1;
wire [{B-1}:0] Bx0, Bx1;         // after theta+rho+pi (share-local wiring)
wire [{B-1}:0] w_chi0, w_chi1;   // chi gadget outputs

always @(posedge clk) begin
    if (rst || clr) begin
        St0 <= 0; St1 <= 0;
    end else if (go) begin        // dense-share unpack, share-local
        St0 <= {share_concat('a', 0, B)};
        St1 <= {share_concat('a', 1, B)};
    end else if (running && ph == {K-1}) begin
        // chi outer XOR + iota, all share-local (iota into share 0 only)
        St0 <= Bx0 ^ w_chi0 ^ {{{{{B-W}{{1'b0}}}}, rc_cur}};
        St1 <= Bx1 ^ w_chi1;
    end
end

// ---- theta (share-local XOR network) ----
"""


def theta_rho_pi_body():
    Lns = []
    o = Lns.append
    for sh in (0, 1):
        o(f"wire [{5*W-1}:0] C{sh}, D{sh};")
        for x in range(5):
            for z in range(W):
                terms = " ^ ".join(f"St{sh}[{idx(x, y, z)}]" for y in range(5))
                o(f"assign C{sh}[{x*W+z}] = {terms};")
        for x in range(5):
            for z in range(W):
                o(f"assign D{sh}[{x*W+z}] = C{sh}[{((x-1)%5)*W+z}] ^ "
                  f"C{sh}[{((x+1)%5)*W+(z-1)%W}];")
    o("\n// ---- rho + pi (pure wiring): Bx[(2x+3y)%5 lane-row perm][z] ----")
    for sh in (0, 1):
        for x in range(5):
            for y in range(5):
                xp, yp = y, (2 * x + 3 * y) % 5   # B[xp][yp] = rot(Atheta[x][y])
                for z in range(W):
                    zs = rot(x, y, z)
                    o(f"assign Bx{sh}[{idx(xp, yp, z)}] = "
                      f"St{sh}[{idx(x, y, zs)}] ^ D{sh}[{x*W+zs}];")
    return "\n".join(Lns)


def chi_body(leaf, rndreuse=False):
    Lns = []
    o = Lns.append
    o(f"""
// ---- chi: w_chi[x,y,z] = (~Bx[x+1,y,z]) AND Bx[x+2,y,z] ----
// NOT is share-local (complement share 0 only); nb_d* are the 1-cycle
// per-share balance registers feeding every gadget ina (contract ina@1).
wire [{B-1}:0] nb_src0, nb_src1;
wire [{B-1}:0] nb0 = ~nb_src0;   // share-local complement, share 0 only
wire [{B-1}:0] nb1 =  nb_src1;
reg  [{B-1}:0] nb_d0, nb_d1;
always @(posedge clk) begin
    nb_d0 <= nb0;
    nb_d1 <= nb1;
end""")
    for x in range(5):
        for y in range(5):
            for z in range(W):
                i = idx(x, y, z)
                o(f"assign nb_src0[{i}] = Bx0[{idx((x+1)%5, y, z)}];  "
                  f"assign nb_src1[{i}] = Bx1[{idx((x+1)%5, y, z)}];")
    o("")
    for x in range(5):
        for y in range(5):
            for z in range(W):
                i = idx(x, y, z)
                ib = idx((x + 2) % 5, y, z)
                if rndreuse and i == 1:
                    rk, sk = "r[0]", "s[0]"
                    note = "  // BUG UNDER TEST: reuses u_chi_0's randomness"
                else:
                    rk, sk = f"r[{i}]", f"s[{i}]"
                    note = ""
                o(f"""{leaf} u_chi_{i} ({note}
    .ina({{nb_d1[{i}], nb_d0[{i}]}}), .inb({{Bx1[{ib}], Bx0[{ib}]}}),
    .rnd({rk}), .s({sk}), .clk(clk), .out({{w_chi1[{i}], w_chi0[{i}]}}));""")
    return "\n".join(Lns)


def outputs_body():
    return "\n".join(f"assign o[{2*j}] = St0[{j}];  assign o[{2*j+1}] = St1[{j}];"
                     for j in range(B))


def build(modname, leaf, comment, rndreuse=False, recomb=False):
    parts = [header(modname, leaf, comment, recomb=recomb),
             theta_rho_pi_body(),
             chi_body(leaf, rndreuse=rndreuse),
             "\n// ---- outputs: dense re-pack of the state register ----",
             outputs_body()]
    if recomb:
        parts.append("""
// BUG UNDER TEST: recombine the two shares of o bit 0. leak0 holds
// o[0]^o[1] (both shares) -> the XOR gate is sensitive in ShareSet{0}
// AND ShareSet{1} -> MATCHI glitch leakage. Driven onto share 0 of leak_o.
(* keep = "yes" *) reg leak0, leak1;
always @(posedge clk) begin
    leak0 <= o[0] ^ o[1];
    leak1 <= 1'b0;
end
assign leak_o = {leak1, leak0};""")
    parts.append("\nendmodule\n")
    return "\n".join(parts)


def emit(fn, text, leaf, expect_count):
    n = text.count(leaf + " u_")
    assert n == expect_count, f"{fn}: leaf {leaf} x{n}, expected {expect_count}"
    with open(fn, "w") as f:
        f.write(text)
    print(f"wrote {fn}: {n} {leaf} instances")


NM = f"keccakf{B}"
C_MAIN = (f"// Masked Keccak-f[{B}] — dedicated masked round unit ({NG} O-PINI2 chi\n"
          f"// leaves) iterated over all {NR} rounds. VERIFIED TARGET.\n"
          "// Bubble-free gadget reuse across rounds with genuine feedback (theta\n"
          "// mixes every gadget's previous output into every next input) — OPINI regime.")
C_PINI = ("// LABEL CONTROL: identical netlist but instantiates the PINI-relabelled\n"
          "// leaf MSKand_opini2_d2_pini. This datapath REUSES gadgets bubble-free\n"
          "// with feedback, so MATCHI's transition rule for PINI leaves is EXPECTED\n"
          "// to reject it (cf. div16_pini). Verdict recorded either way.")
C_RND = ("// NEGATIVE CONTROL (must FAIL): identical to the target except u_chi_1\n"
         "// consumes the SAME random bits as u_chi_0, active in the same cycles,\n"
         "// instead of its dedicated pair. MATCHI must report multi-use.")
C_RCB = ("// NEGATIVE CONTROL (must FAIL): identical to the target plus one share-\n"
         "// recombining register (leak0 <= o[0]^o[1]). MATCHI must flag the\n"
         "// gate sensitive in multiple shares (glitch leakage).")

emit(f"{NM}.v", build(NM, GADGET, C_MAIN), GADGET, NG)
emit(f"{NM}_pini.v", build(f"{NM}_pini", GADGET + "_pini", C_PINI),
     GADGET + "_pini", NG)
emit(f"{NM}_rndreuse.v", build(f"{NM}_rndreuse", GADGET, C_RND, rndreuse=True),
     GADGET, NG)
emit(f"{NM}_recomb.v", build(f"{NM}_recomb", GADGET, C_RCB, recomb=True),
     GADGET, NG)

# ---------------- MATCHI testbench ----------------
A_W = 2 * B
A_WW = (A_W + 31) // 32
RS_WW = (NG + 31) // 32
tb = f"""// MATCHI testbench for the {NM} tops. Same convention as the verified
// adder/iszero/mul/div tbs: values are irrelevant to MATCHI (symbolic); only
// signal-activity timing is read from the VCD. Run length covers the deepest
// window (r [0,{R_HI}]) plus margin.
// Generated by gen_keccakf.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD {NM}
`endif
module tb ();
parameter HP = 5;
reg clk, rst, go;
reg [{A_WW*32-1}:0] a;
reg [{RS_WW*32-1}:0] r, s;
wire [{A_W-1}:0] o;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .go(go), .a(a[{A_W-1}:0]),
             .r(r[{NG-1}:0]), .s(s[{NG-1}:0]), .o(o)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < {A_WW}; w = w + 1) a[w*32 +: 32] = $random;
        for (w = 0; w < {RS_WW}; w = w + 1) begin
            r[w*32 +: 32] = $random;
            s[w*32 +: 32] = $random;
        end
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; go = 1'b0;
    a = 0; r = 0; s = 0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // cycle 0: one-cycle go pulse
    @(negedge clk); go = 1'b1; randfill;
    @(negedge clk); go = 1'b0; randfill;
    for (i = 0; i < {TB_CYC}; i = i + 1) begin
        @(negedge clk); randfill;
    end
    $finish;
end
endmodule
"""
with open(f"tb_{NM}.v", "w") as f:
    f.write(tb)
print(f"wrote tb_{NM}.v")

# ---------------- functional smoke testbench ----------------
# Expected values from the generator-embedded reference permutation (itself
# anchored on the XKCP zero-state vector for w=64 by the asserts above).
import random as _rnd
_rnd.seed(0xC0FFEE + W)
vecs = [[0] * 25]
for _ in range(3):
    vecs.append([_rnd.getrandbits(W) for _ in range(25)])
def st_hex(lanes):
    v = 0
    for i, ln in enumerate(lanes):
        v |= ln << (i * W)
    return f"{B}'h{v:0{(B+3)//4}x}"
checks = "\n".join(
    f"    check({st_hex(v)}, {st_hex(keccakf_ref(v))});" for v in vecs)

smoke = f"""// Functional smoke test for {NM} (NOT a security check — MATCHI is the
// separate verification step). Shares the state with a random mask, pulses
// go, waits out the {NR} rounds, recombines the output shares, compares
// against the spec reference permutation (computed by gen_keccakf.py; for
// w=64 the reference is anchored on the XKCP zero-state test vector
// F1258F7940E1DDE7...). Fresh gadget randoms every cycle.
// Generated by gen_keccakf.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [{2*B-1}:0] a;
reg [{RS_WW*32-1}:0] rr, ss;
wire [{2*B-1}:0] o;

{NM} dut (.clk(clk), .rst(rst), .go(go), .a(a),
          .r(rr[{NG-1}:0]), .s(ss[{NG-1}:0]), .o(o));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < {RS_WW}; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [{B-1}:0] am, got;
integer j;
task check(input [{B-1}:0] x, input [{B-1}:0] expd);
    begin
        for (j = 0; j < {(B+31)//32}; j = j + 1) am[j*32 +: 32] = $random;
        for (j = 0; j < {B}; j = j + 1) begin
            a[2*j] = x[j] ^ am[j];  a[2*j+1] = am[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat ({SMOKE_SAMPLE}) @(negedge clk);
        for (j = 0; j < {B}; j = j + 1) got[j] = o[2*j] ^ o[2*j+1];
        if (got !== expd) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  in =%h", x);
            $display("  got=%h", got);
            $display("  exp=%h", expd);
        end else begin
            $display("PASS lane00=%h", got[{W-1}:0]);
        end
        repeat ({SMOKE_GAP}) @(negedge clk);   // past clr before the next check
    end
endtask

initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
{checks}
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
"""
with open(f"tb_smoke_{NM}.v", "w") as f:
    f.write(smoke)
print(f"wrote tb_smoke_{NM}.v")

print(f"w={W} B={B} NR={NR} NG={NG} K={K} OUT_STABLE={OUT_STABLE} "
      f"OUT_HI={OUT_HI} CLR_AT={CLR_AT} R_HI={R_HI} S_HI={S_HI} TB_CYC={TB_CYC}")
