#!/usr/bin/env python3
"""Emit the masked storage-path tops (SLOAD/SSTORE scratchpad) — an in-domain
two-share scratchpad with TRANSITION-SAFE PAGING: the two shares of every
word live in physically-separate lanes (separate registers, separate read
muxes, separate paging registers) and always MOVE TOGETHER in the same cycle.
No gadgets, no randomness: SLOAD/SSTORE are pure data movement, and every
gate in the unit touches exactly one share of one value.

Design record:
  * D words x W bits, two lanes: per-word named registers m0_i / m1_i —
    EXPLICIT registers, not a Verilog memory array, because yosys infers
    $memrd_v2 cells from arrays and MATCHI rejects those (hit live on the
    keccak iota ROM).
  * Addresses/enables are PUBLIC control (EVM storage slot numbers of the DEX
    contract are public; only the 256-bit contents are secret).
  * SSTORE: we + waddr + wdata (dense sharing). Write decode per lane —
    lane 0 logic sees only share-0 bits, lane 1 only share-1 bits.
  * SLOAD: raddr; registered read port rreg0/rreg1 <= per-lane chained-ternary
    read mux, every cycle. Read-port TRANSITIONS (word X -> word Y) happen
    strictly within one lane, i.e. leak at most masked-share transitions —
    this is exactly what the MATCHI default transition model checks.
  * PAGING (SLOAD->move->SSTORE without leaving the masked domain): pg_go
    latches pg_from/pg_to; cycle 1 reads BOTH lane registers pg0 <= mux0,
    pg1 <= mux1 at the SAME edge; cycle 2 writes both lanes back to pg_to.
    Paired shares move together through physically-separate lanes.
  * NON-VACUITY: the *_sharedbus control violates exactly this rule — ONE
    time-multiplexed bus register carries share 0 of the word on cycle 1 and
    share 1 on cycle 2 (then writes back over two more cycles). The bus
    register's value transition (share0 -> share1 of the same word) combines
    the shares in the transition model; MATCHI must FAIL it. The *_recomb
    control is the classic rdata[0]^rdata[1] recombining register.
  * No r/s ports and no gadget instances: there is nothing to refresh — the
    unit is share-wise linear (wiring + muxes). L1 is vacuous; the whole
    security claim is the L2 MATCHI run + the two failing controls.
  * Sensitivity is NOT time-bounded (storage persists by design, unlike the
    clr-bounded ALU tops); out_act stays high from the first write to the end
    of the trace, and the MATCHI tb ends while words are still sensitive.

Emits (suffix = {W}x{D}): store{W}x{D}.v (target), _sharedbus (NEG control,
must FAIL: transition share recombination on the paging bus), _recomb (NEG
control, must FAIL: glitch share recombination on the read port);
tb_store{W}x{D}.v (MATCHI tb; drives writes, paging, reads), tb_smoke_*.v.
Generated by gen_store256.py; do not hand-edit — regenerate instead.
Usage: gen_store256.py [W] [D]   (default 256 8; pilot: 16 4)
"""
import sys

W = int(sys.argv[1]) if len(sys.argv) > 1 else 256
D = int(sys.argv[2]) if len(sys.argv) > 2 else 8
AW = max(1, (D - 1).bit_length())
NM = f"store{W}x{D}"


def share_concat(port, share, n):
    return "{" + ", ".join(f"{port}[{2*j+share}]" for j in range(n - 1, -1, -1)) + "}"


def rmux(lane, addr):
    """Chained-ternary read mux for one lane (no memory inference)."""
    e = f"m{lane}_{D-1}"
    for i in range(D - 2, -1, -1):
        e = f"(({addr} == {AW}'d{i}) ? m{lane}_{i} : {e})"
    return e


def header(modname, comment, recomb=False):
    ep = ", leak_o" if recomb else ""
    lk = ('\n(* matchi_type = "sharing", matchi_active = "out_act" *) '
          "output [1:0] leak_o;") if recomb else ""
    return f"""{comment}
// Masked storage path: {D} x {W}-bit two-share scratchpad, two physically-
// separate lanes (share 0: m0_*, share 1: m1_*), public addresses, registered
// per-lane read port, 2-cycle two-lane paging pipeline. No gadgets, no
// randomness — every gate touches exactly one share of one value.
// Dense sharing layout: port[2i]=share0, port[2i+1]=share1.
(* matchi_prop = "PINI", matchi_strat = "composite_top", matchi_arch = "loopy", matchi_shares = 2 *)
module {modname} (clk, rst, we, waddr, wdata, raddr, rdata,
                  pg_go, pg_from, pg_to{ep});
(* matchi_type = "clock" *)   input clk;
(* matchi_type = "control" *) input rst;
(* matchi_type = "control" *) input we;
(* matchi_type = "control" *) input [{AW-1}:0] waddr;
(* matchi_type = "control" *) input [{AW-1}:0] raddr;
(* matchi_type = "control" *) input pg_go;
(* matchi_type = "control" *) input [{AW-1}:0] pg_from;
(* matchi_type = "control" *) input [{AW-1}:0] pg_to;
(* matchi_type = "sharings_dense", matchi_active = "a_act" *) input [{2*W-1}:0] wdata;
(* matchi_type = "sharings_dense", matchi_active = "out_act" *) output [{2*W-1}:0] rdata;{lk}

// ---- activity: wdata is consumed exactly when we is high; outputs (and the
// scratchpad) are sensitive from the first write to the end of the trace ----
reg seen_w;
always @(posedge clk) begin
    if (rst) seen_w <= 1'b0;
    else if (we) seen_w <= 1'b1;
end
(* keep *) wire a_act   = we;
(* keep *) wire out_act = we || seen_w;
"""


def body(sharedbus=False):
    Lns = []
    o = Lns.append
    o(f"// ---- lane registers: {D} words per lane, explicit (no memory inference) ----")
    for lane in (0, 1):
        for i in range(D):
            o(f"reg [{W-1}:0] m{lane}_{i};")
    o(f"""
// ---- per-lane write decode (lane k logic sees only share-k bits) ----
wire [{W-1}:0] wd0 = {share_concat('wdata', 0, W)};
wire [{W-1}:0] wd1 = {share_concat('wdata', 1, W)};""")
    if not sharedbus:
        o(f"""
// ---- transition-safe paging: both lane registers load at the SAME edge,
// each from its own lane's read mux; write-back one cycle later ----
reg pg_rd, pg_wr;                 // 2-cycle sequence (public control)
reg [{AW-1}:0] pg_src, pg_dst;
reg [{W-1}:0] pg0, pg1;           // physically-separate paging lanes
always @(posedge clk) begin
    if (rst) begin pg_rd <= 1'b0; pg_wr <= 1'b0; end
    else begin
        pg_rd <= pg_go;
        pg_wr <= pg_rd;
        if (pg_go) begin pg_src <= pg_from; pg_dst <= pg_to; end
        if (pg_rd) begin
            pg0 <= {rmux(0, 'pg_src')};   // share 0 lane
            pg1 <= {rmux(1, 'pg_src')};   // share 1 lane — SAME edge
        end
    end
end""")
    else:
        o(f"""
// BUG UNDER TEST (shared-bus paging): ONE time-multiplexed bus register
// carries share 0 of the paged word on the first cycle and share 1 on the
// next — the bus value TRANSITION (share0 -> share1 of the same word)
// combines both shares; the MATCHI transition model must reject it.
reg pg_rd0, pg_rd1, pg_wr0, pg_wr1;   // 4-cycle serialized sequence
reg [{AW-1}:0] pg_src, pg_dst;
reg [{W-1}:0] bus;                    // the single shared lane
reg [{W-1}:0] pg0_hold;
always @(posedge clk) begin
    if (rst) begin pg_rd0 <= 1'b0; pg_rd1 <= 1'b0; pg_wr0 <= 1'b0; pg_wr1 <= 1'b0; end
    else begin
        pg_rd0 <= pg_go;
        pg_rd1 <= pg_rd0;
        pg_wr0 <= pg_rd1;
        pg_wr1 <= pg_wr0;
        if (pg_go) begin pg_src <= pg_from; pg_dst <= pg_to; end
        if (pg_rd0)      bus <= {rmux(0, 'pg_src')};   // share 0 on the bus...
        else if (pg_rd1) begin
            pg0_hold <= bus;
            bus <= {rmux(1, 'pg_src')};                // ...then share 1: TRANSITION BUG
        end
    end
end
wire pg_wr = pg_wr0;
wire [{W-1}:0] pg0 = pg0_hold;
wire [{W-1}:0] pg1 = bus;""")
    o("\n// ---- lane 0 writes (SSTORE + paging write-back) ----")
    for lane in (0, 1):
        o(f"always @(posedge clk) begin")
        for i in range(D):
            o(f"    if (we && waddr == {AW}'d{i}) m{lane}_{i} <= wd{lane};")
        for i in range(D):
            o(f"    if (pg_wr && pg_dst == {AW}'d{i}) m{lane}_{i} <= pg{lane};")
        o("end")
    o(f"""
// ---- registered per-lane read port (SLOAD); transitions stay in-lane ----
reg [{W-1}:0] rreg0, rreg1;
always @(posedge clk) begin
    rreg0 <= {rmux(0, 'raddr')};
    rreg1 <= {rmux(1, 'raddr')};
end""")
    for j in range(W):
        o(f"assign rdata[{2*j}] = rreg0[{j}];  assign rdata[{2*j+1}] = rreg1[{j}];")
    return "\n".join(Lns)


def build(modname, comment, sharedbus=False, recomb=False):
    parts = [header(modname, comment, recomb=recomb), body(sharedbus=sharedbus)]
    if recomb:
        parts.append("""
// BUG UNDER TEST: recombine the two shares of rdata bit 0. leak0 holds
// rdata[0]^rdata[1] (both shares) -> the XOR gate is sensitive in ShareSet{0}
// AND ShareSet{1} -> MATCHI glitch leakage. Driven onto share 0 of leak_o.
(* keep = "yes" *) reg leak0, leak1;
always @(posedge clk) begin
    leak0 <= rdata[0] ^ rdata[1];
    leak1 <= 1'b0;
end
assign leak_o = {leak1, leak0};""")
    parts.append("\nendmodule\n")
    return "\n".join(parts)


def emit(fn, text):
    with open(fn, "w") as f:
        f.write(text)
    print(f"wrote {fn}")


C_MAIN = (f"// Masked storage path {W}x{D} (SLOAD/SSTORE scratchpad + transition-safe\n"
          "// two-lane paging). VERIFIED TARGET. Paired shares move together through\n"
          "// physically-separate lanes; no gate ever sees both shares of a value.")
C_BUS = ("// NEGATIVE CONTROL (must FAIL): paging serialized through ONE shared bus\n"
         "// register — share 0 then share 1 of the same word on consecutive cycles.\n"
         "// The bus transition combines the shares; the MATCHI transition model\n"
         "// must reject it. This is the exact bug two-lane paging exists to prevent.")
C_RCB = ("// NEGATIVE CONTROL (must FAIL): identical to the target plus one share-\n"
         "// recombining register (leak0 <= rdata[0]^rdata[1]). MATCHI must flag the\n"
         "// gate sensitive in multiple shares (glitch leakage).")

emit(f"{NM}.v", build(NM, C_MAIN))
emit(f"{NM}_sharedbus.v", build(f"{NM}_sharedbus", C_BUS, sharedbus=True))
emit(f"{NM}_recomb.v", build(f"{NM}_recomb", C_RCB, recomb=True))

# ---------------- MATCHI testbench ----------------
WW = (2 * W + 31) // 32
tb = f"""// MATCHI testbench for the {NM} tops: {D} writes (fresh sharings), a page
// {D-1}->0 through the paging path, then continuous reads sweeping all words.
// Values are irrelevant to MATCHI (symbolic); activity timing matters:
// a_act = we cycles, out_act = first write .. end of trace.
// Generated by gen_store256.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD {NM}
`endif
module tb ();
parameter HP = 5;
reg clk, rst, we, pg_go;
reg [{AW-1}:0] waddr, raddr, pg_from, pg_to;
reg [{WW*32-1}:0] wdata;
wire [{2*W-1}:0] rdata;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .we(we), .waddr(waddr),
             .wdata(wdata[{2*W-1}:0]), .raddr(raddr), .rdata(rdata),
             .pg_go(pg_go), .pg_from(pg_from), .pg_to(pg_to)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < {WW}; w = w + 1) wdata[w*32 +: 32] = $random;
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; we = 1'b0; pg_go = 1'b0;
    waddr = 0; raddr = 0; pg_from = 0; pg_to = 0; wdata = 0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // SSTORE a fresh sharing into every word
    for (i = 0; i < {D}; i = i + 1) begin
        @(negedge clk); we = 1'b1; waddr = i[{AW-1}:0]; randfill;
    end
    @(negedge clk); we = 1'b0; randfill;
    // page word {D-1} -> word 0 (through the paging lanes)
    @(negedge clk); pg_go = 1'b1; pg_from = {AW}'d{D-1}; pg_to = {AW}'d0; randfill;
    @(negedge clk); pg_go = 1'b0; randfill;
    // continuous SLOAD sweep (read-port transitions across all words)
    for (i = 0; i < 6*{D}; i = i + 1) begin
        @(negedge clk); raddr = i % {D}; randfill;
    end
    // interleaved write/read tail
    for (i = 0; i < {D}; i = i + 1) begin
        @(negedge clk); we = 1'b1; waddr = i[{AW-1}:0]; raddr = ({D} - 1 - i); randfill;
        @(negedge clk); we = 1'b0; randfill;
    end
    repeat (10) @(negedge clk);
    $finish;
end
endmodule
"""
with open(f"tb_{NM}.v", "w") as f:
    f.write(tb)
print(f"wrote tb_{NM}.v")

# ---------------- functional smoke testbench ----------------
NW = (W + 31) // 32
smoke = f"""// Functional smoke test for {NM} (NOT a security check). Writes {D} known
// words as fresh sharings, reads each back recombined, pages {D-1}->0, checks
// word 0 now recombines to word {D-1}'s value and every other word is intact.
// Generated by gen_store256.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, we = 0, pg_go = 0;
reg [{AW-1}:0] waddr, raddr, pg_from, pg_to;
reg [{2*W-1}:0] wdata;
wire [{2*W-1}:0] rdata;

{NM} dut (.clk(clk), .rst(rst), .we(we), .waddr(waddr), .wdata(wdata),
          .raddr(raddr), .rdata(rdata),
          .pg_go(pg_go), .pg_from(pg_from), .pg_to(pg_to));

always #5 clk = ~clk;

reg [{W-1}:0] vals [0:{D-1}];
reg [{W-1}:0] mask, got, expd;
integer i, j, errors;

task sstore(input [{AW-1}:0] ad, input [{W-1}:0] v);
    begin
        for (j = 0; j < {NW}; j = j + 1) mask[j*32 +: 32] = $random;
        for (j = 0; j < {W}; j = j + 1) begin
            wdata[2*j] = v[j] ^ mask[j];  wdata[2*j+1] = mask[j];
        end
        @(negedge clk); we = 1'b1; waddr = ad;
        @(negedge clk); we = 1'b0;
    end
endtask

task sload_check(input [{AW-1}:0] ad, input [{W-1}:0] v);
    begin
        @(negedge clk); raddr = ad;
        @(negedge clk);  // registered read port
        @(negedge clk);
        for (j = 0; j < {W}; j = j + 1) got[j] = rdata[2*j] ^ rdata[2*j+1];
        if (got !== v) begin
            errors = errors + 1;
            $display("FAIL addr=%0d got=%h exp=%h", ad, got, v);
        end else $display("PASS addr=%0d %h", ad, got);
    end
endtask

initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    for (i = 0; i < {D}; i = i + 1) begin
        for (j = 0; j < {NW}; j = j + 1) vals[i][j*32 +: 32] = $random;
        sstore(i[{AW-1}:0], vals[i]);
    end
    for (i = 0; i < {D}; i = i + 1) sload_check(i[{AW-1}:0], vals[i]);
    // page {D-1} -> 0, then re-check everything
    @(negedge clk); pg_go = 1'b1; pg_from = {AW}'d{D-1}; pg_to = {AW}'d0;
    @(negedge clk); pg_go = 1'b0;
    repeat (4) @(negedge clk);
    sload_check({AW}'d0, vals[{D-1}]);
    for (i = 1; i < {D}; i = i + 1) sload_check(i[{AW-1}:0], vals[i]);
    // overwrite word 0 again and confirm
    for (j = 0; j < {NW}; j = j + 1) vals[0][j*32 +: 32] = $random;
    sstore({AW}'d0, vals[0]);
    sload_check({AW}'d0, vals[0]);
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
"""
with open(f"tb_smoke_{NM}.v", "w") as f:
    f.write(smoke)
print(f"wrote tb_smoke_{NM}.v")

print(f"W={W} D={D} AW={AW} tops: {NM}, {NM}_sharedbus, {NM}_recomb")
