#!/usr/bin/env python3
"""Emit the sponge1600 tops — the KECCAK256 sponge absorb at FULL WIDTH
(w=64, keccak-f[1600]), the same construction as the verified w=4 pilot
(gen_sponge100.py / RESULT_SPONGE100.md) applied to the VERIFIED keccakf1600
variant files. Real Keccak-256 geometry: rate = 1088 bits (17 lanes),
capacity = 512 bits, message = 512 bits = two 256-bit EVM words — the
keccak256(key ‖ slot) mapping-slot pattern — pad10*1 constants at flat bits
512 (lane 8 bit 0) and 1087 (lane 16 bit 63).

DUT = final-block absorb + one f[1600] permutation, ONE flat module built by
minimal assertion-guarded textual surgery (permutation body byte-identical up
to the a-to-ab_ bit rename; absorb = per-bit share-local wires, zero gadgets).

Emits: sponge1600.v (OPINI target), sponge1600_pini.v (label control,
expected transition-leakage FAIL), sponge1600_rndreuse.v (NEG, core r/s
reuse), sponge1600_recomb.v (NEG, planted in the NEW absorb stage on a CLEAN
core); tb_sponge1600.v; tb_smoke_sponge1600.v.
Generated by gen_sponge1600.py; do not hand-edit — regenerate instead.
"""
import random as _rnd
import re

W, NR, L = 64, 24, 6
B = 1600
RATE = 1088        # bits (17 lanes)
MSGB = 512         # message bits (8 lanes = two 256-bit EVM words)
PAD_BITS = (MSGB, RATE - 1)   # pad10*1: flat bits 512 and 1087
GADGET = "MSKand_opini2_d2"
NGAD = 1600

# ---------------- spec reference (same derivation as gen_keccakf.py) --------
def rho_offsets():
    r = [[0] * 5 for _ in range(5)]
    x, y = 1, 0
    for t in range(24):
        r[x][y] = ((t + 1) * (t + 2) // 2) % W
        x, y = y, (2 * x + 3 * y) % 5
    return r

def rc_bit(t):
    if t % 255 == 0:
        return 1
    R = 1
    for _ in range(t % 255):
        R <<= 1
        if R & 0x100:
            R ^= 0x171
        R &= 0xFF
    return R & 1

RHO = rho_offsets()
RC = []
for ir in range(NR):
    v = 0
    for j in range(L + 1):
        v |= rc_bit(j + 7 * ir) << (2 ** j - 1)
    RC.append(v & ((1 << W) - 1))
assert RC[0] == 0x1 and RC[1] == 0x8082 and RC[23] == 0x8000000080008008

def keccakf_ref(lanes):
    lanes = list(lanes)
    M = (1 << W) - 1
    def rotl(v, n):
        n %= W
        return ((v << n) | (v >> (W - n))) & M if n else v
    for ir in range(NR):
        C = [lanes[x] ^ lanes[x + 5] ^ lanes[x + 10] ^ lanes[x + 15] ^ lanes[x + 20]
             for x in range(5)]
        D = [C[(x - 1) % 5] ^ rotl(C[(x + 1) % 5], 1) for x in range(5)]
        A = [lanes[5 * y + x] ^ D[x] for y in range(5) for x in range(5)]
        Bl = [0] * 25
        for x in range(5):
            for y in range(5):
                Bl[5 * ((2 * x + 3 * y) % 5) + y] = rotl(A[5 * y + x], RHO[x][y])
        lanes = [Bl[5 * y + x] ^ ((~Bl[5 * y + (x + 1) % 5]) & Bl[5 * y + (x + 2) % 5]) & M
                 for y in range(5) for x in range(5)]
        lanes[0] ^= RC[ir]
    return lanes

def flat(lanes):
    v = 0
    for i in range(25):
        v |= lanes[i] << (i * W)
    return v

def unflat(v):
    return [(v >> (i * W)) & ((1 << W) - 1) for i in range(25)]

# anchor 1: XKCP zero-state test vector (ties the permutation reference)
z = keccakf_ref([0] * 25)
assert z[0] == 0xF1258F7940E1DDE7 and z[1] == 0x84D5CCF933C0478A
print("anchor OK: XKCP zero-state vector")

PAD = 0
for pb in PAD_BITS:
    PAD |= 1 << pb

def sponge_ref(st, m):
    """absorbed = st XOR zext(m) XOR PAD; return f[1600](absorbed)."""
    return flat(keccakf_ref(unflat(st ^ m ^ PAD)))

# anchor 2: the DUT absorbs a FIXED 64-byte message, so sponge_ref(0,0) is
# keccak256(64 zero bytes) — the canonical Solidity mapping-slot hash for
# key=0, slot=0 (widely published constant). Anchors the byte/lane/pad
# mapping, not just the permutation.
out0 = unflat(sponge_ref(0, 0))
digest0 = b"".join(out0[i].to_bytes(8, "little") for i in range(4))
assert digest0.hex() == ("ad3228b676f7d3cd4284a5443f17f196"
                         "2b36e491b30a40b2405849e597ba5fb5"), digest0.hex()
print(f"anchor OK: keccak256(64 zero bytes) = {digest0.hex()}")

# ---------------- textual surgery on the verified core files ----------------
def subst_once(text, old, new, fn):
    assert text.count(old) == 1, f"{fn}: pattern not unique ({text.count(old)}x): {old!r}"
    return text.replace(old, new)

def absorb_block(recomb=False):
    L = ["""
// ---- SPONGE ABSORB (final-block, real Keccak-256 geometry): rate = 1088
// bits (lanes 0..16), capacity = 512 bits (lanes 17..24), message = 512 bits
// (lanes 0..7 — keccak256(key||slot), two 256-bit EVM words), pad10*1 public
// constants at flat bits 512 (lane 8 bit 0) and 1087 (lane 16 bit 63).
// STRICTLY SHARE-LOCAL, ZERO gadgets: share 0 = st0 ^ m0 ^ pad_const,
// share 1 = st1 ^ m1; two shares of one secret never meet. Per-bit wires
// ab_<k> (a packed vector leaves a partially-aliased netname dangling in the
// synth JSON, which MATCHI rejects — see RESULT_SPONGE100.md flow note).
// The verified permutation body below is byte-identical to keccakf1600 up
// to the a-to-ab_ bit rename."""]
    for j in range(B):
        pad = " ^ 1'b1" if j in PAD_BITS else ""
        if j < MSGB:
            L.append(f"wire ab_{2*j} = st[{2*j}] ^ m[{2*j}]{pad};  "
                     f"wire ab_{2*j+1} = st[{2*j+1}] ^ m[{2*j+1}];")
        else:
            L.append(f"wire ab_{2*j} = st[{2*j}]{pad};  "
                     f"wire ab_{2*j+1} = st[{2*j+1}];")
    if recomb:
        L.append("""
// BUG UNDER TEST (planted in the NEW absorb stage, core is CLEAN): register
// recombining the two shares of absorbed state bit 0. Its input XOR gate is
// sensitive in ShareSet{0} AND ShareSet{1} -> MATCHI glitch leakage.
(* keep = "yes" *) reg leak0, leak1;
always @(posedge clk) begin
    leak0 <= ab_0 ^ ab_1;
    leak1 <= 1'b0;
end
assign leak_o = {leak1, leak0};""")
    return "\n".join(L)

def build(core_file, core_mod, sponge_mod, comment, recomb=False):
    text = open(core_file).read()
    ep = ", leak_o" if recomb else ""
    lk = ('\n(* matchi_type = "sharing", matchi_active = "out_act" *) '
          "output [1:0] leak_o;") if recomb else ""
    text = subst_once(
        text,
        f"module {core_mod} (clk, rst, go, a, r, s, o);",
        f"module {sponge_mod} (clk, rst, go, st, m, r, s, o{ep});",
        core_file)
    text = subst_once(
        text,
        '(* matchi_type = "sharings_dense", matchi_active = "a_act" *) '
        f"input [{2*B-1}:0] a;",
        '(* matchi_type = "sharings_dense", matchi_active = "a_act" *) '
        f"input [{2*B-1}:0] st;\n"
        '(* matchi_type = "sharings_dense", matchi_active = "a_act" *) '
        f"input [{2*MSGB-1}:0] m;",
        core_file)
    o_decl = ('(* matchi_type = "sharings_dense", matchi_active = "out_act" *)'
              f" output [{2*B-1}:0] o;")
    text = subst_once(text, o_decl, o_decl + lk + "\n" + absorb_block(recomb),
                      core_file)
    # rename the former input refs (the two St0/St1 load lines) to ab_<k>
    text, nsub = re.subn(r"\ba\[(\d+)\]", r"ab_\1", text)
    assert nsub == 2 * B, f"{core_file}: substituted {nsub} a-refs, expected {2*B}"
    assert not re.search(r"\ba\[", text)
    return comment + "\n" + text

C_MAIN = ("// sponge1600 — KECCAK256 sponge absorb at FULL WIDTH (w=64):\n"
          "// share-local final-block absorb (zero gadgets) + the VERIFIED\n"
          "// keccakf1600 permutation body byte-identical below. VERIFIED TARGET.")
C_PINI = ("// LABEL CONTROL (EXPECTED transition-leakage FAIL): sponge absorb on\n"
          "// the keccakf1600_pini core (PINI-relabelled leaf, bubble-free round\n"
          "// reuse — cf. keccakf1600_pini). Verdict recorded either way.")
C_RND = ("// NEGATIVE CONTROL (must FAIL): sponge absorb on the\n"
         "// keccakf1600_rndreuse core (u_chi_1 reuses u_chi_0's r/s).")
C_RCB = ("// NEGATIVE CONTROL (must FAIL): CLEAN keccakf1600 core; the bug is\n"
         "// planted in the NEW absorb stage (leak0 <= ab_0^ab_1) — proves\n"
         "// MATCHI checks the sponge wiring itself, not just the core.")

def emit(fn, text, leaf):
    n = text.count(leaf + " u_")
    assert n == NGAD, f"{fn}: leaf {leaf} x{n}, expected {NGAD}"
    with open(fn, "w") as f:
        f.write(text)
    print(f"wrote {fn}: {n} {leaf} instances")

emit("sponge1600.v",
     build("keccakf1600.v", "keccakf1600", "sponge1600", C_MAIN), GADGET)
emit("sponge1600_pini.v",
     build("keccakf1600_pini.v", "keccakf1600_pini", "sponge1600_pini", C_PINI),
     GADGET + "_pini")
emit("sponge1600_rndreuse.v",
     build("keccakf1600_rndreuse.v", "keccakf1600_rndreuse",
           "sponge1600_rndreuse", C_RND), GADGET)
emit("sponge1600_recomb.v",
     build("keccakf1600.v", "keccakf1600", "sponge1600_recomb", C_RCB,
           recomb=True), GADGET)

# ---------------- MATCHI testbench (mirror tb_keccakf1600.v) ----------------
tb = f"""// MATCHI testbench for the sponge1600 tops. Same convention as
// tb_keccakf1600.v: values are irrelevant to MATCHI (symbolic); only
// signal-activity timing is read from the VCD. Run length covers the deepest
// window plus margin — the absorb stage is combinational and adds zero
// cycles, so all keccakf1600 window constants carry over unchanged.
// Generated by gen_sponge1600.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD sponge1600
`endif
module tb ();
parameter HP = 5;
reg [{2*B-1}:0] st;
reg [{2*MSGB-1}:0] m;
reg clk, rst, go;
reg [{B-1}:0] r, s;
wire [{2*B-1}:0] o;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .go(go), .st(st), .m(m),
             .r(r), .s(s), .o(o)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < {2*B//32}; w = w + 1) st[w*32 +: 32] = $random;
        for (w = 0; w < {2*MSGB//32}; w = w + 1) m[w*32 +: 32] = $random;
        for (w = 0; w < {B//32}; w = w + 1) begin
            r[w*32 +: 32] = $random;
            s[w*32 +: 32] = $random;
        end
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; go = 1'b0;
    st = 0; m = 0; r = 0; s = 0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // cycle 0: one-cycle go pulse
    @(negedge clk); go = 1'b1; randfill;
    @(negedge clk); go = 1'b0; randfill;
    for (i = 0; i < 196; i = i + 1) begin
        @(negedge clk); randfill;
    end
    $finish;
end
endmodule
"""
with open("tb_sponge1600.v", "w") as f:
    f.write(tb)
print("wrote tb_sponge1600.v")

# ---------------- functional smoke testbench ----------------
_rnd.seed(0x5B0A61600)
key_w = 0x000000000000000000000000DEADBEEF00C0FFEE00BA5E00CAFE0000FEED0001
slot_w = 3
def evm_msg(key, slot):
    """key||slot as the sponge sees it: 64 bytes big-endian words, absorbed
    little-endian into lanes 0..7 (the gen_keccak256_smoke.py byte mapping)."""
    blob = key.to_bytes(32, "big") + slot.to_bytes(32, "big")
    v = 0
    for i in range(8):
        v |= int.from_bytes(blob[8 * i:8 * i + 8], "little") << (i * W)
    return v

vecs = [
    (0, 0, 'st=0 m=0: keccak256(64 zero bytes), the key=0/slot=0 mapping hash'),
    (0, evm_msg(key_w, slot_w),
     "st=0, m = keccak256(key||slot=3) mapping-slot message"),
    (_rnd.getrandbits(B), _rnd.getrandbits(MSGB),
     "chained block: random incoming state + random message"),
    (_rnd.getrandbits(B), _rnd.getrandbits(MSGB),
     "chained block: second random vector"),
]
checks = []
for stv, mv, note in vecs:
    exp = sponge_ref(stv, mv)
    dig = b"".join(unflat(exp)[i].to_bytes(8, "little") for i in range(4))
    print(f"vector: {note}\n  digest = {dig.hex()}")
    checks.append(f"    // {note}\n"
                  f"    // digest(lanes 0..3 LE) = {dig.hex()}\n"
                  f"    check({B}'h{stv:0{B//4}x},\n"
                  f"          {MSGB}'h{mv:0{MSGB//4}x},\n"
                  f"          {B}'h{exp:0{B//4}x});")
checks = "\n".join(checks)

smoke = f"""// Functional smoke test for sponge1600 (NOT a security check — MATCHI is
// the separate verification step). Incoming state AND message enter as real
// 2-share sharings (independent random masks); pad constants live in share 0
// only (inside the DUT); recombined 1600-bit output compared against
// absorb+permute from the spec reference in gen_sponge1600.py, anchored on
// the XKCP zero-state vector AND the canonical keccak256("") digest.
// Fresh gadget randoms every cycle.
// Generated by gen_sponge1600.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg [{2*B-1}:0] st;
reg [{2*MSGB-1}:0] m;
reg clk = 0, rst = 1, go = 0;
reg [{B-1}:0] rr, ss;
wire [{2*B-1}:0] o;

sponge1600 dut (.clk(clk), .rst(rst), .go(go), .st(st), .m(m),
          .r(rr), .s(ss), .o(o));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < {B//32}; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [{B-1}:0] am, got;
reg [{MSGB-1}:0] bm;
integer j;
task check(input [{B-1}:0] x, input [{MSGB-1}:0] mx, input [{B-1}:0] expd);
    begin
        for (j = 0; j < {B//32}; j = j + 1) am[j*32 +: 32] = $random;
        for (j = 0; j < {MSGB//32}; j = j + 1) bm[j*32 +: 32] = $random;
        for (j = 0; j < {B}; j = j + 1) begin
            st[2*j] = x[j] ^ am[j];  st[2*j+1] = am[j];
        end
        for (j = 0; j < {MSGB}; j = j + 1) begin
            m[2*j] = mx[j] ^ bm[j];  m[2*j+1] = bm[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat (151) @(negedge clk);
        for (j = 0; j < {B}; j = j + 1) got[j] = o[2*j] ^ o[2*j+1];
        if (got !== expd) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  got=%h", got);
            $display("  exp=%h", expd);
        end else begin
            $display("PASS digest(flat lanes 0..3)=%h", got[255:0]);
        end
        repeat (30) @(negedge clk);   // past clr before the next check
    end
endtask

initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
{checks}
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
"""
with open("tb_smoke_sponge1600.v", "w") as f:
    f.write(smoke)
print("wrote tb_smoke_sponge1600.v")
