#!/usr/bin/env python3
"""Emit the 256-bit masked MUL tops (EVM MUL: prod = (A*B) mod 2^256) — an
ITERATIVE CARRY-SAVE multiplier over the MATCHI-passed O-PINI2 gadget
(MSKand_opini2_d2, byte-identical leaf from ./, read-only
reference), plus a final ripple add that is a verbatim structural copy of the
verified 256-bit adder datapath (top_add256_opini2).

Why iterative carry-save (design record):
  * A fully unrolled schoolbook mod-2^256 multiplier needs ~N^2 PP-gating
    gadgets + ~2*N^2 accumulation gadgets (~196k O-PINI2 leaves) — far past
    MATCHI/yosys tractability on this box.
  * Using the verified ripple adder once per partial product is small but
    needs ~N * (2N+3) ~ 132k cycles.
  * Carry-save keeps BOTH small: 5N = 1280 gadget instances, ~10N+O(1) ~2600
    cycles. Netlist ~2.5x the verified adder, cycle count ~2.5x its tb.
  * The datapath REUSES every gadget bubble-free across all 256 iterations
    with continuously-sensitive inputs and genuine FEEDBACK (C depends on the
    same gadget's previous output) — exactly the structure the OPINI-vs-PINI
    chain controls (./top_chain_*) exercise. The verified
    top_chain_opini2 shows MATCHI accepts bubble-free feedback reuse for
    OPINI leaves.

Algorithm (per iteration i = 0..N-1, invariant S + C == sum_{k<i} PP_k mod 2^N):
  PP   = (A << i) AND broadcast(B[i])          (mod 2^N)   -> N gadgets
  newS = S ^ C ^ PP                            (share-local XOR, free)
  newC = ( (S&C) ^ (PP&(S^C)) ) << 1           (MAJ = full-adder carry;
                                                2 gadgets/bit -> 2N gadgets)
  A <<= 1 ; B >>= 1                            (share-local shifts, public 0 in)
After N iterations: prod = S + C mod 2^N via the verified ripple-adder
dataflow (2 gadgets/bit -> 2N gadgets; sub=0; carry-out dropped = mod 2^N).
Total gadgets 5N. Every XOR/NOT/shift is STRICTLY share-local (no gate ever
mixes share 0 and share 1 of any masked value). Gadget is INSTANTIATED, never
inlined.

Gadget latency contract (inb@0, rnd@0, ina@1, s@1, out@3) inside the FSM:
every gadget's ina path goes through a 1-cycle per-share balance register
(the iszero256 solution): ina arrives exactly one cycle after inb.
Iteration period K=8 (state registers held stable all 8 cycles => every
execution in the window sees a consistent inb@e/ina@e+1 pair):
  ph0 (start): aa/bb/S/C stable; PP gadget exec e=start -> out during start+3
  edge end of ph3: pp <= PP-gadget out                  -> pp valid start+4
  MAJ gadgets exec e=start+4 (inb = S / pp; ina = c_d/x_d, 1-cycle-delayed
    copies of C / S^C)                                  -> out during start+7
  edge end of ph7: S,C,aa,bb update -> next iteration.
Final add: adder consumes a := S_d (1-cycle delayed S) and b := C — the same
1-cycle a-late/b-early arrival stagger the verified adder realises with its
a[1,..]/b[0,..] port windows. Ripple settles ~2N+4 cycles after S,C freeze.

State-register sensitivity is BOUNDED IN TIME: unlike the feed-forward
adder/iszero tops, S/C/aa/pp registers would hold shares forever, so a
control-derived clr pulse (act[CLR_AT]) zeroes them after the output window;
the unconditional 1-cycle delay registers drain by themselves one cycle
later. r/s stay fresh through CLR_AT+8 so every sensitive execution (incl.
the clearing tail) has fresh randomness.

Emits (suffix = N): mul{N}.v (OPINI target), mul{N}_pini.v (label control:
with bubble-free reuse+feedback this control is EXPECTED to exercise the
OPINI-vs-PINI transition rule), mul{N}_rndreuse.v (NEG control, must FAIL:
u_pp_1 reuses u_pp_0's r[0]/s[0]), mul{N}_recomb.v (NEG control, must FAIL:
register recombining prod[0]^prod[1]); tb_mul{N}.v (MATCHI tb);
tb_smoke_mul{N}.v (functional).
Generated by gen_mul256.py; do not hand-edit — regenerate instead.
Usage: gen_mul256.py [N]   (default 256)
"""
import sys

N = int(sys.argv[1]) if len(sys.argv) > 1 else 256
GADGET = "MSKand_opini2_d2"
# Gadget budget: N PP-gating + 2(N-1) carry-save MAJ + 2(N-1) final-add.
# The top-bit MAJ and final-add carry-out gadgets are NOT instantiated: their
# only product is the carry dropped by mod-2^N, and yosys would clean the
# dangling XOR leaving a driverless wire that MATCHI rejects.
NG = 5 * N - 4                  # total gadget instances
ITW = max(2, (N - 1).bit_length() + 1)   # iteration counter width

# ---- schedule constants (cycle 0 = go; registers load at edge into cycle 1) ----
K = 8
OUT_STABLE = 10 * N + 8         # prod stable from here (analysis in header)
CLR_AT = 10 * N + 25            # state registers cleared at this act tap
OUT_HI = CLR_AT + 2 * N + 20    # out_act covers the post-clr drain: regs zero
                                # @CLR+1, delay regs @CLR+2, then NON-sensitivity
                                # ripples down the final-add carry chain at
                                # ~2 cycles/bit (like the value ripple) -> ~2N tail
R_HI = OUT_HI + 2               # randoms fresh through the whole drain
S_HI = R_HI + 1                 # s latency 1
ACTR_HI = S_HI
TB_CYC = S_HI + 30              # MATCHI tb run length after go
SMOKE_SAMPLE = CLR_AT - 5       # smoke: sample prod here (stable, before clr)
SMOKE_GAP = 60                  # smoke: extra cycles after sample


def share_concat(port, share, n=N):
    """Dense sharing unpack: {port[2*(n-1)+share], ..., port[share]}."""
    return "{" + ", ".join(f"{port}[{2*j+share}]" for j in range(n - 1, -1, -1)) + "}"


def header(modname, leaf, comment, recomb=False):
    ep = ", leak_o" if recomb else ""
    lk = ('\n(* matchi_type = "sharing", matchi_active = "out_act" *) '
          "output [1:0] leak_o;") if recomb else ""
    return f"""{comment}
// Iterative carry-save masked multiplier, prod = (A*B) mod 2^{N}. {NG} assumed-
// OPINI gadget leaves ({N} PP-gating u_pp_*, {2*(N-1)} carry-save MAJ u_sc_*/u_px_*,
// {2*(N-1)} final-add u_g_*/u_t_* — the verified-adder dataflow; the top-bit
// carry gadgets are omitted, their carries are dropped by mod 2^{N}), each with
// a DEDICATED r[k]/s[k] random bit. Every XOR/shift is strictly share-local.
// Dense sharing layout (share index fastest): port[2i]=share0, port[2i+1]=share1.
// Schedule: load @0; iteration i occupies cycles [1+{K}i, {K}+{K}i]; S,C final
// from cycle {K}*{N}+1; ripple output stable ~cycle {OUT_STABLE}; state cleared
// (share-local, to public 0) at cycle {CLR_AT}; randoms fresh [0,{R_HI}].
(* matchi_prop = "PINI", matchi_strat = "composite_top", matchi_arch = "loopy", matchi_shares = 2 *)
module {modname} (clk, rst, go, a, b, r, s, prod{ep});
(* matchi_type = "clock" *)   input clk;
(* matchi_type = "control" *) input rst;
(* matchi_type = "control" *) input go;
(* matchi_type = "sharings_dense", matchi_active = "a_act" *) input [{2*N-1}:0] a;
(* matchi_type = "sharings_dense", matchi_active = "b_act" *) input [{2*N-1}:0] b;
(* matchi_type = "random", matchi_active = "r_act" *) input [{NG-1}:0] r;
(* matchi_type = "random", matchi_active = "s_act" *) input [{NG-1}:0] s;
(* matchi_type = "sharings_dense", matchi_active = "out_act" *) output [{2*N-1}:0] prod;{lk}

// ---- activity shift register (single go pulse; windows are its taps) ----
(* keep *) wire act0 = go;
(* keep *) reg [{ACTR_HI}:1] actr;
always @(posedge clk) begin
    if (rst) actr <= {ACTR_HI}'b0;
    else     actr <= {{actr[{ACTR_HI-1}:1], act0}};
end
wire [{ACTR_HI}:0] act = {{actr, act0}};
(* keep *) wire a_act   = |act[1:0];      // operands consumed only at the load edge
(* keep *) wire b_act   = |act[1:0];
(* keep *) wire r_act   = |act[{R_HI}:0];
(* keep *) wire s_act   = |act[{S_HI}:1];
(* keep *) wire out_act = |act[{OUT_HI}:0];
(* keep *) wire clr     = act[{CLR_AT}];  // bounded sensitivity: zero the state regs

// ---- public FSM: iteration counter + phase (control only, data-independent) ----
reg running;
reg [{ITW-1}:0] it;
reg [2:0] ph;
always @(posedge clk) begin
    if (rst) begin running <= 1'b0; it <= 0; ph <= 3'd0; end
    else if (go) begin running <= 1'b1; it <= 0; ph <= 3'd0; end
    else if (running) begin
        if (ph == 3'd7) begin
            ph <= 3'd0;
            if (it == {ITW}'d{N-1}) begin running <= 1'b0; it <= 0; end
            else it <= it + {ITW}'d1;
        end else ph <= ph + 3'd1;
    end
end

// ---- state registers (per-share; NEVER mix share 0 and share 1) ----
reg [{N-1}:0] aa0, aa1;          // multiplicand A, shifts left (public 0 in)
reg [{N-1}:0] bb0, bb1;          // multiplier B, shifts right (public 0 in)
reg [{N-1}:0] S0, S1, C0, C1;    // carry-save accumulator
reg [{N-1}:0] pp0, pp1;          // registered PP-gadget outputs
wire [{N-1}:0] w_pp0, w_pp1;
wire [{N-2}:0] w_sc0, w_sc1, w_px0, w_px1;   // top bit not computed (mod 2^{N})
wire [{N-2}:0] maj0 = w_sc0 ^ w_px0;   // share-local XOR of two gadget outputs
wire [{N-2}:0] maj1 = w_sc1 ^ w_px1;   // (same pattern as the adder's g^t)

always @(posedge clk) begin
    if (rst || clr) begin
        aa0 <= 0; aa1 <= 0; bb0 <= 0; bb1 <= 0;
        S0 <= 0; S1 <= 0; C0 <= 0; C1 <= 0; pp0 <= 0; pp1 <= 0;
    end else if (go) begin        // dense-share unpack, share-local
        aa0 <= {share_concat('a', 0)};
        aa1 <= {share_concat('a', 1)};
        bb0 <= {share_concat('b', 0)};
        bb1 <= {share_concat('b', 1)};
        S0 <= 0; S1 <= 0; C0 <= 0; C1 <= 0; pp0 <= 0; pp1 <= 0;
    end else if (running) begin
        if (ph == 3'd3) begin pp0 <= w_pp0; pp1 <= w_pp1; end
        if (ph == 3'd7) begin
            S0 <= S0 ^ C0 ^ pp0;                    // share-local
            S1 <= S1 ^ C1 ^ pp1;
            C0 <= {{maj0, 1'b0}};                   // <<1 = mod 2^{N} accumulate
            C1 <= {{maj1, 1'b0}};
            aa0 <= {{aa0[{N-2}:0], 1'b0}};          // A <<= 1 (per-share)
            aa1 <= {{aa1[{N-2}:0], 1'b0}};
            bb0 <= {{1'b0, bb0[{N-1}:1]}};          // B >>= 1 (per-share)
            bb1 <= {{1'b0, bb1[{N-1}:1]}};
        end
    end
end

// ---- 1-cycle per-share balance registers: every gadget ina arrives one
// cycle after its inb (gadget contract ina@1/inb@0 — the iszero256 pattern).
// Unconditional, so they drain by themselves one cycle after clr.
reg [{N-1}:0] aa_d0, aa_d1;      // ina of u_pp_*  (inb = bbit)
reg [{N-1}:0] c_d0, c_d1;        // ina of u_sc_*  (inb = S)
reg [{N-1}:0] x_d0, x_d1;        // ina of u_px_*  (inb = pp); x = S^C share-local
reg [{N-1}:0] S_d0, S_d1;        // final adder operand a := delayed S (b := C)
always @(posedge clk) begin
    aa_d0 <= aa0;       aa_d1 <= aa1;
    c_d0  <= C0;        c_d1  <= C1;
    x_d0  <= S0 ^ C0;   x_d1  <= S1 ^ C1;
    S_d0  <= S0;        S_d1  <= S1;
end
"""


def pp_maj_body(leaf, rndreuse=False):
    L = []
    o = L.append
    o(f"\n// ===== PP gating: PP[j] = aa[j] AND bbit  (bbit = current B bit, both shares fan out) =====")
    for j in range(N):
        if rndreuse and j == 1:
            rk, sk = "r[0]", "s[0]"
            note = "  // BUG UNDER TEST: reuses u_pp_0's randomness r[0]/s[0]"
        else:
            rk, sk = f"r[{j}]", f"s[{j}]"
            note = ""
        o(f"""{leaf} u_pp_{j} ({note}
    .ina({{aa_d1[{j}], aa_d0[{j}]}}), .inb({{bb1[0], bb0[0]}}),
    .rnd({rk}), .s({sk}), .clk(clk), .out({{w_pp1[{j}], w_pp0[{j}]}}));""")
    o(f"\n// ===== carry-save MAJ: newC[j+1] = (S&C)[j] ^ (PP&(S^C))[j] =====")
    o(f"// (bit {N-1} omitted: its carry is dropped by the <<1 mod-2^{N} accumulate)")
    for j in range(N - 1):
        o(f"""{leaf} u_sc_{j} (
    .ina({{c_d1[{j}], c_d0[{j}]}}), .inb({{S1[{j}], S0[{j}]}}),
    .rnd(r[{N+2*j}]), .s(s[{N+2*j}]), .clk(clk), .out({{w_sc1[{j}], w_sc0[{j}]}}));
{leaf} u_px_{j} (
    .ina({{x_d1[{j}], x_d0[{j}]}}), .inb({{pp1[{j}], pp0[{j}]}}),
    .rnd(r[{N+2*j+1}]), .s(s[{N+2*j+1}]), .clk(clk), .out({{w_px1[{j}], w_px0[{j}]}}));""")
    return "\n".join(L)


def adder_body(leaf):
    """Final ripple add prod = S_d + C mod 2^N — verbatim verified-adder
    dataflow (top_add256_opini2 bit slice with a:=S_d, b:=C, sub=0)."""
    L = []
    o = L.append
    base = 3 * N - 2   # dense randomness indexing after the N-1 MAJ pairs
    o(f"""
// ===== final ripple add: prod = S + C mod 2^{N} (verified-adder dataflow, sub=0) =====
// (bit {N-1} needs no g/t gadgets: its carry-out is dropped by mod 2^{N}.
//  fc[1..{N-2}] feed gadget ports so they survive synthesis; the carry INTO the
//  top bit is kept as standalone scalars fct0/fct1 — abc may absorb them into
//  the prod XOR without leaving a driverless vector bit behind.)
wire [{N-2}:0] fc0, fc1;
assign fc0[0] = 1'b0;
assign fc1[0] = 1'b0;""")
    for j in range(N - 1):
        cw0, cw1 = (f"fc0[{j+1}]", f"fc1[{j+1}]") if j < N - 2 else ("fct0", "fct1")
        cd = "assign" if j < N - 2 else "wire"
        o(f"""wire p0_{j} = S_d0[{j}] ^ C0[{j}];
wire p1_{j} = S_d1[{j}] ^ C1[{j}];
wire g0_{j}, g1_{j}, t0_{j}, t1_{j};
{leaf} u_g_{j} (
    .ina({{S_d1[{j}], S_d0[{j}]}}), .inb({{C1[{j}], C0[{j}]}}),
    .rnd(r[{base+2*j}]), .s(s[{base+2*j}]), .clk(clk), .out({{g1_{j}, g0_{j}}}));
{leaf} u_t_{j} (
    .ina({{fc1[{j}], fc0[{j}]}}), .inb({{p1_{j}, p0_{j}}}),
    .rnd(r[{base+2*j+1}]), .s(s[{base+2*j+1}]), .clk(clk), .out({{t1_{j}, t0_{j}}}));
{cd} {cw0} = g0_{j} ^ t0_{j};
{cd} {cw1} = g1_{j} ^ t1_{j};
assign prod[{2*j}]   = p0_{j} ^ fc0[{j}];
assign prod[{2*j+1}] = p1_{j} ^ fc1[{j}];""")
    j = N - 1
    o(f"""// top bit: sum only, carry-out dropped (mod 2^{N}, EVM MUL)
wire p0_{j} = S_d0[{j}] ^ C0[{j}];
wire p1_{j} = S_d1[{j}] ^ C1[{j}];
assign prod[{2*j}]   = p0_{j} ^ fct0;
assign prod[{2*j+1}] = p1_{j} ^ fct1;""")
    return "\n".join(L)


def build(modname, leaf, comment, rndreuse=False, recomb=False):
    parts = [header(modname, leaf, comment, recomb=recomb),
             pp_maj_body(leaf, rndreuse=rndreuse),
             adder_body(leaf)]
    if recomb:
        parts.append("""
// BUG UNDER TEST: recombine the two shares of prod bit 0. leak0 holds
// prod[0]^prod[1] (both shares) -> the XOR gate is sensitive in ShareSet{0}
// AND ShareSet{1} -> MATCHI glitch leakage. Driven onto share 0 of leak_o.
(* keep = "yes" *) reg leak0, leak1;
always @(posedge clk) begin
    leak0 <= prod[0] ^ prod[1];
    leak1 <= 1'b0;
end
assign leak_o = {leak1, leak0};""")
    parts.append("\nendmodule\n")
    return "\n".join(parts)


def emit(fn, text, leaf, expect_count):
    n = text.count(leaf + " u_")
    assert n == expect_count, f"{fn}: leaf {leaf} x{n}, expected {expect_count}"
    with open(fn, "w") as f:
        f.write(text)
    print(f"wrote {fn}: {n} {leaf} instances")


C_MAIN = (f"// {N}-bit masked MUL (EVM: prod = A*B mod 2^{N}) — iterative carry-save\n"
          f"// multiplier over {NG} O-PINI2 masked-AND leaves. VERIFIED TARGET.\n"
          "// Bubble-free gadget reuse across all iterations with genuine feedback\n"
          "// (C depends on the same gadgets' previous outputs) — the OPINI regime.")
C_PINI = ("// LABEL CONTROL: identical netlist but instantiates the PINI-relabelled\n"
          "// leaf MSKand_opini2_d2_pini. Unlike the single-pass adder/iszero label\n"
          "// controls, this datapath REUSES gadgets bubble-free with feedback, the\n"
          "// structure MATCHI's transition rule guards for PINI leaves (cf.\n"
          "// ./top_chain_pini). Verdict recorded either way.")
C_RND = ("// NEGATIVE CONTROL (must FAIL): identical to the target except u_pp_1\n"
         "// consumes r[0]/s[0] — the SAME random bits as u_pp_0, active in the same\n"
         "// cycles — instead of its dedicated r[1]/s[1]. MATCHI must report multi-use.")
C_RCB = ("// NEGATIVE CONTROL (must FAIL): identical to the target plus one share-\n"
         "// recombining register (leak0 <= prod[0]^prod[1]). MATCHI must flag the\n"
         "// gate sensitive in multiple shares (glitch leakage).")

emit(f"mul{N}.v", build(f"mul{N}", GADGET, C_MAIN), GADGET, NG)
emit(f"mul{N}_pini.v", build(f"mul{N}_pini", GADGET + "_pini", C_PINI),
     GADGET + "_pini", NG)
emit(f"mul{N}_rndreuse.v", build(f"mul{N}_rndreuse", GADGET, C_RND, rndreuse=True),
     GADGET, NG)
emit(f"mul{N}_recomb.v", build(f"mul{N}_recomb", GADGET, C_RCB, recomb=True),
     GADGET, NG)

# ---------------- MATCHI testbench ----------------
AB_W = 2 * N                    # a/b port width
RS_W = NG                       # r/s port width
AB_WW = (AB_W + 31) // 32       # $random words
RS_WW = (RS_W + 31) // 32
tb = f"""// MATCHI testbench for the mul{N} tops. Same convention as the verified
// adder/iszero tbs: values are irrelevant to MATCHI (symbolic); only signal-
// activity timing is read from the VCD. Inputs re-randomized every cycle so
// the annotated activity windows match physics. Run length covers the deepest
// window (r [0,{R_HI}]) plus margin.
// Generated by gen_mul256.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD mul{N}
`endif
module tb ();
parameter HP = 5;
reg clk, rst, go;
reg [{AB_WW*32-1}:0] a, b;
reg [{RS_WW*32-1}:0] r, s;
wire [{AB_W-1}:0] prod;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .go(go),
             .a(a[{AB_W-1}:0]), .b(b[{AB_W-1}:0]),
             .r(r[{RS_W-1}:0]), .s(s[{RS_W-1}:0]), .prod(prod)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < {AB_WW}; w = w + 1) begin
            a[w*32 +: 32] = $random;
            b[w*32 +: 32] = $random;
        end
        for (w = 0; w < {RS_WW}; w = w + 1) begin
            r[w*32 +: 32] = $random;
            s[w*32 +: 32] = $random;
        end
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; go = 1'b0;
    a = 0; b = 0; r = 0; s = 0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // cycle 0: one-cycle go pulse
    @(negedge clk); go = 1'b1; randfill;
    @(negedge clk); go = 1'b0; randfill;
    for (i = 0; i < {TB_CYC}; i = i + 1) begin
        @(negedge clk); randfill;
    end
    $finish;
end
endmodule
"""
with open(f"tb_mul{N}.v", "w") as f:
    f.write(tb)
print(f"wrote tb_mul{N}.v")

# ---------------- functional smoke testbench ----------------
NW = (N + 31) // 32
smoke = f"""// Functional smoke test for mul{N} (NOT a security check — MATCHI is the
// separate verification step). Shares each operand with a random mask, pulses
// go, waits out the {N} carry-save iterations + final ripple, recombines the
// product shares, compares against (x*y) mod 2^{N}. Fresh gadget randoms every
// cycle (the recombined output is mask-independent).
// Generated by gen_mul256.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [{2*N-1}:0] a, b;
reg [{RS_WW*32-1}:0] rr, ss;
wire [{2*N-1}:0] prod;

mul{N} dut (.clk(clk), .rst(rst), .go(go), .a(a), .b(b),
            .r(rr[{RS_W-1}:0]), .s(ss[{RS_W-1}:0]), .prod(prod));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < {RS_WW}; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [{N-1}:0] am, bm, got, expd;
integer j;
task check(input [{N-1}:0] x, input [{N-1}:0] y);
    begin
        for (j = 0; j < {NW}; j = j + 1) begin
            am[j*32 +: 32] = $random;
            bm[j*32 +: 32] = $random;
        end
        for (j = 0; j < {N}; j = j + 1) begin
            a[2*j] = x[j] ^ am[j];  a[2*j+1] = am[j];
            b[2*j] = y[j] ^ bm[j];  b[2*j+1] = bm[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat ({SMOKE_SAMPLE}) @(negedge clk);
        for (j = 0; j < {N}; j = j + 1) got[j] = prod[2*j] ^ prod[2*j+1];
        expd = x * y;               // Verilog truncates to {N} bits = mod 2^{N}
        if (got !== expd) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  x  =%h", x);
            $display("  y  =%h", y);
            $display("  got=%h", got);
            $display("  exp=%h", expd);
        end else begin
            $display("PASS x*y mod 2^{N}: %h", got);
        end
        repeat ({SMOKE_GAP}) @(negedge clk);   // past clr before the next check
    end
endtask

reg [{N-1}:0] xv, yv;
initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    check({{{N}{{1'b0}}}}, {{{N}{{1'b0}}}});                    // 0 * 0
    check({{{{{N-1}{{1'b0}}}}, 1'b1}}, {{{{{N-1}{{1'b0}}}}, 1'b1}}); // 1 * 1
    for (j = 0; j < {NW}; j = j + 1) xv[j*32 +: 32] = $random;
    check(xv, {{{{{N-1}{{1'b0}}}}, 1'b1}});                     // x * 1 = x
    check({{1'b1, {{{N-1}{{1'b0}}}}}}, {{{{{N-2}{{1'b0}}}}, 2'b10}}); // 2^{N-1} * 2 = 0 (wrap)
    check({{{N}{{1'b1}}}}, {{{N}{{1'b1}}}});                    // (-1)*(-1) = 1 mod 2^{N}
    for (j = 0; j < {NW}; j = j + 1) begin
        xv[j*32 +: 32] = $random;
        yv[j*32 +: 32] = $random;
    end
    check(xv, yv);                                              // random * random
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
"""
with open(f"tb_smoke_mul{N}.v", "w") as f:
    f.write(smoke)
print(f"wrote tb_smoke_mul{N}.v")

print(f"N={N} NG={NG} K={K} OUT_STABLE={OUT_STABLE} OUT_HI={OUT_HI} "
      f"CLR_AT={CLR_AT} R_HI={R_HI} S_HI={S_HI} TB_CYC={TB_CYC}")
