#!/usr/bin/env python3
"""Emit the 256-bit masked SWAP tops — the DEX swap-sequencing DEMONSTRATOR:
a straight-line constant-product swap "program" over structural copies of the
MATCHI-verified masked units, sequenced by PUBLIC control (a global cycle
counter), all data in the two-share Boolean domain end to end.

Program (EVM ops, mod 2^N wrap semantics):
  denom = reserveIn + amountIn          ADD   (also newReserveIn)
  num   = reserveOut * amountIn         MUL   (mod 2^N)
  aout  = num / denom                   DIV   (denom != 0 by construction:
                                               reserve + amountIn > 0 on the
                                               DEX path — cf. div256 header)
  ok    = (aout >= minOut)              GT/EQ via subtract borrow-out
  nro   = reserveOut - aout             SUB   (mod 2^N)

Composition rules (design record):
  * Each stage is a VERBATIM STRUCTURAL COPY of the corresponding verified
    dataflow — mul256 (carry-save multiplier), div256 (restoring divider),
    top_add256_opini2 (ripple add/sub, incl. borrow-out compare) — NOT a
    module instantiation: a nested module carrying matchi_prop would be read
    by MATCHI as an opaque gadget leaf instead of being traversed. Only the
    O-PINI2 leaf (MSKand_opini2_d2, byte-identical, read-only reference) is
    instantiated.
  * Every inter-stage hand-off is a PER-SHARE register capture at a fixed
    public count (mprod <= mul ripple wires; D <= denom-add wires; div loads
    A <= mprod, Bn <= ~D at its go strobe; ok/nror <= cmp/sub wires). No gate
    anywhere mixes share 0 and share 1 of any masked value.
  * Sequencing is PUBLIC and data-independent: one global cycle counter
    (the div256 counter pattern — the deepest window is ~DK*N cycles, far too
    long for a go-shift-register) issues per-stage strobes at fixed counts.
  * Each of the {NG} gadgets has a DEDICATED r[k]/s[k] random bit, disjoint
    slices per stage (mul | denom-add | div | cmp | subro). Fresh every cycle.
  * State-register sensitivity is BOUNDED IN TIME: ONE global clr at CLR_AT
    zeroes every conditional state register (held operands, mul state, mprod,
    D, div state, ok, nror) after the output window; the unconditional
    1-cycle balance/delay registers drain by themselves one cycle later;
    non-sensitivity then ripples down the still-executing carry chains at
    ~2 cycles/bit (the mul256/div256 drain analysis) -> ~2N out_act tail.

Schedule (cycle 0 = swap go; registers load at the edge INTO cycle 1):
  A: mul runs [1, 8N], prod stable 10N+8, captured at MUL_CAP = 10N+12;
     denom add settles ~2N+6, D captured at ADD_CAP = 2N+12.
  B: div go strobe at DIV_GO = MUL_CAP+4; iteration period DK = 2N+16
     (M1 = 2N+8 capture point inside each iteration — the div256 schedule);
     q/rem registers stable from DIV_OUT = DIV_GO + DK*N + 1.
  C: cmp + subro ripple over the frozen Q; ok/nror captured at
     OK_CAP = DIV_OUT + 2N + 12.  Outputs valid [OK_CAP+1, CLR_AT].
  clr at CLR_AT = OK_CAP + 6; tb $finishes at TB_CYC = CLR_AT + 30 while all
  windows are STILL OPEN (out [0, TB_CYC+500], r/s just past that) — windows
  never close inside the trace (keccak w>=16 root-cause, f2e50d60f).

Gadget latency contract (inb@0, rnd@0, ina@1, s@1, out@3): every gadget ina
is a 1-cycle per-share balance register (hri_d, hro_d, Q_d, and the mul/div
internal delays — the iszero256 pattern) or the naturally-late ripple carry
(the verified-adder pattern).

Emits (suffix = N): swap{N}.v (OPINI target), swap{N}_pini.v (label control —
EXPECTED to FAIL: the embedded divider reuses gadgets bubble-free with
feedback, the exact structure MATCHI's PINI transition rule rejects, cf.
div16_pini "no pipeline bubble"), swap{N}_rndreuse.v (NEG control, must FAIL:
u_dm_1 reuses u_dm_0's r/s), swap{N}_recomb.v (NEG control, must FAIL:
register recombining aout[0]^aout[1]); tb_swap{N}.v (MATCHI tb);
tb_smoke_swap{N}.v (functional: recombined outputs == reference swap).
Generated by gen_swap256.py; do not hand-edit — regenerate instead.
Usage: gen_swap256.py [N]   (default 256)
"""
import sys

N = int(sys.argv[1]) if len(sys.argv) > 1 else 256
GADGET = "MSKand_opini2_d2"

# ---- gadget budget: disjoint per-stage r/s slices ----
NG_MUL = 5 * N - 4              # mul256 copy (u_mpp/u_msc/u_mpx/u_mg/u_mt)
NG_ADD = 2 * (N - 1)            # denom add   (u_ag/u_at; top carry dropped)
NG_DIV = 3 * N + 2              # div256 copy (u_dg/u_dt/u_dm)
NG_CMP = 2 * N                  # slippage compare (u_cg/u_ct; borrow-out kept)
NG_SUB = 2 * (N - 1)            # reserveOut update (u_sg/u_st)
MB = 0                          # r/s base offsets
AB = MB + NG_MUL
DB = AB + NG_ADD
CB = DB + NG_DIV
SB = CB + NG_CMP
NG = SB + NG_SUB                # = 14N - 6
ITW = max(2, (N - 1).bit_length() + 1)

# ---- schedule constants (cycle 0 = go) ----
MK = 8                          # mul iteration period (mul256)
MUL_OUT = 10 * N + 8            # mul prod wires stable (mul256 analysis)
MUL_CAP = MUL_OUT + 4           # mprod registers capture strobe
ADD_CAP = 2 * N + 12            # denom D registers capture strobe
DIV_GO = MUL_CAP + 4            # div stage go strobe
DK = 2 * N + 16                 # div iteration period (div256)
M1 = 2 * N + 8                  # div in-iteration Treg/cout capture phase
DIV_OUT = DIV_GO + DK * N + 1   # div Q/R registers stable
OK_CAP = DIV_OUT + 2 * N + 12   # cmp/subro settled: ok/nror capture strobe
CLR_AT = OK_CAP + 6             # global clear of all conditional state regs
# Windows NEVER close inside the trace (the keccak w>=16 root-cause fix,
# commit f2e50d60f: MATCHI does not drain persistent-state sensitivity after a
# share-local clear). The tb $finishes at TB_CYC while every window is still
# open; OUT_HI/R_HI/S_HI sit far past any cycle the trace can reach.
TB_CYC = CLR_AT + 30            # MATCHI tb run length after go ($finish here)
OUT_HI = TB_CYC + 500           # far past every cycle the trace can reach
R_HI = OUT_HI + 2
S_HI = R_HI + 1
CNTW = max(ITW + 6, (S_HI + 2).bit_length() + 1)
SMOKE_SAMPLE = CLR_AT - 5       # smoke: sample outputs here (stable, pre-clr)
SMOKE_GAP = 60


def share_concat(port, share, n=N):
    """Dense sharing unpack: {port[2*(n-1)+share], ..., port[share]}."""
    return "{" + ", ".join(f"{port}[{2*j+share}]" for j in range(n - 1, -1, -1)) + "}"


def header(modname, leaf, comment, recomb=False):
    ep = ", leak_o" if recomb else ""
    lk = ('\n(* matchi_type = "sharing", matchi_active = "out_act" *) '
          "output [1:0] leak_o;") if recomb else ""
    return f"""{comment}
// Constant-product swap program over the verified masked units (structural
// copies): denom=ri+x (ADD), num=ro*x (MUL), aout=num/denom (DIV), ok =
// (aout>=mo) (borrow-out compare), nro=ro-aout (SUB). {NG} assumed-OPINI
// gadget leaves ({NG_MUL} mul u_mpp_*/u_msc_*/u_mpx_*/u_mg_*/u_mt_*, {NG_ADD} denom-add
// u_ag_*/u_at_*, {NG_DIV} div u_dg_*/u_dt_*/u_dm_*, {NG_CMP} compare u_cg_*/u_ct_*,
// {NG_SUB} reserve-sub u_sg_*/u_st_*), each with a DEDICATED r[k]/s[k] random bit
// (disjoint per-stage slices). Every XOR/NOT/shift/hand-off is strictly
// share-local; control (counter, strobes, FSMs) is public and data-independent.
// Dense sharing layout (share index fastest): port[2i]=share0, port[2i+1]=share1.
// Schedule: load @0; mul [1,{MK*N}], prod captured @{MUL_CAP}; denom captured @{ADD_CAP};
// div go @{DIV_GO}, iteration i occupies [{DIV_GO}+1+{DK}i, {DIV_GO}+{DK}(i+1)], Q/R stable @{DIV_OUT};
// ok/nro captured @{OK_CAP}; outputs valid [{OK_CAP+1},{CLR_AT}]; global clr @{CLR_AT};
// randoms fresh [0,{R_HI}].
(* matchi_prop = "PINI", matchi_strat = "composite_top", matchi_arch = "loopy", matchi_shares = 2 *)
module {modname} (clk, rst, go, x, ri, ro, mo, r, s, aout, nri, nro, ok{ep});
(* matchi_type = "clock" *)   input clk;
(* matchi_type = "control" *) input rst;
(* matchi_type = "control" *) input go;
(* matchi_type = "sharings_dense", matchi_active = "in_act" *) input [{2*N-1}:0] x;
(* matchi_type = "sharings_dense", matchi_active = "in_act" *) input [{2*N-1}:0] ri;
(* matchi_type = "sharings_dense", matchi_active = "in_act" *) input [{2*N-1}:0] ro;
(* matchi_type = "sharings_dense", matchi_active = "in_act" *) input [{2*N-1}:0] mo;
(* matchi_type = "random", matchi_active = "r_act" *) input [{NG-1}:0] r;
(* matchi_type = "random", matchi_active = "s_act" *) input [{NG-1}:0] s;
(* matchi_type = "sharings_dense", matchi_active = "out_act" *) output [{2*N-1}:0] aout;
(* matchi_type = "sharings_dense", matchi_active = "out_act" *) output [{2*N-1}:0] nri;
(* matchi_type = "sharings_dense", matchi_active = "out_act" *) output [{2*N-1}:0] nro;
(* matchi_type = "sharing", matchi_active = "out_act" *) output [1:0] ok;{lk}

// ---- global cycle counter (public control; counts 1.. from go, saturates —
// the div256 window pattern) + per-stage strobes at fixed counts ----
reg [{CNTW-1}:0] cnt;
always @(posedge clk) begin
    if (rst)                       cnt <= {CNTW}'d0;
    else if (go)                   cnt <= {CNTW}'d1;
    else if (cnt != {CNTW}'d0 && cnt != {CNTW}'d{S_HI + 2}) cnt <= cnt + {CNTW}'d1;
end
(* keep *) wire in_act  = go || (cnt == {CNTW}'d1);   // operands consumed at load
(* keep *) wire r_act   = go || (cnt >= {CNTW}'d1 && cnt <= {CNTW}'d{R_HI});
(* keep *) wire s_act   =       (cnt >= {CNTW}'d1 && cnt <= {CNTW}'d{S_HI});
(* keep *) wire out_act = go || (cnt >= {CNTW}'d1 && cnt <= {CNTW}'d{OUT_HI});
wire add_cap = (cnt == {CNTW}'d{ADD_CAP});   // denom D <= adder wires
wire mul_cap = (cnt == {CNTW}'d{MUL_CAP});   // mprod <= mul ripple wires
wire d_go    = (cnt == {CNTW}'d{DIV_GO});    // div stage load strobe
wire ok_cap  = (cnt == {CNTW}'d{OK_CAP});    // ok/nror <= cmp/subro wires
(* keep *) wire clr = (cnt == {CNTW}'d{CLR_AT});  // bounded sensitivity

// ---- held operands (per-share; loaded at go, cleared at clr) ----
reg [{N-1}:0] hx0, hx1;          // amountIn
reg [{N-1}:0] hri0, hri1;        // reserveIn
reg [{N-1}:0] hro0, hro1;        // reserveOut
reg [{N-1}:0] hmo0, hmo1;        // minOut
always @(posedge clk) begin
    if (rst || clr) begin
        hx0 <= 0; hx1 <= 0; hri0 <= 0; hri1 <= 0;
        hro0 <= 0; hro1 <= 0; hmo0 <= 0; hmo1 <= 0;
    end else if (go) begin        // dense-share unpack, share-local
        hx0  <= {share_concat('x', 0)};
        hx1  <= {share_concat('x', 1)};
        hri0 <= {share_concat('ri', 0)};
        hri1 <= {share_concat('ri', 1)};
        hro0 <= {share_concat('ro', 0)};
        hro1 <= {share_concat('ro', 1)};
        hmo0 <= {share_concat('mo', 0)};
        hmo1 <= {share_concat('mo', 1)};
    end
end

// ==================== stage A1: MUL num = ro * x (mul256 copy) ====================
// ---- mul public FSM (period {MK}) ----
reg m_running;
reg [{ITW-1}:0] m_it;
reg [2:0] m_ph;
always @(posedge clk) begin
    if (rst) begin m_running <= 1'b0; m_it <= 0; m_ph <= 3'd0; end
    else if (go) begin m_running <= 1'b1; m_it <= 0; m_ph <= 3'd0; end
    else if (m_running) begin
        if (m_ph == 3'd7) begin
            m_ph <= 3'd0;
            if (m_it == {ITW}'d{N-1}) begin m_running <= 1'b0; m_it <= 0; end
            else m_it <= m_it + {ITW}'d1;
        end else m_ph <= m_ph + 3'd1;
    end
end

// ---- mul state registers (per-share; NEVER mix shares) ----
reg [{N-1}:0] m_aa0, m_aa1;      // multiplicand = reserveOut, shifts left
reg [{N-1}:0] m_bb0, m_bb1;      // multiplier = amountIn, shifts right
reg [{N-1}:0] m_S0, m_S1, m_C0, m_C1;
reg [{N-1}:0] m_pp0, m_pp1;
wire [{N-1}:0] w_mpp0, w_mpp1;
wire [{N-2}:0] w_msc0, w_msc1, w_mpx0, w_mpx1;
wire [{N-2}:0] m_maj0 = w_msc0 ^ w_mpx0;   // share-local
wire [{N-2}:0] m_maj1 = w_msc1 ^ w_mpx1;

always @(posedge clk) begin
    if (rst || clr) begin
        m_aa0 <= 0; m_aa1 <= 0; m_bb0 <= 0; m_bb1 <= 0;
        m_S0 <= 0; m_S1 <= 0; m_C0 <= 0; m_C1 <= 0; m_pp0 <= 0; m_pp1 <= 0;
    end else if (go) begin        // dense-share unpack, share-local
        m_aa0 <= {share_concat('ro', 0)};
        m_aa1 <= {share_concat('ro', 1)};
        m_bb0 <= {share_concat('x', 0)};
        m_bb1 <= {share_concat('x', 1)};
        m_S0 <= 0; m_S1 <= 0; m_C0 <= 0; m_C1 <= 0; m_pp0 <= 0; m_pp1 <= 0;
    end else if (m_running) begin
        if (m_ph == 3'd3) begin m_pp0 <= w_mpp0; m_pp1 <= w_mpp1; end
        if (m_ph == 3'd7) begin
            m_S0 <= m_S0 ^ m_C0 ^ m_pp0;            // share-local
            m_S1 <= m_S1 ^ m_C1 ^ m_pp1;
            m_C0 <= {{m_maj0, 1'b0}};
            m_C1 <= {{m_maj1, 1'b0}};
            m_aa0 <= {{m_aa0[{N-2}:0], 1'b0}};
            m_aa1 <= {{m_aa1[{N-2}:0], 1'b0}};
            m_bb0 <= {{1'b0, m_bb0[{N-1}:1]}};
            m_bb1 <= {{1'b0, m_bb1[{N-1}:1]}};
        end
    end
end

// ---- 1-cycle per-share balance registers (unconditional: self-draining) ----
reg [{N-1}:0] m_aa_d0, m_aa_d1;  // ina of u_mpp_*  (inb = m_bb bit)
reg [{N-1}:0] m_c_d0, m_c_d1;    // ina of u_msc_*  (inb = m_S)
reg [{N-1}:0] m_x_d0, m_x_d1;    // ina of u_mpx_*  (inb = m_pp)
reg [{N-1}:0] m_S_d0, m_S_d1;    // final-add operand a := delayed S (b := C)
always @(posedge clk) begin
    m_aa_d0 <= m_aa0;         m_aa_d1 <= m_aa1;
    m_c_d0  <= m_C0;          m_c_d1  <= m_C1;
    m_x_d0  <= m_S0 ^ m_C0;   m_x_d1  <= m_S1 ^ m_C1;
    m_S_d0  <= m_S0;          m_S_d1  <= m_S1;
end

// ---- mul product capture (inter-stage hand-off, per-share) ----
// (* keep *): mprodw feeds only register inputs; without keep, abc absorbs the
// XOR drivers into the register cone and MATCHI hits a driverless wire.
(* keep *) wire [{N-1}:0] mprodw0, mprodw1;   // mul final-ripple sum wires
reg [{N-1}:0] mprod0, mprod1;                 // captured num = ro*x mod 2^{N}
always @(posedge clk) begin
    if (rst || clr) begin mprod0 <= 0; mprod1 <= 0; end
    else if (mul_cap) begin mprod0 <= mprodw0; mprod1 <= mprodw1; end
end

// ==================== stage A2: ADD denom = ri + x (adder dataflow) ====================
// operands: b := hx (inb@0), a := hri_d (ina@1 via balance register)
reg [{N-1}:0] hri_d0, hri_d1;
always @(posedge clk) begin
    hri_d0 <= hri0;  hri_d1 <= hri1;
end
(* keep *) wire [{N-1}:0] a_sum0, a_sum1;     // denom sum wires (feed D regs only)
reg [{N-1}:0] D0, D1;                         // captured denom (= newReserveIn)
always @(posedge clk) begin
    if (rst || clr) begin D0 <= 0; D1 <= 0; end
    else if (add_cap) begin D0 <= a_sum0; D1 <= a_sum1; end
end

// ==================== stage B: DIV aout = num / denom (div256 copy) ====================
// ---- div public FSM (period {DK}), started by the d_go strobe ----
reg d_running;
reg [{ITW-1}:0] d_it;
reg [{(DK-1).bit_length()-1}:0] d_ph;
always @(posedge clk) begin
    if (rst) begin d_running <= 1'b0; d_it <= 0; d_ph <= 0; end
    else if (d_go) begin d_running <= 1'b1; d_it <= 0; d_ph <= 0; end
    else if (d_running) begin
        if (d_ph == {DK-1}) begin
            d_ph <= 0;
            if (d_it == {ITW}'d{N-1}) begin d_running <= 1'b0; d_it <= 0; end
            else d_it <= d_it + {ITW}'d1;
        end else d_ph <= d_ph + 1'b1;
    end
end

// ---- div state registers (per-share; NEVER mix shares) ----
reg [{N-1}:0] d_R0, d_R1;        // partial remainder
reg [{N-1}:0] d_A0, d_A1;        // dividend = num, shifts left
reg [{N-1}:0] d_Q0, d_Q1;        // quotient = amountOut, shifts left
reg [{N-1}:0] d_Bn0, d_Bn1;      // ~denom (complement share 0 only)
reg [{N-1}:0] d_Treg0, d_Treg1;  // registered subtract result (settled)
reg d_coutr0, d_coutr1;          // registered carry-out = quotient bit
wire [{N}:0] d_Rsh0 = {{d_R0, d_A0[{N-1}]}};
wire [{N}:0] d_Rsh1 = {{d_R1, d_A1[{N-1}]}};
wire [{N-1}:0] w_dm0, w_dm1;     // borrow-mux gadget outputs
// (* keep *): T/coutw feed only register inputs (div256 lesson)
(* keep *) wire [{N-1}:0] d_T0, d_T1;
(* keep *) wire d_coutw0, d_coutw1;

always @(posedge clk) begin
    if (rst || clr) begin
        d_R0 <= 0; d_R1 <= 0; d_A0 <= 0; d_A1 <= 0; d_Q0 <= 0; d_Q1 <= 0;
        d_Bn0 <= 0; d_Bn1 <= 0; d_Treg0 <= 0; d_Treg1 <= 0;
        d_coutr0 <= 0; d_coutr1 <= 0;
    end else if (d_go) begin      // inter-stage hand-off: per-share reg copies
        d_A0 <= mprod0;           // dividend = captured num
        d_A1 <= mprod1;
        d_Bn0 <= ~D0;             // share-local NOT: complement share 0
        d_Bn1 <= D1;              // share 1 untouched
        d_R0 <= 0; d_R1 <= 0; d_Q0 <= 0; d_Q1 <= 0;
        d_Treg0 <= 0; d_Treg1 <= 0; d_coutr0 <= 0; d_coutr1 <= 0;
    end else if (d_running) begin
        if (d_ph == {M1-1}) begin   // subtract ripple settled: capture T, cout
            d_Treg0 <= d_T0; d_Treg1 <= d_T1;
            d_coutr0 <= d_coutw0; d_coutr1 <= d_coutw1;
        end
        if (d_ph == {DK-1}) begin   // iteration update (all share-local)
            d_R0 <= d_Rsh0[{N-1}:0] ^ w_dm0;   // R' = cout ? T : Rsh
            d_R1 <= d_Rsh1[{N-1}:0] ^ w_dm1;
            d_Q0 <= {{d_Q0[{N-2}:0], d_coutr0}};
            d_Q1 <= {{d_Q1[{N-2}:0], d_coutr1}};
            d_A0 <= {{d_A0[{N-2}:0], 1'b0}};
            d_A1 <= {{d_A1[{N-2}:0], 1'b0}};
        end
    end
end

// ---- 1-cycle per-share balance registers (unconditional: self-draining) ----
reg [{N}:0] d_Rsh_d0, d_Rsh_d1;  // ina of u_dg_*  (inb = d_Bn)
reg [{N-1}:0] d_xm_d0, d_xm_d1;  // ina of u_dm_*  (inb = d_coutr)
always @(posedge clk) begin
    d_Rsh_d0 <= d_Rsh0;                        d_Rsh_d1 <= d_Rsh1;
    d_xm_d0  <= d_Rsh0[{N-1}:0] ^ d_Treg0;     d_xm_d1  <= d_Rsh1[{N-1}:0] ^ d_Treg1;
end

// ==================== stage C: CMP ok = (aout >= mo), SUB nro = ro - aout ====================
// cmp: aout - mo borrow-out. b := mo complemented share-locally (sub=1),
// a := Q via balance register. subro: b := ~Q (share 0), a := hro_d.
reg [{N-1}:0] d_Q_d0, d_Q_d1;    // ina of u_cg_* (inb = ~hmo0/hmo1)
reg [{N-1}:0] hro_d0, hro_d1;    // ina of u_sg_* (inb = ~d_Q0/d_Q1)
always @(posedge clk) begin
    d_Q_d0 <= d_Q0;  d_Q_d1 <= d_Q1;
    hro_d0 <= hro0;  hro_d1 <= hro1;
end
(* keep *) wire c_coutw0, c_coutw1;           // compare borrow-out wires
(* keep *) wire [{N-1}:0] s_sum0, s_sum1;     // reserve-sub sum wires
reg ok0, ok1;                                 // captured ok = (aout >= mo)
reg [{N-1}:0] nror0, nror1;                   // captured nro = ro - aout
always @(posedge clk) begin
    if (rst || clr) begin ok0 <= 0; ok1 <= 0; nror0 <= 0; nror1 <= 0; end
    else if (ok_cap) begin
        ok0 <= c_coutw0; ok1 <= c_coutw1;
        nror0 <= s_sum0; nror1 <= s_sum1;
    end
end

// ---- outputs: dense re-pack of the result registers (share-local wiring) ----
assign ok = {{ok1, ok0}};
"""


def outputs_body():
    L = []
    for j in range(N):
        L.append(f"assign aout[{2*j}] = d_Q0[{j}];  assign aout[{2*j+1}] = d_Q1[{j}];  "
                 f"assign nri[{2*j}] = D0[{j}];  assign nri[{2*j+1}] = D1[{j}];  "
                 f"assign nro[{2*j}] = nror0[{j}];  assign nro[{2*j+1}] = nror1[{j}];")
    return "\n".join(L)


def mul_body(leaf):
    """Verbatim mul256 gadget body, m_-prefixed, r/s base MB."""
    L = []
    o = L.append
    o(f"\n// ===== mul PP gating: PP[j] = m_aa[j] AND m_bb[0] (mul256 copy) =====")
    for j in range(N):
        o(f"""{leaf} u_mpp_{j} (
    .ina({{m_aa_d1[{j}], m_aa_d0[{j}]}}), .inb({{m_bb1[0], m_bb0[0]}}),
    .rnd(r[{MB+j}]), .s(s[{MB+j}]), .clk(clk), .out({{w_mpp1[{j}], w_mpp0[{j}]}}));""")
    o(f"\n// ===== mul carry-save MAJ: newC[j+1] = (S&C)[j] ^ (PP&(S^C))[j] =====")
    for j in range(N - 1):
        o(f"""{leaf} u_msc_{j} (
    .ina({{m_c_d1[{j}], m_c_d0[{j}]}}), .inb({{m_S1[{j}], m_S0[{j}]}}),
    .rnd(r[{MB+N+2*j}]), .s(s[{MB+N+2*j}]), .clk(clk), .out({{w_msc1[{j}], w_msc0[{j}]}}));
{leaf} u_mpx_{j} (
    .ina({{m_x_d1[{j}], m_x_d0[{j}]}}), .inb({{m_pp1[{j}], m_pp0[{j}]}}),
    .rnd(r[{MB+N+2*j+1}]), .s(s[{MB+N+2*j+1}]), .clk(clk), .out({{w_mpx1[{j}], w_mpx0[{j}]}}));""")
    base = MB + 3 * N - 2
    o(f"""
// ===== mul final ripple add: num = S + C mod 2^{N} (verified-adder dataflow, sub=0) =====
wire [{N-2}:0] m_fc0, m_fc1;
assign m_fc0[0] = 1'b0;
assign m_fc1[0] = 1'b0;""")
    for j in range(N - 1):
        cw0, cw1 = (f"m_fc0[{j+1}]", f"m_fc1[{j+1}]") if j < N - 2 else ("m_fct0", "m_fct1")
        cd = "assign" if j < N - 2 else "wire"
        o(f"""wire mp0_{j} = m_S_d0[{j}] ^ m_C0[{j}];
wire mp1_{j} = m_S_d1[{j}] ^ m_C1[{j}];
wire mg0_{j}, mg1_{j}, mt0_{j}, mt1_{j};
{leaf} u_mg_{j} (
    .ina({{m_S_d1[{j}], m_S_d0[{j}]}}), .inb({{m_C1[{j}], m_C0[{j}]}}),
    .rnd(r[{base+2*j}]), .s(s[{base+2*j}]), .clk(clk), .out({{mg1_{j}, mg0_{j}}}));
{leaf} u_mt_{j} (
    .ina({{m_fc1[{j}], m_fc0[{j}]}}), .inb({{mp1_{j}, mp0_{j}}}),
    .rnd(r[{base+2*j+1}]), .s(s[{base+2*j+1}]), .clk(clk), .out({{mt1_{j}, mt0_{j}}}));
{cd} {cw0} = mg0_{j} ^ mt0_{j};
{cd} {cw1} = mg1_{j} ^ mt1_{j};
assign mprodw0[{j}] = mp0_{j} ^ m_fc0[{j}];
assign mprodw1[{j}] = mp1_{j} ^ m_fc1[{j}];""")
    j = N - 1
    o(f"""// top bit: sum only, carry-out dropped (mod 2^{N}, EVM MUL)
wire mp0_{j} = m_S_d0[{j}] ^ m_C0[{j}];
wire mp1_{j} = m_S_d1[{j}] ^ m_C1[{j}];
assign mprodw0[{j}] = mp0_{j} ^ m_fct0;
assign mprodw1[{j}] = mp1_{j} ^ m_fct1;""")
    return "\n".join(L)


def add_body(leaf):
    """Denom add ri + x mod 2^N: verified-adder dataflow, sub=0.
    a := hri_d (balance reg), b := hx (held)."""
    L = []
    o = L.append
    o(f"""
// ===== denom ripple add: D = ri + x mod 2^{N} (verified-adder dataflow, sub=0) =====
wire [{N-2}:0] a_fc0, a_fc1;
assign a_fc0[0] = 1'b0;
assign a_fc1[0] = 1'b0;""")
    for j in range(N - 1):
        cw0, cw1 = (f"a_fc0[{j+1}]", f"a_fc1[{j+1}]") if j < N - 2 else ("a_fct0", "a_fct1")
        cd = "assign" if j < N - 2 else "wire"
        o(f"""wire ap0_{j} = hri_d0[{j}] ^ hx0[{j}];
wire ap1_{j} = hri_d1[{j}] ^ hx1[{j}];
wire ag0_{j}, ag1_{j}, at0_{j}, at1_{j};
{leaf} u_ag_{j} (
    .ina({{hri_d1[{j}], hri_d0[{j}]}}), .inb({{hx1[{j}], hx0[{j}]}}),
    .rnd(r[{AB+2*j}]), .s(s[{AB+2*j}]), .clk(clk), .out({{ag1_{j}, ag0_{j}}}));
{leaf} u_at_{j} (
    .ina({{a_fc1[{j}], a_fc0[{j}]}}), .inb({{ap1_{j}, ap0_{j}}}),
    .rnd(r[{AB+2*j+1}]), .s(s[{AB+2*j+1}]), .clk(clk), .out({{at1_{j}, at0_{j}}}));
{cd} {cw0} = ag0_{j} ^ at0_{j};
{cd} {cw1} = ag1_{j} ^ at1_{j};
assign a_sum0[{j}] = ap0_{j} ^ a_fc0[{j}];
assign a_sum1[{j}] = ap1_{j} ^ a_fc1[{j}];""")
    j = N - 1
    o(f"""// top bit: sum only, carry-out dropped (mod 2^{N}, EVM ADD)
wire ap0_{j} = hri_d0[{j}] ^ hx0[{j}];
wire ap1_{j} = hri_d1[{j}] ^ hx1[{j}];
assign a_sum0[{j}] = ap0_{j} ^ a_fct0;
assign a_sum1[{j}] = ap1_{j} ^ a_fct1;""")
    return "\n".join(L)


def div_body(leaf, rndreuse=False):
    """Verbatim div256 gadget body, d_-prefixed, r/s base DB."""
    L = []
    o = L.append
    o(f"""
// ===== div (N+1)-bit ripple subtract: T = Rsh + ~denom + 1 (sub=1) =====
// d_fc[0] = carry-in = public 1; d_Bn bit {N} = ~0 = public 1.
wire [{N}:0] d_fc0, d_fc1;
assign d_fc0[0] = 1'b1;
assign d_fc1[0] = 1'b0;""")
    for j in range(N + 1):
        b0 = f"d_Bn0[{j}]" if j < N else "1'b1"
        b1 = f"d_Bn1[{j}]" if j < N else "1'b0"
        cl0, cl1 = (f"assign d_fc0[{j+1}]", f"assign d_fc1[{j+1}]") if j < N else \
                   ("assign d_coutw0", "assign d_coutw1")
        o(f"""wire dp0_{j} = d_Rsh_d0[{j}] ^ {b0};
wire dp1_{j} = d_Rsh_d1[{j}] ^ {b1};
wire dg0_{j}, dg1_{j}, dt0_{j}, dt1_{j};
{leaf} u_dg_{j} (
    .ina({{d_Rsh_d1[{j}], d_Rsh_d0[{j}]}}), .inb({{{b1}, {b0}}}),
    .rnd(r[{DB+2*j}]), .s(s[{DB+2*j}]), .clk(clk), .out({{dg1_{j}, dg0_{j}}}));
{leaf} u_dt_{j} (
    .ina({{d_fc1[{j}], d_fc0[{j}]}}), .inb({{dp1_{j}, dp0_{j}}}),
    .rnd(r[{DB+2*j+1}]), .s(s[{DB+2*j+1}]), .clk(clk), .out({{dt1_{j}, dt0_{j}}}));
{cl0} = dg0_{j} ^ dt0_{j};
{cl1} = dg1_{j} ^ dt1_{j};""")
    o(f"// difference bits (only [{N-1}:0] needed: both R' branches are < denom < 2^{N})")
    for j in range(N):
        o(f"assign d_T0[{j}] = dp0_{j} ^ d_fc0[{j}];  assign d_T1[{j}] = dp1_{j} ^ d_fc1[{j}];")
    mbase = DB + 2 * (N + 1)
    o(f"\n// ===== div borrow-mux: w_dm[j] = d_coutr AND d_xm[j] (broadcast) =====")
    for j in range(N):
        if rndreuse and j == 1:
            rk, sk = f"r[{mbase}]", f"s[{mbase}]"
            note = "  // BUG UNDER TEST: reuses u_dm_0's randomness"
        else:
            rk, sk = f"r[{mbase+j}]", f"s[{mbase+j}]"
            note = ""
        o(f"""{leaf} u_dm_{j} ({note}
    .ina({{d_xm_d1[{j}], d_xm_d0[{j}]}}), .inb({{d_coutr1, d_coutr0}}),
    .rnd({rk}), .s({sk}), .clk(clk), .out({{w_dm1[{j}], w_dm0[{j}]}}));""")
    return "\n".join(L)


def cmp_body(leaf):
    """Slippage compare: ok = carry-out of aout + ~mo + 1 over N bits =
    NOT borrow of (aout - mo) = (aout >= mo). Full 2N gadgets (borrow-out is
    the result); sum bits are not formed. a := d_Q_d, b := ~hmo0/hmo1."""
    L = []
    o = L.append
    o(f"""
// ===== slippage compare: ok = (aout >= mo) via subtract borrow-out (sub=1) =====
// c_fc[0] = carry-in = public 1; b share 0 complemented share-locally (~mo).
wire [{N}:0] c_fc0, c_fc1;
assign c_fc0[0] = 1'b1;
assign c_fc1[0] = 1'b0;""")
    for j in range(N):
        cl0, cl1 = (f"assign c_fc0[{j+1}]", f"assign c_fc1[{j+1}]")
        o(f"""wire cb0_{j} = ~hmo0[{j}];
wire cp0_{j} = d_Q_d0[{j}] ^ cb0_{j};
wire cp1_{j} = d_Q_d1[{j}] ^ hmo1[{j}];
wire cg0_{j}, cg1_{j}, ct0_{j}, ct1_{j};
{leaf} u_cg_{j} (
    .ina({{d_Q_d1[{j}], d_Q_d0[{j}]}}), .inb({{hmo1[{j}], cb0_{j}}}),
    .rnd(r[{CB+2*j}]), .s(s[{CB+2*j}]), .clk(clk), .out({{cg1_{j}, cg0_{j}}}));
{leaf} u_ct_{j} (
    .ina({{c_fc1[{j}], c_fc0[{j}]}}), .inb({{cp1_{j}, cp0_{j}}}),
    .rnd(r[{CB+2*j+1}]), .s(s[{CB+2*j+1}]), .clk(clk), .out({{ct1_{j}, ct0_{j}}}));
{cl0} = cg0_{j} ^ ct0_{j};
{cl1} = cg1_{j} ^ ct1_{j};""")
    o(f"assign c_coutw0 = c_fc0[{N}];")
    o(f"assign c_coutw1 = c_fc1[{N}];")
    return "\n".join(L)


def subro_body(leaf):
    """Reserve update: nro = ro - aout mod 2^N = ro + ~aout + 1 (sub=1).
    a := hro_d, b := ~d_Q0/d_Q1 (share-local NOT). Top carry dropped."""
    L = []
    o = L.append
    o(f"""
// ===== reserve update: nro = ro - aout mod 2^{N} (verified-adder dataflow, sub=1) =====
wire [{N-2}:0] s_fc0, s_fc1;
assign s_fc0[0] = 1'b1;
assign s_fc1[0] = 1'b0;""")
    for j in range(N - 1):
        cw0, cw1 = (f"s_fc0[{j+1}]", f"s_fc1[{j+1}]") if j < N - 2 else ("s_fct0", "s_fct1")
        cd = "assign" if j < N - 2 else "wire"
        o(f"""wire sb0_{j} = ~d_Q0[{j}];
wire sp0_{j} = hro_d0[{j}] ^ sb0_{j};
wire sp1_{j} = hro_d1[{j}] ^ d_Q1[{j}];
wire sg0_{j}, sg1_{j}, st0_{j}, st1_{j};
{leaf} u_sg_{j} (
    .ina({{hro_d1[{j}], hro_d0[{j}]}}), .inb({{d_Q1[{j}], sb0_{j}}}),
    .rnd(r[{SB+2*j}]), .s(s[{SB+2*j}]), .clk(clk), .out({{sg1_{j}, sg0_{j}}}));
{leaf} u_st_{j} (
    .ina({{s_fc1[{j}], s_fc0[{j}]}}), .inb({{sp1_{j}, sp0_{j}}}),
    .rnd(r[{SB+2*j+1}]), .s(s[{SB+2*j+1}]), .clk(clk), .out({{st1_{j}, st0_{j}}}));
{cd} {cw0} = sg0_{j} ^ st0_{j};
{cd} {cw1} = sg1_{j} ^ st1_{j};
assign s_sum0[{j}] = sp0_{j} ^ s_fc0[{j}];
assign s_sum1[{j}] = sp1_{j} ^ s_fc1[{j}];""")
    j = N - 1
    o(f"""// top bit: sum only, carry-out dropped (mod 2^{N}, EVM SUB)
wire sb0_{j} = ~d_Q0[{j}];
wire sp0_{j} = hro_d0[{j}] ^ sb0_{j};
wire sp1_{j} = hro_d1[{j}] ^ d_Q1[{j}];
assign s_sum0[{j}] = sp0_{j} ^ s_fct0;
assign s_sum1[{j}] = sp1_{j} ^ s_fct1;""")
    return "\n".join(L)


def build(modname, leaf, comment, rndreuse=False, recomb=False):
    parts = [header(modname, leaf, comment, recomb=recomb),
             outputs_body(),
             mul_body(leaf),
             add_body(leaf),
             div_body(leaf, rndreuse=rndreuse),
             cmp_body(leaf),
             subro_body(leaf)]
    if recomb:
        parts.append("""
// BUG UNDER TEST: recombine the two shares of aout bit 0. leak0 holds
// aout[0]^aout[1] (both shares) -> the XOR gate is sensitive in ShareSet{0}
// AND ShareSet{1} -> MATCHI glitch leakage. Driven onto share 0 of leak_o.
(* keep = "yes" *) reg leak0, leak1;
always @(posedge clk) begin
    leak0 <= aout[0] ^ aout[1];
    leak1 <= 1'b0;
end
assign leak_o = {leak1, leak0};""")
    parts.append("\nendmodule\n")
    return "\n".join(parts)


def emit(fn, text, leaf, expect_count):
    n = text.count(leaf + " u_")
    assert n == expect_count, f"{fn}: leaf {leaf} x{n}, expected {expect_count}"
    with open(fn, "w") as f:
        f.write(text)
    print(f"wrote {fn}: {n} {leaf} instances")


C_MAIN = (f"// {N}-bit masked constant-product SWAP demonstrator — the DEX swap program\n"
          f"// over {NG} O-PINI2 masked-AND leaves. VERIFIED TARGET.\n"
          "// Public straight-line control over structural copies of the verified\n"
          "// mul256/div256/adder dataflows; every inter-stage hand-off per-share.")
C_PINI = ("// LABEL CONTROL: identical netlist but instantiates the PINI-relabelled\n"
          "// leaf MSKand_opini2_d2_pini. The embedded divider REUSES gadgets bubble-\n"
          "// free with feedback — the structure MATCHI's PINI transition rule rejects\n"
          "// (cf. div16_pini / div256_pini). EXPECTED FAIL (live OPINI-vs-PINI control).")
C_RND = ("// NEGATIVE CONTROL (must FAIL): identical to the target except u_dm_1\n"
         "// consumes the SAME random bits as u_dm_0, active in the same cycles,\n"
         "// instead of its dedicated pair. MATCHI must report multi-use.")
C_RCB = ("// NEGATIVE CONTROL (must FAIL): identical to the target plus one share-\n"
         "// recombining register (leak0 <= aout[0]^aout[1]). MATCHI must flag the\n"
         "// gate sensitive in multiple shares (glitch leakage).")

emit(f"swap{N}.v", build(f"swap{N}", GADGET, C_MAIN), GADGET, NG)
emit(f"swap{N}_pini.v", build(f"swap{N}_pini", GADGET + "_pini", C_PINI),
     GADGET + "_pini", NG)
emit(f"swap{N}_rndreuse.v", build(f"swap{N}_rndreuse", GADGET, C_RND, rndreuse=True),
     GADGET, NG)
emit(f"swap{N}_recomb.v", build(f"swap{N}_recomb", GADGET, C_RCB, recomb=True),
     GADGET, NG)

# ---------------- MATCHI testbench ----------------
AB_W = 2 * N
RS_W = NG
AB_WW = (AB_W + 31) // 32
RS_WW = (RS_W + 31) // 32
tb = f"""// MATCHI testbench for the swap{N} tops. Same convention as the verified
// adder/iszero/mul/div tbs: values are irrelevant to MATCHI (symbolic); only
// signal-activity timing is read from the VCD. Inputs re-randomized every
// cycle so the annotated activity windows match physics. Run length covers
// the deepest window (r [0,{R_HI}]) plus margin.
// Generated by gen_swap256.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD swap{N}
`endif
module tb ();
parameter HP = 5;
reg clk, rst, go;
reg [{AB_WW*32-1}:0] x, ri, ro, mo;
reg [{RS_WW*32-1}:0] r, s;
wire [{AB_W-1}:0] aout, nri, nro;
wire [1:0] ok;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .go(go),
             .x(x[{AB_W-1}:0]), .ri(ri[{AB_W-1}:0]),
             .ro(ro[{AB_W-1}:0]), .mo(mo[{AB_W-1}:0]),
             .r(r[{RS_W-1}:0]), .s(s[{RS_W-1}:0]),
             .aout(aout), .nri(nri), .nro(nro), .ok(ok)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < {AB_WW}; w = w + 1) begin
            x[w*32 +: 32] = $random;
            ri[w*32 +: 32] = $random;
            ro[w*32 +: 32] = $random;
            mo[w*32 +: 32] = $random;
        end
        for (w = 0; w < {RS_WW}; w = w + 1) begin
            r[w*32 +: 32] = $random;
            s[w*32 +: 32] = $random;
        end
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; go = 1'b0;
    x = 0; ri = 0; ro = 0; mo = 0; r = 0; s = 0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // cycle 0: one-cycle go pulse
    @(negedge clk); go = 1'b1; randfill;
    @(negedge clk); go = 1'b0; randfill;
    for (i = 0; i < {TB_CYC}; i = i + 1) begin
        @(negedge clk); randfill;
    end
    $finish;
end
endmodule
"""
with open(f"tb_swap{N}.v", "w") as f:
    f.write(tb)
print(f"wrote tb_swap{N}.v")

# ---------------- functional smoke testbench ----------------
NW = (N + 31) // 32
smoke = f"""// Functional smoke test for swap{N} (NOT a security check — MATCHI is the
// separate verification step). Shares each operand with a random mask, pulses
// go, waits out mul + div + compare, recombines all four outputs, compares
// against the reference constant-product swap computed in {N}-bit Verilog
// arithmetic (EVM wrap semantics). Fresh gadget randoms every cycle. denom =
// ri + x != 0 on every vector (the DEX-path precondition, cf. div256 header).
// Generated by gen_swap256.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [{2*N-1}:0] x, ri, ro, mo;
reg [{RS_WW*32-1}:0] rr, ss;
wire [{2*N-1}:0] aout, nri, nro;
wire [1:0] ok;

swap{N} dut (.clk(clk), .rst(rst), .go(go), .x(x), .ri(ri), .ro(ro), .mo(mo),
             .r(rr[{RS_W-1}:0]), .s(ss[{RS_W-1}:0]),
             .aout(aout), .nri(nri), .nro(nro), .ok(ok));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < {RS_WW}; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [{N-1}:0] xm, rim, rom, mom;
reg [{N-1}:0] got_aout, got_nri, got_nro;
reg got_ok;
reg [{N-1}:0] denom, num, expaout, expnri, expnro;
reg expok;
integer j;
task check(input [{N-1}:0] vx, input [{N-1}:0] vri,
           input [{N-1}:0] vro, input [{N-1}:0] vmo);
    begin
        // reference swap ({N}-bit wrap arithmetic = EVM semantics)
        denom = vri + vx;
        num = vro * vx;
        expaout = num / denom;      // tb guarantees denom != 0
        expnri = denom;
        expnro = vro - expaout;
        expok = (expaout >= vmo);
        // share the operands with fresh random masks
        for (j = 0; j < {NW}; j = j + 1) begin
            xm[j*32 +: 32] = $random;  rim[j*32 +: 32] = $random;
            rom[j*32 +: 32] = $random; mom[j*32 +: 32] = $random;
        end
        for (j = 0; j < {N}; j = j + 1) begin
            x[2*j]  = vx[j] ^ xm[j];    x[2*j+1]  = xm[j];
            ri[2*j] = vri[j] ^ rim[j];  ri[2*j+1] = rim[j];
            ro[2*j] = vro[j] ^ rom[j];  ro[2*j+1] = rom[j];
            mo[2*j] = vmo[j] ^ mom[j];  mo[2*j+1] = mom[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat ({SMOKE_SAMPLE}) @(negedge clk);
        for (j = 0; j < {N}; j = j + 1) begin
            got_aout[j] = aout[2*j] ^ aout[2*j+1];
            got_nri[j]  = nri[2*j] ^ nri[2*j+1];
            got_nro[j]  = nro[2*j] ^ nro[2*j+1];
        end
        got_ok = ok[0] ^ ok[1];
        if (got_aout !== expaout || got_nri !== expnri ||
            got_nro !== expnro || got_ok !== expok) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  x=%h ri=%h ro=%h mo=%h", vx, vri, vro, vmo);
            $display("  aout got=%h exp=%h", got_aout, expaout);
            $display("  nri  got=%h exp=%h", got_nri, expnri);
            $display("  nro  got=%h exp=%h", got_nro, expnro);
            $display("  ok   got=%b exp=%b", got_ok, expok);
        end else begin
            $display("PASS swap: aout=%h nri=%h nro=%h ok=%b",
                     got_aout, got_nri, got_nro, got_ok);
        end
        repeat ({SMOKE_GAP}) @(negedge clk);   // past clr before the next check
    end
endtask

reg [{N-1}:0] v1, v2, v3, v4;
initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    // 1. small AMM pool: 2000*100/1100 = 181, mo=0 -> ok=1
    check({N}'d100, {N}'d1000, {N}'d2000, {N}'d0);
    // 2. same trade, mo = exact expected aout -> ok=1 (>= boundary)
    check({N}'d100, {N}'d1000, {N}'d2000, ({N}'d2000*{N}'d100)/({N}'d1000+{N}'d100));
    // 3. same trade, mo = expected aout + 1 -> ok=0 (slippage trips)
    check({N}'d100, {N}'d1000, {N}'d2000, ({N}'d2000*{N}'d100)/({N}'d1000+{N}'d100) + {N}'d1);
    // 4. x=1, ri=0: denom=1, aout=ro, nro=0
    for (j = 0; j < {NW}; j = j + 1) v1[j*32 +: 32] = $random;
    check({N}'d1, {N}'d0, v1, v1);
    // 5. x=0: num=0, aout=0, nro=ro, ok=(0>=mo)
    for (j = 0; j < {NW}; j = j + 1) v2[j*32 +: 32] = $random;
    check({N}'d0, {N}'d7, v2, {N}'d0);
    // 6. random full-width (wrap semantics), small-ish denom for busy quotient
    for (j = 0; j < {NW}; j = j + 1) begin
        v1[j*32 +: 32] = $random;
        v2[j*32 +: 32] = $random;
        v3[j*32 +: 32] = $random;
        v4[j*32 +: 32] = $random;
    end
    v2[{N-1}:{N//2}] = 0;                 // ri small-ish
    v1[{N-1}:{N//2}] = 0;                 // x small-ish -> denom small, != 0
    if ((v1 + v2) == 0) v1 = v1 + {N}'d3;
    check(v1, v2, v3, v4);
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
"""
with open(f"tb_smoke_swap{N}.v", "w") as f:
    f.write(smoke)
print(f"wrote tb_smoke_swap{N}.v")

print(f"N={N} NG={NG} (mul {NG_MUL} @{MB}, add {NG_ADD} @{AB}, div {NG_DIV} @{DB}, "
      f"cmp {NG_CMP} @{CB}, sub {NG_SUB} @{SB})")
print(f"MUL_CAP={MUL_CAP} ADD_CAP={ADD_CAP} DIV_GO={DIV_GO} DK={DK} DIV_OUT={DIV_OUT} "
      f"OK_CAP={OK_CAP} CLR_AT={CLR_AT} OUT_HI={OUT_HI} R_HI={R_HI} S_HI={S_HI} TB_CYC={TB_CYC}")
