#!/usr/bin/env python3
"""Emit the dexloop{N} tops — the SLOAD -> swap -> SSTORE COMPOSITION pilot:
the last integration gap in SWAP_DATAPATH.md. Storage (store16x4 pattern) and
the swap program (gen_swap256.py) are each MATCHI-verified alone; this unit
closes the loop: the swap's reserve operands are LOADED from the masked
scratchpad (registered per-lane read port), the swap runs unmodified, and the
new reserves are WRITTEN BACK into the same scratchpad — all in the two-share
domain, all sequencing public.

Composition rules (design record):
  * The swap program body is reused VERBATIM from gen_swap256.py (imported,
    argv-patched): same gadget bodies, same schedule constants, same counter.
    The ONLY change inside the swap text: the held-operand load sources for
    reserveIn/reserveOut are redirected from input ports to the storage-read
    capture registers rri/rro (per-share, same-edge, deterministic string
    replacement asserted unique). x (amountIn) and mo (minOut) stay ports
    (calldata, not storage).
  * Storage lanes are a structural copy of the VERIFIED store16x4: two
    physically-separate lanes m0_*/m1_*, explicit registers (no memory
    inference), per-lane write decode, registered per-lane read port
    (transitions stay in-lane). Paging dropped (verified separately, unused).
  * Prefix FSM (public counter pcnt, cycle 0 = tx_go): SLOAD slot0 -> rri
    (both lanes captured at the SAME edge), SLOAD slot1 -> rro, then the
    internal swap `go` strobe fires at pcnt=={PGO}. WRITEBACK: at swap-counter
    OK_CAP+2 slot0 <= D (newReserveIn), at OK_CAP+3 slot1 <= nror (newRO) —
    per-lane muxed write values (lane k logic sees only share-k values of
    anything), strictly before the global clr at CLR_AT.
  * NEW-GLUE NEGATIVE CONTROL `_sharedbus` (must FAIL): the rri capture is
    routed through ONE time-multiplexed bus register — share 0 of the loaded
    reserve on one edge, share 1 of the SAME word on the next (the store16x4
    sharedbus violation, planted in the NEW hand-off): the bus register's
    value transition combines the shares in the transition model.
  * The swap-core controls come along unchanged: `_pini` label control
    (embedded bubble-free divider, LIVE FAIL), `_rndreuse` (u_dm_1 reuses
    u_dm_0's r/s; the glue itself has ZERO gadgets and ZERO randomness — like
    eq256, the reuse is planted in the embedded core), `_recomb`
    (leak <= aout[0]^aout[1]).

Emits: dexloop{N}.v (target) + _pini/_rndreuse/_recomb/_sharedbus controls,
tb_dexloop{N}.v (MATCHI tb: 2 preload writes, tx_go, windows never close),
tb_smoke_dexloop{N}.v (functional: preload reserves via SSTORE, run swap,
check outputs AND read the written-back reserves out of storage via SLOAD).
Generated by gen_dexloop.py; do not hand-edit — regenerate instead.
Usage: gen_dexloop.py [N]   (default 16; storage D=4 words)
"""
import importlib
import os
import sys
import tempfile

N = int(sys.argv[1]) if len(sys.argv) > 1 else 16
D = 4
AW = 2
GADGET = "MSKand_opini2_d2"

# ---- import gen_swap256 at our N; its import-time emits go to a temp dir ----
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.argv = ["gen_swap256.py", str(N)]
_cwd = os.getcwd()
with tempfile.TemporaryDirectory() as _td:
    os.chdir(_td)
    sw = importlib.import_module("gen_swap256")
    os.chdir(_cwd)

NG = sw.NG
NM = f"dexloop{N}"


def rep1(text, old, new):
    """Replace exactly-once (composition surgery must be deterministic)."""
    n = text.count(old)
    assert n == 1, f"expected 1 occurrence, got {n}: {old[:60]!r}"
    return text.replace(old, new)


def share_bits(port, share):
    return "{" + ", ".join(f"{port}[{2*j+share}]" for j in range(N - 1, -1, -1)) + "}"


def rmux(lane, addr):
    e = f"m{lane}_{D-1}"
    for i in range(D - 2, -1, -1):
        e = f"(({addr} == {AW}'d{i}) ? m{lane}_{i} : {e})"
    return e


def storage_early(sharedbus=False):
    """Declarations + read path + prefix FSM. Inserted BEFORE the swap
    sequencing text (iverilog needs declaration-before-use; everything that
    references swap regs — cnt, D, nror — lives in storage_late)."""
    PGO = 6 if sharedbus else 4
    L = []
    o = L.append
    o(f"""
// ===== masked storage lanes (store16x4 structural copy; paging dropped) =====
// wdata consumed exactly when we is high; storage (and rdata) sensitive from
// the first write to the end of the trace (sticky window, never closes).
reg seen_w;
always @(posedge clk) begin
    if (rst) seen_w <= 1'b0;
    else if (we) seen_w <= 1'b1;
end
(* keep *) wire a_act      = we;
(* keep *) wire st_out_act = we || seen_w;
""")
    for lane in (0, 1):
        for i in range(D):
            o(f"reg [{N-1}:0] m{lane}_{i};")
    o(f"""
// ---- per-lane external write decode (lane k sees only share-k bits) ----
wire [{N-1}:0] wd0 = {share_bits('wdata', 0)};
wire [{N-1}:0] wd1 = {share_bits('wdata', 1)};

// ---- prefix FSM (public; cycle 0 = tx_go): SLOAD ri, SLOAD ro, swap go ----
reg [2:0] pcnt;
always @(posedge clk) begin
    if (rst)                          pcnt <= 3'd0;
    else if (tx_go)                   pcnt <= 3'd1;
    else if (pcnt != 3'd0 && pcnt != 3'd7) pcnt <= pcnt + 3'd1;
end""")
    if sharedbus:
        o(f"""// sharedbus control: hold slot0 on the read port two cycles, slot1 next
wire [{AW-1}:0] st_raddr = (pcnt == 3'd1 || pcnt == 3'd2) ? {AW}'d0 :
                           (pcnt == 3'd3) ? {AW}'d1 : raddr;""")
    else:
        o(f"""wire [{AW-1}:0] st_raddr = (pcnt == 3'd1) ? {AW}'d0 :
                           (pcnt == 3'd2) ? {AW}'d1 : raddr;""")
    o(f"""
// ---- registered per-lane read port (SLOAD); transitions stay in-lane ----
reg [{N-1}:0] rreg0, rreg1;
always @(posedge clk) begin
    rreg0 <= {rmux(0, 'st_raddr')};
    rreg1 <= {rmux(1, 'st_raddr')};
end""")
    for j in range(N):
        o(f"assign rdata[{2*j}] = rreg0[{j}];  assign rdata[{2*j+1}] = rreg1[{j}];")
    o(f"""
// ---- SLOAD capture registers feeding the swap held-operand loads ----
// (persistent copies of storage words — sticky sensitivity like the pad;
// no clr, mirroring the storage lanes themselves)
reg [{N-1}:0] rri0, rri1, rro0, rro1;""")
    if sharedbus:
        o(f"""// BUG UNDER TEST (sharedbus): ONE time-multiplexed bus register carries
// share 0 of the loaded reserveIn on one edge and share 1 of the SAME word on
// the next — the bus register's value transition combines the two shares
// (transition model). The verified unit captures both lanes at the SAME edge.
reg [{N-1}:0] bus;
always @(posedge clk) begin
    if (rst) begin
        rri0 <= 0; rri1 <= 0; rro0 <= 0; rro1 <= 0; bus <= 0;
    end else begin
        if (pcnt == 3'd2) bus <= rreg0;                      // share 0 of slot0
        if (pcnt == 3'd3) begin rri0 <= bus; bus <= rreg1; end // share0 -> share1 TRANSITION
        if (pcnt == 3'd4) begin
            rri1 <= bus;
            rro0 <= rreg0; rro1 <= rreg1;                    // slot1, same edge
        end
    end
end
wire go = (pcnt == 3'd{PGO});   // internal swap-go strobe""")
    else:
        o(f"""// both lanes captured at the SAME edge (the store16x4 paging rule)
always @(posedge clk) begin
    if (rst) begin
        rri0 <= 0; rri1 <= 0; rro0 <= 0; rro1 <= 0;
    end else begin
        if (pcnt == 3'd2) begin rri0 <= rreg0; rri1 <= rreg1; end   // slot0
        if (pcnt == 3'd3) begin rro0 <= rreg0; rro1 <= rreg1; end   // slot1
    end
end
wire go = (pcnt == 3'd{PGO});   // internal swap-go strobe""")
    return "\n".join(L)


def storage_late():
    """Writeback: references swap regs (cnt, D, nror) — appended AFTER the
    swap sequencing text."""
    L = []
    o = L.append
    o(f"""
// ---- WRITEBACK strobes (swap counter domain; strictly before clr) ----
// slot0 <= D (nri = newReserveIn) at OK_CAP+2; slot1 <= nror (nro) at OK_CAP+3.
wire wb1 = (cnt == {sw.CNTW}'d{sw.OK_CAP + 2});
wire wb2 = (cnt == {sw.CNTW}'d{sw.OK_CAP + 3});
wire eff_we = we || wb1 || wb2;
wire [{AW-1}:0] eff_waddr = wb1 ? {AW}'d0 : (wb2 ? {AW}'d1 : waddr);
// per-lane write-value mux: lane k mixes only share-k values (public selects)
wire [{N-1}:0] wv0 = wb1 ? D0 : (wb2 ? nror0 : wd0);
wire [{N-1}:0] wv1 = wb1 ? D1 : (wb2 ? nror1 : wd1);

// ---- lane 0 writes ----
always @(posedge clk) begin""")
    for i in range(D):
        o(f"    if (eff_we && eff_waddr == {AW}'d{i}) m0_{i} <= wv0;")
    o("""end
// ---- lane 1 writes ----
always @(posedge clk) begin""")
    for i in range(D):
        o(f"    if (eff_we && eff_waddr == {AW}'d{i}) m1_{i} <= wv1;")
    o("end")
    return "\n".join(L)


def build(modname, leaf, comment, rndreuse=False, recomb=False, sharedbus=False):
    text = sw.header(modname, leaf, comment, recomb=recomb)
    # ---- port surgery: go -> tx_go + storage ports; ri/ro -> wdata/rdata ----
    text = rep1(text,
                "(clk, rst, go, x, ri, ro, mo, r, s, aout, nri, nro, ok",
                "(clk, rst, tx_go, we, waddr, raddr, wdata, x, mo,\n"
                "                r, s, aout, nri, nro, ok, rdata")
    text = rep1(text,
                '(* matchi_type = "control" *) input go;',
                '(* matchi_type = "control" *) input tx_go;\n'
                '(* matchi_type = "control" *) input we;\n'
                f'(* matchi_type = "control" *) input [{AW-1}:0] waddr;\n'
                f'(* matchi_type = "control" *) input [{AW-1}:0] raddr;')
    text = rep1(text,
                f'(* matchi_type = "sharings_dense", matchi_active = "in_act" *) input [{2*N-1}:0] ri;',
                f'(* matchi_type = "sharings_dense", matchi_active = "a_act" *) input [{2*N-1}:0] wdata;')
    text = rep1(text,
                f'(* matchi_type = "sharings_dense", matchi_active = "in_act" *) input [{2*N-1}:0] ro;',
                f'(* matchi_type = "sharings_dense", matchi_active = "st_out_act" *) output [{2*N-1}:0] rdata;')
    # ---- load-source surgery: reserves come from storage, not ports ----
    text = rep1(text, "hri0 <= " + sw.share_concat('ri', 0) + ";", "hri0 <= rri0;")
    text = rep1(text, "hri1 <= " + sw.share_concat('ri', 1) + ";", "hri1 <= rri1;")
    text = rep1(text, "hro0 <= " + sw.share_concat('ro', 0) + ";", "hro0 <= rro0;")
    text = rep1(text, "hro1 <= " + sw.share_concat('ro', 1) + ";", "hro1 <= rro1;")
    text = rep1(text, "m_aa0 <= " + sw.share_concat('ro', 0) + ";", "m_aa0 <= rro0;")
    text = rep1(text, "m_aa1 <= " + sw.share_concat('ro', 1) + ";", "m_aa1 <= rro1;")
    # ---- insert storage + prefix FSM before the swap counter ----
    text = rep1(text, "// ---- global cycle counter",
                storage_early(sharedbus=sharedbus) +
                "\n\n// ---- global cycle counter")
    parts = [text,
             storage_late(),
             sw.outputs_body(),
             sw.mul_body(leaf),
             sw.add_body(leaf),
             sw.div_body(leaf, rndreuse=rndreuse),
             sw.cmp_body(leaf),
             sw.subro_body(leaf)]
    if recomb:
        parts.append("""
// BUG UNDER TEST: recombine the two shares of aout bit 0. leak0 holds
// aout[0]^aout[1] (both shares) -> the XOR gate is sensitive in ShareSet{0}
// AND ShareSet{1} -> MATCHI glitch leakage. Driven onto share 0 of leak_o.
(* keep = "yes" *) reg leak0, leak1;
always @(posedge clk) begin
    leak0 <= aout[0] ^ aout[1];
    leak1 <= 1'b0;
end
assign leak_o = {leak1, leak0};""")
    parts.append("\nendmodule\n")
    return "\n".join(parts)


def emit(fn, text, leaf, expect_count):
    n = text.count(leaf + " u_")
    assert n == expect_count, f"{fn}: leaf {leaf} x{n}, expected {expect_count}"
    with open(fn, "w") as f:
        f.write(text)
    print(f"wrote {fn}: {n} {leaf} instances")


C_MAIN = (f"// {N}-bit SLOAD->swap->SSTORE COMPOSITION pilot over {NG} O-PINI2 leaves\n"
          "// + the verified two-lane masked scratchpad (0 gadgets). VERIFIED TARGET.\n"
          "// Reserves are loaded from storage, the constant-product swap program runs\n"
          "// verbatim, and the new reserves are written back — all two-share domain.")
C_PINI = ("// LABEL CONTROL: identical netlist but instantiates the PINI-relabelled\n"
          "// leaf MSKand_opini2_d2_pini. The embedded divider REUSES gadgets bubble-\n"
          "// free with feedback — the structure MATCHI's PINI transition rule rejects\n"
          "// (cf. div16_pini / swap16_pini). EXPECTED FAIL (live OPINI-vs-PINI control).")
C_RND = ("// NEGATIVE CONTROL (must FAIL): identical to the target except u_dm_1\n"
         "// consumes the SAME random bits as u_dm_0 (the glue has zero gadgets and\n"
         "// zero randomness — reuse planted in the embedded core, cf. eq256).")
C_RCB = ("// NEGATIVE CONTROL (must FAIL): identical to the target plus one share-\n"
         "// recombining register (leak0 <= aout[0]^aout[1]). MATCHI must flag the\n"
         "// gate sensitive in multiple shares (glitch leakage).")
C_BUS = ("// NEGATIVE CONTROL (must FAIL) — planted in the NEW composition glue: the\n"
         "// SLOAD->swap hand-off rides ONE time-multiplexed bus register (share 0 of\n"
         "// the loaded reserve, then share 1 of the SAME word on the next edge) —\n"
         "// the transition combines the shares (store16x4 sharedbus violation).")

emit(f"{NM}.v", build(NM, GADGET, C_MAIN), GADGET, NG)
emit(f"{NM}_pini.v", build(f"{NM}_pini", GADGET + "_pini", C_PINI),
     GADGET + "_pini", NG)
emit(f"{NM}_rndreuse.v", build(f"{NM}_rndreuse", GADGET, C_RND, rndreuse=True),
     GADGET, NG)
emit(f"{NM}_recomb.v", build(f"{NM}_recomb", GADGET, C_RCB, recomb=True),
     GADGET, NG)
emit(f"{NM}_sharedbus.v", build(f"{NM}_sharedbus", GADGET, C_BUS, sharedbus=True),
     GADGET, NG)

# ---------------- MATCHI testbench ----------------
AB_W = 2 * N
RS_W = NG
AB_WW = (AB_W + 31) // 32
RS_WW = (RS_W + 31) // 32
TB_RUN = sw.TB_CYC + 16          # covers the sharedbus PGO=6 shift too
tb = f"""// MATCHI testbench for the dexloop{N} tops. Same convention as the verified
// swap/store tbs: values are irrelevant to MATCHI (symbolic); only signal-
// activity timing is read from the VCD. Two preload SSTOREs (storage becomes
// sensitive, sticky window), one tx_go, then randfill to $finish — windows
// never close inside the trace (keccak f2e50d60f rule).
// Generated by gen_dexloop.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD dexloop{N}
`endif
module tb ();
parameter HP = 5;
reg clk, rst, tx_go, we;
reg [{AW-1}:0] waddr, raddr;
reg [{AB_WW*32-1}:0] x, mo, wdata;
reg [{RS_WW*32-1}:0] r, s;
wire [{AB_W-1}:0] aout, nri, nro, rdata;
wire [1:0] ok;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .tx_go(tx_go), .we(we), .waddr(waddr),
             .raddr(raddr), .wdata(wdata[{AB_W-1}:0]),
             .x(x[{AB_W-1}:0]), .mo(mo[{AB_W-1}:0]),
             .r(r[{RS_W-1}:0]), .s(s[{RS_W-1}:0]),
             .aout(aout), .nri(nri), .nro(nro), .ok(ok), .rdata(rdata)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < {AB_WW}; w = w + 1) begin
            x[w*32 +: 32] = $random;
            mo[w*32 +: 32] = $random;
            wdata[w*32 +: 32] = $random;
        end
        for (w = 0; w < {RS_WW}; w = w + 1) begin
            r[w*32 +: 32] = $random;
            s[w*32 +: 32] = $random;
        end
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; tx_go = 1'b0; we = 1'b0;
    waddr = 0; raddr = 0; x = 0; mo = 0; wdata = 0; r = 0; s = 0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // preload SSTOREs: slot0 (reserveIn), slot1 (reserveOut)
    @(negedge clk); we = 1'b1; waddr = {AW}'d0; randfill;
    @(negedge clk); waddr = {AW}'d1; randfill;
    @(negedge clk); we = 1'b0; tx_go = 1'b1; randfill;
    @(negedge clk); tx_go = 1'b0; randfill;
    for (i = 0; i < {TB_RUN}; i = i + 1) begin
        @(negedge clk); randfill;
    end
    $finish;
end
endmodule
"""
with open(f"tb_{NM}.v", "w") as f:
    f.write(tb)
print(f"wrote tb_{NM}.v")

# ---------------- functional smoke testbench ----------------
NW = (N + 31) // 32
PGO = 4
SAMPLE = PGO + sw.SMOKE_SAMPLE
smoke = f"""// Functional smoke test for dexloop{N} (NOT a security check — MATCHI is the
// separate step). Full storage round-trip per vector: SSTORE the two shared
// reserves, pulse tx_go (the unit SLOADs them itself), wait out the swap,
// check the direct outputs, then SLOAD the written-back reserves out of the
// scratchpad and check them against the reference too. Fresh gadget randoms
// every cycle. denom = ri + x != 0 on every vector (DEX-path precondition).
// Generated by gen_dexloop.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, tx_go = 0, we = 0;
reg [{AW-1}:0] waddr, raddr;
reg [{2*N-1}:0] x, mo, wdata;
reg [{RS_WW*32-1}:0] rr, ss;
wire [{2*N-1}:0] aout, nri, nro, rdata;
wire [1:0] ok;

dexloop{N} dut (.clk(clk), .rst(rst), .tx_go(tx_go), .we(we), .waddr(waddr),
             .raddr(raddr), .wdata(wdata), .x(x), .mo(mo),
             .r(rr[{RS_W-1}:0]), .s(ss[{RS_W-1}:0]),
             .aout(aout), .nri(nri), .nro(nro), .ok(ok), .rdata(rdata));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < {RS_WW}; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [{N-1}:0] xm, mom, wm;
reg [{N-1}:0] got_aout, got_nri, got_nro, got_slot;
reg got_ok;
reg [{N-1}:0] denom, num, expaout, expnri, expnro;
reg expok;
integer j;

task sstore(input [{AW-1}:0] slot, input [{N-1}:0] v);
    begin
        for (j = 0; j < {NW}; j = j + 1) wm[j*32 +: 32] = $random;
        for (j = 0; j < {N}; j = j + 1) begin
            wdata[2*j] = v[j] ^ wm[j];  wdata[2*j+1] = wm[j];
        end
        @(negedge clk); we = 1'b1; waddr = slot;
        @(negedge clk); we = 1'b0;
    end
endtask

task sload(input [{AW-1}:0] slot);
    begin
        raddr = slot;
        repeat (3) @(negedge clk);
        for (j = 0; j < {N}; j = j + 1)
            got_slot[j] = rdata[2*j] ^ rdata[2*j+1];
    end
endtask

task check(input [{N-1}:0] vx, input [{N-1}:0] vri,
           input [{N-1}:0] vro, input [{N-1}:0] vmo);
    begin
        // reference swap ({N}-bit wrap arithmetic = EVM semantics)
        denom = vri + vx;
        num = vro * vx;
        expaout = num / denom;      // tb guarantees denom != 0
        expnri = denom;
        expnro = vro - expaout;
        expok = (expaout >= vmo);
        // SSTORE the reserves (the previous tx's state)
        sstore({AW}'d0, vri);
        sstore({AW}'d1, vro);
        // share the calldata operands with fresh random masks
        for (j = 0; j < {NW}; j = j + 1) begin
            xm[j*32 +: 32] = $random;  mom[j*32 +: 32] = $random;
        end
        for (j = 0; j < {N}; j = j + 1) begin
            x[2*j]  = vx[j] ^ xm[j];    x[2*j+1]  = xm[j];
            mo[2*j] = vmo[j] ^ mom[j];  mo[2*j+1] = mom[j];
        end
        @(negedge clk); tx_go = 1'b1;
        @(negedge clk); tx_go = 1'b0;
        repeat ({SAMPLE}) @(negedge clk);
        for (j = 0; j < {N}; j = j + 1) begin
            got_aout[j] = aout[2*j] ^ aout[2*j+1];
            got_nri[j]  = nri[2*j] ^ nri[2*j+1];
            got_nro[j]  = nro[2*j] ^ nro[2*j+1];
        end
        got_ok = ok[0] ^ ok[1];
        if (got_aout !== expaout || got_nri !== expnri ||
            got_nro !== expnro || got_ok !== expok) begin
            errors = errors + 1;
            $display("FAIL outputs");
            $display("  x=%h ri=%h ro=%h mo=%h", vx, vri, vro, vmo);
            $display("  aout got=%h exp=%h", got_aout, expaout);
            $display("  nri  got=%h exp=%h", got_nri, expnri);
            $display("  nro  got=%h exp=%h", got_nro, expnro);
            $display("  ok   got=%b exp=%b", got_ok, expok);
        end else begin
            $display("PASS outputs: aout=%h nri=%h nro=%h ok=%b",
                     got_aout, got_nri, got_nro, got_ok);
        end
        // storage round-trip: the written-back reserves must be in the pad
        repeat (10) @(negedge clk);   // strictly after writeback + clr
        sload({AW}'d0);
        if (got_slot !== expnri) begin
            errors = errors + 1;
            $display("FAIL slot0 (nri) got=%h exp=%h", got_slot, expnri);
        end else $display("PASS slot0 (nri) = %h", got_slot);
        sload({AW}'d1);
        if (got_slot !== expnro) begin
            errors = errors + 1;
            $display("FAIL slot1 (nro) got=%h exp=%h", got_slot, expnro);
        end else $display("PASS slot1 (nro) = %h", got_slot);
        repeat ({sw.SMOKE_GAP}) @(negedge clk);
    end
endtask

reg [{N-1}:0] v1, v2, v3, v4;
initial begin
    errors = 0;
    waddr = 0; raddr = 0; x = 0; mo = 0; wdata = 0;
    #40 rst = 0;
    @(negedge clk);
    // 1. small AMM pool: 2000*100/1100 = 181, mo=0 -> ok=1
    check({N}'d100, {N}'d1000, {N}'d2000, {N}'d0);
    // 2. same trade, mo = exact expected aout -> ok=1 (>= boundary)
    check({N}'d100, {N}'d1000, {N}'d2000, ({N}'d2000*{N}'d100)/({N}'d1000+{N}'d100));
    // 3. same trade, mo = expected aout + 1 -> ok=0 (slippage trips)
    check({N}'d100, {N}'d1000, {N}'d2000, ({N}'d2000*{N}'d100)/({N}'d1000+{N}'d100) + {N}'d1);
    // 4. x=1, ri=0: denom=1, aout=ro, nro=0
    for (j = 0; j < {NW}; j = j + 1) v1[j*32 +: 32] = $random;
    check({N}'d1, {N}'d0, v1, v1);
    // 5. x=0: num=0, aout=0, nro=ro, ok=(0>=mo)
    for (j = 0; j < {NW}; j = j + 1) v2[j*32 +: 32] = $random;
    check({N}'d0, {N}'d7, v2, {N}'d0);
    // 6. random full-width (wrap semantics), small-ish denom for busy quotient
    for (j = 0; j < {NW}; j = j + 1) begin
        v1[j*32 +: 32] = $random;
        v2[j*32 +: 32] = $random;
        v3[j*32 +: 32] = $random;
        v4[j*32 +: 32] = $random;
    end
    v2[{N-1}:{N//2}] = 0;                 // ri small-ish
    v1[{N-1}:{N//2}] = 0;                 // x small-ish -> denom small, != 0
    if ((v1 + v2) == 0) v1 = v1 + {N}'d3;
    check(v1, v2, v3, v4);
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
"""
with open(f"tb_smoke_{NM}.v", "w") as f:
    f.write(smoke)
print(f"wrote tb_smoke_{NM}.v")

print(f"N={N} NG={NG} PGO=4 (sharedbus 6) OK_CAP={sw.OK_CAP} CLR_AT={sw.CLR_AT} "
      f"TB_RUN={TB_RUN} writeback @cnt {sw.OK_CAP+2}/{sw.OK_CAP+3}")
