#!/usr/bin/env python3
"""Emit tb_smoke_keccak256.v — functional smoke for the KECCAK256 SPONGE
COMPOSITION over the VERIFIED keccakf1600 round unit (RESULT_KECCAKF1600.md).

This closes the SWAP_DATAPATH.md composition note "sponge padding / rate XOR:
share-local XOR of the masked message block into the masked state — no
gadgets" with executable evidence, for the DEX-relevant case: storage-slot
addressing, slot = keccak256(key ‖ slot_index) (two 256-bit EVM words = 64
bytes, a single rate-1088 block).

Masked-domain wiring demonstrated by the tb (all share-local, ZERO new
gadgets, no new RTL — the DUT is the unmodified keccakf1600):
  * the 512 message bits enter as a 2-share sharing (share0 = bit ^ mask,
    share1 = mask) — i.e. they arrive already masked, as they would from the
    verified storage path;
  * the pad10*1 bits and capacity zeros are PUBLIC constants: XORed into
    share 0 ONLY (share 1 stays 0 there) — the share-local rate/padding XOR;
  * one f[1600] permutation (the unit's 24 rounds, one go pulse);
  * digest = recombined lanes 0..3 (256 bits).

Reference: the same spec-derived permutation as gen_keccakf.py (rho via the
(t+1)(t+2)/2 walk, RC via the degree-8 LFSR), re-anchored here on BOTH the
XKCP zero-state vector AND keccak256("") =
c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 (the
canonical empty-input digest), so the sponge byte/lane mapping itself is
anchored, not just the permutation.
Generated by gen_keccak256_smoke.py; do not hand-edit — regenerate instead.
"""
import random as _rnd

W, NR, L = 64, 24, 6
B = 1600

def rho_offsets():
    r = [[0] * 5 for _ in range(5)]
    x, y = 1, 0
    for t in range(24):
        r[x][y] = ((t + 1) * (t + 2) // 2) % W
        x, y = y, (2 * x + 3 * y) % 5
    return r

def rc_bit(t):
    if t % 255 == 0:
        return 1
    R = 1
    for _ in range(t % 255):
        R <<= 1
        if R & 0x100:
            R ^= 0x171
        R &= 0xFF
    return R & 1

RHO = rho_offsets()
RC = []
for ir in range(NR):
    v = 0
    for j in range(L + 1):
        v |= rc_bit(j + 7 * ir) << (2 ** j - 1)
    RC.append(v)
assert RC[0] == 0x1 and RC[1] == 0x8082 and RC[23] == 0x8000000080008008

def keccakf_ref(lanes):
    lanes = list(lanes)
    M = (1 << W) - 1
    def rotl(v, n):
        n %= W
        return ((v << n) | (v >> (W - n))) & M
    for ir in range(NR):
        C = [lanes[x] ^ lanes[x + 5] ^ lanes[x + 10] ^ lanes[x + 15] ^ lanes[x + 20]
             for x in range(5)]
        D = [C[(x - 1) % 5] ^ rotl(C[(x + 1) % 5], 1) for x in range(5)]
        A = [lanes[5 * y + x] ^ D[x] for y in range(5) for x in range(5)]
        Bl = [0] * 25
        for x in range(5):
            for y in range(5):
                Bl[5 * ((2 * x + 3 * y) % 5) + y] = rotl(A[5 * y + x], RHO[x][y])
        lanes = [Bl[5 * y + x] ^ ((~Bl[5 * y + (x + 1) % 5]) & Bl[5 * y + (x + 2) % 5]) & M
                 for y in range(5) for x in range(5)]
        lanes[0] ^= RC[ir]
    return lanes

z = keccakf_ref([0] * 25)
assert z[0] == 0xF1258F7940E1DDE7 and z[1] == 0x84D5CCF933C0478A  # XKCP anchor

RATE = 136  # bytes, Keccak-256 (capacity 512)

def keccak256(msg: bytes):
    """Single-block Keccak-256 (len <= RATE-1). Returns (digest_bytes,
    init_lanes, out_lanes)."""
    assert len(msg) <= RATE - 1, "single-block smoke only"
    block = bytearray(RATE)
    block[:len(msg)] = msg
    block[len(msg)] ^= 0x01          # Keccak (pre-NIST) pad10*1
    block[RATE - 1] ^= 0x80
    lanes = [int.from_bytes(block[8 * i:8 * i + 8], "little") for i in range(17)]
    lanes += [0] * 8
    out = keccakf_ref(lanes)
    digest = b"".join(out[i].to_bytes(8, "little") for i in range(4))
    return digest, lanes, out

# ---- anchor the SPONGE mapping (byte->lane, padding) on keccak256("") ----
d_empty, _, _ = keccak256(b"")
assert d_empty.hex() == ("c5d2460186f7233c927e7db2dcc703c0"
                         "e500b653ca82273b7bfad8045d85a470"), d_empty.hex()
print(f"anchor OK: keccak256(\"\") = {d_empty.hex()}")

def flat(lanes, n=25):
    v = 0
    for i in range(n):
        v |= lanes[i] << (i * W)
    return v

# ---- test vectors ----
# 1. empty message (msgbits=0: the whole init state is public -> exercises
#    pure share-0 constant injection; digest is the canonical empty digest).
# 2. Solidity mapping-slot address: keccak256(key ‖ slot_index), key = an
#    address-like word, slot_index = 3. EVM words serialize BIG-endian.
# 3. random 64-byte message (two random words).
_rnd.seed(0xDEC0DE)
key_w = 0x000000000000000000000000DEADBEEF00C0FFEE00BA5E00CAFE0000FEED0001
slot_w = 3
w1, w2 = _rnd.getrandbits(256), _rnd.getrandbits(256)
vecs = [
    (b"", "empty message  (canonical c5d24601... digest)"),
    (key_w.to_bytes(32, "big") + slot_w.to_bytes(32, "big"),
     "mapping slot: keccak256(key || slot=3), EVM big-endian words"),
    (w1.to_bytes(32, "big") + w2.to_bytes(32, "big"), "random 64-byte message"),
]

checks = []
for msg, note in vecs:
    digest, lanes_in, out = keccak256(msg)
    print(f"vector: {note}\n  keccak256 = {digest.hex()}")
    checks.append(
        f"    // {note}\n"
        f"    // canonical digest: {digest.hex()}\n"
        f"    check({B}'h{flat(lanes_in):0{B//4}x},\n"
        f"          256'h{flat(out,4):064x}, {8*len(msg)});")
checks = "\n".join(checks)

smoke = f"""// Functional smoke test for the KECCAK256 SPONGE COMPOSITION over the
// verified keccakf1600 round unit (NOT a security check — the unit's MATCHI
// matrix is RESULT_KECCAKF1600.md; this tb adds ZERO gadgets and ZERO RTL).
// Message bits enter as a 2-share sharing; pad10*1 + capacity zeros are
// public constants XORed into SHARE 0 ONLY (share 1 stays 0 there) — the
// share-local rate/padding XOR of SWAP_DATAPATH.md. One permutation;
// digest = recombined lanes 0..3. Reference digests are spec-derived and
// double-anchored (XKCP zero-state + canonical keccak256("")).
// Generated by gen_keccak256_smoke.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [{2*B-1}:0] a;
reg [1599:0] rr, ss;
wire [{2*B-1}:0] o;

keccakf1600 dut (.clk(clk), .rst(rst), .go(go), .a(a),
          .r(rr[1599:0]), .s(ss[1599:0]), .o(o));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 50; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [{B-1}:0] am;
reg [255:0] got;
integer j;
task check(input [{B-1}:0] x, input [255:0] expd, input integer msgbits);
    begin
        // mask ONLY the message region: those bits arrive as a real sharing;
        // padding + capacity are public -> share 0 carries the constant,
        // share 1 is 0 there (share-local injection, no gadgets).
        for (j = 0; j < 50; j = j + 1) am[j*32 +: 32] = $random;
        for (j = 0; j < {B}; j = j + 1) begin
            if (j < msgbits) begin
                a[2*j] = x[j] ^ am[j];  a[2*j+1] = am[j];
            end else begin
                a[2*j] = x[j];          a[2*j+1] = 1'b0;
            end
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat (151) @(negedge clk);
        for (j = 0; j < 256; j = j + 1) got[j] = o[2*j] ^ o[2*j+1];
        if (got !== expd) begin
            errors = errors + 1;
            $display("FAIL msgbits=%0d", msgbits);
            $display("  got=%h", got);
            $display("  exp=%h", expd);
        end else begin
            $display("PASS digest(flat lanes 0..3)=%h msgbits=%0d", got, msgbits);
        end
        repeat (30) @(negedge clk);   // past clr before the next check
    end
endtask

initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
{checks}
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
"""
with open("tb_smoke_keccak256.v", "w") as f:
    f.write(smoke)
print("wrote tb_smoke_keccak256.v")
