#!/usr/bin/env python3
"""Emit the 256-bit masked EQ tops — EQ(A,B) = ISZERO(A ^ B), the composition
noted (not built) in RESULT_ISZERO256.md, now materialized: a share-local XOR
stage (d0 = a0^b0, d1 = a1^b1 — combines matching shares of two DIFFERENT
sharings, never two shares of one secret; zero gadgets) feeding the VERIFIED
gen_iszero256.py OR-reduction tree verbatim (255 O-PINI2 gadgets, De Morgan
OR, per-gadget ina balance registers). out recombines to (A == B).

Same activity schedule as iszero256 (E=32 streamed executions; the XOR stage
adds zero gadget levels, so all window constants carry over unchanged).
Emits: eq256.v (OPINI target), eq256_pini.v (label control, single-pass =>
EXPECTED PASS, recorded not counted — same as iszero256_pini), eq256_rndreuse.v
(NEG, must FAIL: gadget 1 reuses gadget 0's r/s), eq256_recomb.v (NEG, must
FAIL: register recombining out[0]^out[1]); tb_eq256.v; tb_smoke_eq256.v.
Generated by gen_eq256.py; do not hand-edit — regenerate instead.
"""

N = 256
LEVELS = 8
NGAD = N - 1
GADGET = "MSKand_opini2_d2"

E = 32
A_HI = E + 8          # 40  a/b sensitive [0,40] (level-0 inb@e U ina@e+1 + margin)
R_HI = E + 36         # 68
S_HI = E + 37         # 69
OUT_HI = E + 40       # 72


def header(modname, comment, recomb=False):
    ep = ", leak_o" if recomb else ""
    lk = '\n(* matchi_type = "sharing", matchi_active = "out_act" *) output [1:0] leak_o;' if recomb else ""
    return f"""{comment}
(* matchi_prop = "PINI", matchi_strat = "composite_top", matchi_arch = "loopy", matchi_shares = 2 *)
module {modname} (clk, rst, go, a, b, r, s, out{ep});
(* matchi_type = "clock" *)   input clk;
(* matchi_type = "control" *) input rst;
(* matchi_type = "control" *) input go;
(* matchi_type = "sharings_dense", matchi_active = "a_act" *) input [{2*N-1}:0] a;
(* matchi_type = "sharings_dense", matchi_active = "b_act" *) input [{2*N-1}:0] b;
(* matchi_type = "random", matchi_active = "r_act" *) input [{N-1}:0] r;
(* matchi_type = "random", matchi_active = "s_act" *) input [{N-1}:0] s;
(* matchi_type = "sharing", matchi_active = "out_act" *) output [1:0] out;{lk}

// ---- activity shift register (single go-pulse propagated; E={E} overlapped execs) ----
(* keep *) wire act0 = go;
(* keep *) reg [{OUT_HI}:1] actr;
always @(posedge clk) begin
    if (rst) actr <= {OUT_HI}'b0;
    else     actr <= {{actr[{OUT_HI-1}:1], act0}};
end
wire [{OUT_HI}:0] act = {{actr, act0}};
(* keep *) wire a_act   = |act[{A_HI}:0];
(* keep *) wire b_act   = |act[{A_HI}:0];
(* keep *) wire r_act   = |act[{R_HI}:0];
(* keep *) wire s_act   = |act[{S_HI}:1];
(* keep *) wire out_act = |act[{OUT_HI}:0];

// ---- EQ input stage: d = A XOR B, SHARE-LOCAL (d_s = a_s ^ b_s for each
// share s — matching shares of two different sharings; never two shares of
// the same secret; zero gadgets). d == 0 iff A == B. ----
"""


def xor_body():
    L = []
    for j in range(N):
        L.append(f"wire d0_{j} = a[{2*j}] ^ b[{2*j}];  "
                 f"wire d1_{j} = a[{2*j+1}] ^ b[{2*j+1}];")
    return "\n".join(L)


def tree_body(leaf, rndreuse=False):
    """Verbatim gen_iszero256.py OR-reduction tree, fed by the d XOR stage."""
    L = []
    o = L.append
    cur = [(f"d0_{j}", f"d1_{j}") for j in range(N)]
    k = 0
    for lvl in range(LEVELS):
        o(f"\n// ===== OR-reduce level {lvl}: {len(cur)} masked bits -> {len(cur)//2} =====")
        nxt = []
        for m in range(len(cur) // 2):
            (x0, x1) = cur[2 * m]
            (y0, y1) = cur[2 * m + 1]
            if rndreuse and k == 1:
                rk, sk = "r[0]", "s[0]"
                note = "  // BUG UNDER TEST: reuses gadget 0's randomness r[0]/s[0]"
            else:
                rk, sk = f"r[{k}]", f"s[{k}]"
                note = ""
            o(f"""wire nx0_{k} = {x0} ^ 1'b1;   // NOT childA, share-local (share 0)
wire ny0_{k} = {y0} ^ 1'b1;   // NOT childB, share-local (share 0)
// 1-cycle balance reg on the ina path (share-local, per-share): presents ina
// one cycle after inb, matching the gadget's ina@1 / inb@0 latency contract.
(* keep = "yes" *) reg ina0_{k}, ina1_{k};
always @(posedge clk) begin
    ina0_{k} <= nx0_{k};
    ina1_{k} <= {x1};
end
wire w0_{k}, w1_{k};
{leaf} u_or_{k} ({note}
    .ina({{ina1_{k}, ina0_{k}}}), .inb({{{y1}, ny0_{k}}}),
    .rnd({rk}), .s({sk}), .clk(clk), .out({{w1_{k}, w0_{k}}}));
wire or0_{k} = w0_{k} ^ 1'b1;   // OR = NOT(AND(..)), share-local (share 0)
wire or1_{k} = w1_{k};""")
            nxt.append((f"or0_{k}", f"or1_{k}"))
            k += 1
        cur = nxt
    assert len(cur) == 1 and k == NGAD
    return "\n".join(L), cur[0]


def build(modname, leaf, comment, rndreuse=False, recomb=False):
    body, (f0, f1) = tree_body(leaf, rndreuse=rndreuse)
    parts = [header(modname, comment, recomb=recomb), xor_body(), body]
    parts.append(f"""
// ---- EQ = ISZERO(A^B) = NOT( OR-reduce(d) ) : share-local complement ----
assign out[0] = {f0} ^ 1'b1;
assign out[1] = {f1};""")
    if recomb:
        parts.append("""
// BUG UNDER TEST: recombine the two shares of the EQ output. leak0 holds
// out[0]^out[1] (both shares) -> its input XOR gate is sensitive in
// ShareSet{0} AND ShareSet{1} -> MATCHI glitch leakage.
(* keep = "yes" *) reg leak0, leak1;
always @(posedge clk) begin
    leak0 <= out[0] ^ out[1];
    leak1 <= 1'b0;
end
assign leak_o = {leak1, leak0};""")
    parts.append("\nendmodule\n")
    return "\n".join(parts)


def emit(fn, text, leaf, expect_count):
    n = text.count(leaf + " u_")
    assert n == expect_count, f"{fn}: leaf {leaf} x{n}, expected {expect_count}"
    with open(fn, "w") as f:
        f.write(text)
    print(f"wrote {fn}: {n} {leaf} instances")


C_MAIN = ("// 256-bit masked EQ — EQ(A,B) = ISZERO(A ^ B): share-local XOR stage (zero\n"
          "// gadgets) + the verified iszero256 OR-reduction tree (255 O-PINI2 leaves).\n"
          "// VERIFIED TARGET. out recombines to 1 iff A == B. Materializes the\n"
          "// composition noted in RESULT_ISZERO256.md.")
C_PINI = ("// LABEL CONTROL (EXPECTED PASS, single-pass): identical to eq256 but\n"
          "// instantiates the PINI-relabelled leaf MSKand_opini2_d2_pini. Single-pass\n"
          "// => PINI composition already suffices => PASS. Recorded, NOT counted as\n"
          "// non-vacuity (same reasoning as iszero256_pini).")
C_RND = ("// NEGATIVE CONTROL (must FAIL): identical to eq256 except gadget 1 consumes\n"
         "// r[0]/s[0] — the SAME random bits as gadget 0 (both at level 0, same\n"
         "// cycle) — instead of its dedicated r[1]/s[1]. MATCHI must report multi-use.")
C_RCB = ("// NEGATIVE CONTROL (must FAIL): identical to eq256 plus one share-recombining\n"
         "// register (leak <= out[0] ^ out[1]). MATCHI must flag the gate sensitive in\n"
         "// multiple shares (glitch leakage).")

emit("eq256.v", build("eq256", GADGET, C_MAIN), GADGET, NGAD)
emit("eq256_pini.v", build("eq256_pini", GADGET + "_pini", C_PINI),
     GADGET + "_pini", NGAD)
emit("eq256_rndreuse.v", build("eq256_rndreuse", GADGET, C_RND, rndreuse=True),
     GADGET, NGAD)
emit("eq256_recomb.v", build("eq256_recomb", GADGET, C_RCB, recomb=True),
     GADGET, NGAD)

# ---------------- MATCHI testbench ----------------
tb = f"""// MATCHI testbench for the 256-bit EQ tops. Same convention as
// tb_iszero256.v: values are irrelevant to MATCHI (symbolic); only
// signal-activity timing is read from the VCD. Inputs re-randomized every
// cycle. Run long enough to cover the deepest activity window (out [0,{OUT_HI}]).
// Generated by gen_eq256.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD eq256
`endif
module tb ();
parameter HP = 5;
reg clk, rst, go;
reg [511:0] a, b;
reg [255:0] r, s;
wire [1:0] out;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .go(go),
             .a(a), .b(b), .r(r), .s(s), .out(out)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < 16; w = w + 1) begin
            a[w*32 +: 32] = $random;
            b[w*32 +: 32] = $random;
        end
        for (w = 0; w < 8;  w = w + 1) begin
            r[w*32 +: 32] = $random;
            s[w*32 +: 32] = $random;
        end
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; go = 1'b0;
    a = 512'h0; b = 512'h0; r = 256'h0; s = 256'h0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // cycle 0: one-cycle go pulse
    @(negedge clk); go = 1'b1; randfill;
    @(negedge clk); go = 1'b0; randfill;
    for (i = 0; i < 160; i = i + 1) begin
        @(negedge clk); randfill;
    end
    $finish;
end
endmodule
"""
with open("tb_eq256.v", "w") as f:
    f.write(tb)
print("wrote tb_eq256.v")

# ---------------- functional smoke testbench ----------------
smoke = """// Functional smoke test for eq256 (NOT a security check — MATCHI is the
// separate verification step). Shares both 256-bit operands with independent
// random masks, holds the inputs steady, waits out the XOR stage + 8-level
// tree, recombines the EQ output shares, compares against (x == y).
// Fresh gadget randoms every cycle.
// Generated by gen_eq256.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [511:0] a, b;
reg [255:0] r, s;
wire [1:0] out;

eq256 dut (.clk(clk), .rst(rst), .go(go), .a(a), .b(b), .r(r), .s(s), .out(out));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 8; k = k + 1) begin
        r[k*32 +: 32] = $random;
        s[k*32 +: 32] = $random;
    end
end

reg [255:0] am, bm;
reg got, expd;
integer j;
task check(input [255:0] x, input [255:0] y);
    begin
        for (j = 0; j < 8; j = j + 1) begin
            am[j*32 +: 32] = $random;
            bm[j*32 +: 32] = $random;
        end
        for (j = 0; j < 256; j = j + 1) begin
            a[2*j]   = x[j] ^ am[j];
            a[2*j+1] = am[j];
            b[2*j]   = y[j] ^ bm[j];
            b[2*j+1] = bm[j];
        end
        repeat (200) @(negedge clk);   // >> tree depth (~24 cycles)
        got  = out[0] ^ out[1];
        expd = (x == y) ? 1'b1 : 1'b0;
        if (got !== expd) begin
            errors = errors + 1;
            $display("FAIL  x=%h y=%h got=%b exp=%b", x, y, got, expd);
        end else begin
            $display("PASS  eq=%b", got);
        end
    end
endtask

reg [255:0] xv;
initial begin
    errors = 0;
    #40 rst = 0;
    check(256'h0, 256'h0);                                     // 0 == 0 -> 1
    check(256'h1, 256'h0);                                     // differ in LSB -> 0
    for (j = 0; j < 8; j = j + 1) xv[j*32 +: 32] = $random;
    check(xv, xv);                                             // x == x -> 1
    check(xv, xv ^ (256'h1 << 255));                           // differ in MSB -> 0
    check(xv, ~xv);                                            // complement -> 0
    check({256{1'b1}}, {256{1'b1}});                           // max == max -> 1
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
"""
with open("tb_smoke_eq256.v", "w") as f:
    f.write(smoke)
print("wrote tb_smoke_eq256.v")

print(f"E={E} A_HI={A_HI} R_HI={R_HI} S_HI={S_HI} OUT_HI={OUT_HI}")
