#!/usr/bin/env python3
"""Emit the 256-bit masked DIV/MOD tops (EVM DIV: q = A / B, EVM MOD:
rem = A % B, for B != 0) — ITERATIVE RESTORING DIVISION over the
MATCHI-passed O-PINI2 gadget (MSKand_opini2_d2, byte-identical leaf from
./, read-only reference). The per-iteration subtractor is a
verbatim structural copy of the verified 256-bit adder dataflow
(top_add256_opini2 with sub=1: b complemented share-locally, carry-in = public
1, carry-out = NOT borrow); the conditional select reuses the broadcast-AND
pattern MATCHI-verified in mul256's PP gating.

Design record:
  * Restoring division, MSB first. State: R (remainder, N bits), A (dividend,
    shifts left), Q (quotient, shifts left), Bn (share-local ~B). Invariant at
    iteration i: R < B and Q holds the top i quotient bits.
  * Per iteration: Rsh = {R, msb(A)} ((N+1)-bit R<<1|bit); T = Rsh - B via the
    (N+1)-bit ripple subtract (2(N+1) gadgets, gadget latency chain settles in
    ~2(N+1)+4 cycles); cout = NOT borrow = (Rsh >= B) is the quotient bit;
    R'   = cout ? T : Rsh = Rsh ^ (cout AND (Rsh^T))  (N broadcast gadgets).
    Both R' branches are < B <= 2^N-1, so R stays N bits (T[N] not needed).
  * Gadget budget 3N+2 = 2(N+1) subtract + N mux, instantiated ONCE and reused
    bubble-free across all N iterations with genuine feedback (the subtractor
    consumes the mux's previous output) — the OPINI regime, same as mul256.
  * Iteration period K = 2N+16: ripple settles by offset 2N+6, T/cout are
    registered at the edge into offset M1 = 2N+8, the mux gadgets execute with
    a consistent inb@e (coutreg) / ina@e+1 (xm_d = delayed Rsh^Treg) pair from
    e = M1+1, mux out is stable during M1+4.., and R/Q/A update at the edge
    ending offset K-1 = M1+7. Total ~ N*K + margin cycles.
  * MOD FOR FREE: after the last iteration R is A % B; exposed as rem.
  * EVM B == 0 semantics (DIV=0, MOD=0) are NOT inside this unit (here B=0
    yields q = 2^N-1, rem = shifted A). Full EVM compliance is the verified
    composition ISZERO(B) -> z; gate q/rem with (NOT z) via the same
    broadcast-AND pattern verified here and in mul256. Precondition B != 0 is
    also guaranteed on the DEX path (divisor = reserve + amountIn > 0).

Activity-window generation (differs from mul/iszero, honestly flagged): those
tops tapped a go-shift-register (length ~ run time). Here the deepest window is
~2N^2 cycles — a 135k-bit shift register would dominate yosys time and VCD
size — so the windows come from an idempotent cycle counter (public control,
like the FSM counters) + comparators. Same waveforms for a single go pulse.
The N=16 pilot validates this flow change against the full matrix before the
N=256 runs.

Gadget latency contract (inb@0, rnd@0, ina@1, s@1, out@3): every gadget ina is
either a 1-cycle per-share balance register (Rsh_d, xm_d — the iszero256
pattern) or the naturally-late ripple carry (fc, the verified-adder pattern).

State-register sensitivity is BOUNDED IN TIME (mul256 pattern): clr zeroes
R/A/Q/Bn/Treg/coutreg after the output window; the unconditional delay
registers drain one cycle later; r/s stay fresh until non-sensitivity has
rippled down the subtract carry chain (~2N tail).

Emits (suffix = N): div{N}.v (OPINI target), div{N}_pini.v (label control),
div{N}_rndreuse.v (NEG control, must FAIL: u_m_1 reuses u_m_0's r/s),
div{N}_recomb.v (NEG control, must FAIL: register recombining q[0]^q[1]);
tb_div{N}.v (MATCHI tb); tb_smoke_div{N}.v (functional).
Generated by gen_div256.py; do not hand-edit — regenerate instead.
Usage: gen_div256.py [N]   (default 256)
"""
import sys

N = int(sys.argv[1]) if len(sys.argv) > 1 else 256
GADGET = "MSKand_opini2_d2"
NG = 3 * N + 2                  # 2(N+1) subtract + N mux gadget instances
ITW = max(2, (N - 1).bit_length() + 1)   # iteration counter width

# ---- schedule constants (cycle 0 = go; registers load at edge into cycle 1) ----
M1 = 2 * N + 8                  # T/cout registered at edge into this offset
K = M1 + 8                      # iteration period (= 2N+16)
OUT_STABLE = K * N + 1          # q/rem (registers) stable from here
CLR_AT = K * N + 16             # state registers cleared at this count
OUT_HI = CLR_AT + 2 * N + 20    # conservative tail while the subtract chain
                                # drains non-sensitivity at ~2 cycles/bit
R_HI = OUT_HI + 2               # randoms fresh through the whole drain
S_HI = R_HI + 1                 # s latency 1
CNTW = max(ITW + 6, (S_HI + 2).bit_length() + 1)   # cycle counter width
TB_CYC = S_HI + 30              # MATCHI tb run length after go
SMOKE_SAMPLE = CLR_AT - 5       # smoke: sample q/rem here (stable, before clr)
SMOKE_GAP = 60                  # smoke: extra cycles after sample


def share_concat(port, share, n=N):
    """Dense sharing unpack: {port[2*(n-1)+share], ..., port[share]}."""
    return "{" + ", ".join(f"{port}[{2*j+share}]" for j in range(n - 1, -1, -1)) + "}"


def header(modname, leaf, comment, recomb=False):
    ep = ", leak_o" if recomb else ""
    lk = ('\n(* matchi_type = "sharing", matchi_active = "out_act" *) '
          "output [1:0] leak_o;") if recomb else ""
    return f"""{comment}
// Iterative restoring divider, q = A/B, rem = A%B (B != 0). {NG} assumed-OPINI
// gadget leaves ({2*(N+1)} subtract u_g_*/u_t_* — the verified-adder dataflow
// with sub=1 — plus {N} borrow-mux u_m_*), each with a DEDICATED r[k]/s[k]
// random bit. Every XOR/NOT/shift is strictly share-local.
// Dense sharing layout (share index fastest): port[2i]=share0, port[2i+1]=share1.
// Schedule: load @0; iteration i occupies cycles [1+{K}i, {K}+{K}i]; q/rem
// (registers) stable from cycle {OUT_STABLE}; state cleared (share-local, to
// public 0) at cycle {CLR_AT}; randoms fresh [0,{R_HI}].
(* matchi_prop = "PINI", matchi_strat = "composite_top", matchi_arch = "loopy", matchi_shares = 2 *)
module {modname} (clk, rst, go, a, b, r, s, q, rem{ep});
(* matchi_type = "clock" *)   input clk;
(* matchi_type = "control" *) input rst;
(* matchi_type = "control" *) input go;
(* matchi_type = "sharings_dense", matchi_active = "a_act" *) input [{2*N-1}:0] a;
(* matchi_type = "sharings_dense", matchi_active = "b_act" *) input [{2*N-1}:0] b;
(* matchi_type = "random", matchi_active = "r_act" *) input [{NG-1}:0] r;
(* matchi_type = "random", matchi_active = "s_act" *) input [{NG-1}:0] s;
(* matchi_type = "sharings_dense", matchi_active = "out_act" *) output [{2*N-1}:0] q;
(* matchi_type = "sharings_dense", matchi_active = "out_act" *) output [{2*N-1}:0] rem;{lk}

// ---- activity windows from an idempotent cycle counter (public control;
// counts 1.. from the go pulse, saturates — see generator header) ----
reg [{CNTW-1}:0] cnt;
always @(posedge clk) begin
    if (rst)                       cnt <= {CNTW}'d0;
    else if (go)                   cnt <= {CNTW}'d1;
    else if (cnt != {CNTW}'d0 && cnt != {CNTW}'d{S_HI + 2}) cnt <= cnt + {CNTW}'d1;
end
(* keep *) wire a_act   = go || (cnt == {CNTW}'d1);   // operands consumed at load
(* keep *) wire b_act   = go || (cnt == {CNTW}'d1);
(* keep *) wire r_act   = go || (cnt >= {CNTW}'d1 && cnt <= {CNTW}'d{R_HI});
(* keep *) wire s_act   =       (cnt >= {CNTW}'d1 && cnt <= {CNTW}'d{S_HI});
(* keep *) wire out_act = go || (cnt >= {CNTW}'d1 && cnt <= {CNTW}'d{OUT_HI});
(* keep *) wire clr     = (cnt == {CNTW}'d{CLR_AT});  // bounded sensitivity

// ---- public FSM: iteration counter + phase (control only, data-independent) ----
reg running;
reg [{ITW-1}:0] it;
reg [{(K-1).bit_length()-1}:0] ph;
always @(posedge clk) begin
    if (rst) begin running <= 1'b0; it <= 0; ph <= 0; end
    else if (go) begin running <= 1'b1; it <= 0; ph <= 0; end
    else if (running) begin
        if (ph == {K-1}) begin
            ph <= 0;
            if (it == {ITW}'d{N-1}) begin running <= 1'b0; it <= 0; end
            else it <= it + {ITW}'d1;
        end else ph <= ph + 1'b1;
    end
end

// ---- state registers (per-share; NEVER mix share 0 and share 1) ----
reg [{N-1}:0] R0, R1;            // partial remainder
reg [{N-1}:0] A0, A1;            // dividend, shifts left (public 0 in)
reg [{N-1}:0] Q0, Q1;            // quotient, shifts left (cout in)
reg [{N-1}:0] Bn0, Bn1;          // ~B, complement share-local (share 0 only)
reg [{N-1}:0] Treg0, Treg1;      // registered subtract result (settled)
reg coutr0, coutr1;              // registered carry-out = quotient bit
wire [{N}:0] Rsh0 = {{R0, A0[{N-1}]}};   // Rsh = R<<1 | msb(A), per share
wire [{N}:0] Rsh1 = {{R1, A1[{N-1}]}};
wire [{N-1}:0] w_m0, w_m1;       // borrow-mux gadget outputs
// (* keep *): T/coutw feed only register inputs; without keep, abc absorbs
// their XOR drivers into the register cone and MATCHI hits a driverless wire.
(* keep *) wire [{N-1}:0] T0, T1;   // subtract difference bits (settled by M1)
(* keep *) wire coutw0, coutw1;     // subtract carry-out = NOT borrow

always @(posedge clk) begin
    if (rst || clr) begin
        R0 <= 0; R1 <= 0; A0 <= 0; A1 <= 0; Q0 <= 0; Q1 <= 0;
        Bn0 <= 0; Bn1 <= 0; Treg0 <= 0; Treg1 <= 0; coutr0 <= 0; coutr1 <= 0;
    end else if (go) begin        // dense-share unpack, share-local
        A0 <= {share_concat('a', 0)};
        A1 <= {share_concat('a', 1)};
        Bn0 <= ~{share_concat('b', 0)};   // share-local NOT: complement share 0
        Bn1 <= {share_concat('b', 1)};    // share 1 untouched
        R0 <= 0; R1 <= 0; Q0 <= 0; Q1 <= 0;
        Treg0 <= 0; Treg1 <= 0; coutr0 <= 0; coutr1 <= 0;
    end else if (running) begin
        if (ph == {M1-1}) begin   // subtract ripple settled: capture T, cout
            Treg0 <= T0; Treg1 <= T1;
            coutr0 <= coutw0; coutr1 <= coutw1;
        end
        if (ph == {K-1}) begin    // iteration update (all share-local)
            R0 <= Rsh0[{N-1}:0] ^ w_m0;   // R' = cout ? T : Rsh
            R1 <= Rsh1[{N-1}:0] ^ w_m1;
            Q0 <= {{Q0[{N-2}:0], coutr0}};   // quotient bit, MSB first
            Q1 <= {{Q1[{N-2}:0], coutr1}};
            A0 <= {{A0[{N-2}:0], 1'b0}};     // A <<= 1 (per-share)
            A1 <= {{A1[{N-2}:0], 1'b0}};
        end
    end
end

// ---- 1-cycle per-share balance registers: every gadget ina arrives one
// cycle after its inb (gadget contract ina@1/inb@0 — the iszero256 pattern).
// Unconditional, so they drain by themselves one cycle after clr.
reg [{N}:0] Rsh_d0, Rsh_d1;      // ina of u_g_*  (inb = Bn)
reg [{N-1}:0] xm_d0, xm_d1;      // ina of u_m_*  (inb = coutr); xm = Rsh^Treg
always @(posedge clk) begin
    Rsh_d0 <= Rsh0;                       Rsh_d1 <= Rsh1;
    xm_d0  <= Rsh0[{N-1}:0] ^ Treg0;      xm_d1  <= Rsh1[{N-1}:0] ^ Treg1;
end

// ---- outputs: dense re-pack of the Q/R registers (share-local wiring) ----
"""


def outputs_body():
    L = []
    for j in range(N):
        L.append(f"assign q[{2*j}] = Q0[{j}];  assign q[{2*j+1}] = Q1[{j}];  "
                 f"assign rem[{2*j}] = R0[{j}];  assign rem[{2*j+1}] = R1[{j}];")
    return "\n".join(L)


def sub_body(leaf):
    """(N+1)-bit ripple subtract T = Rsh - B = Rsh + Bn + 1 — verbatim
    verified-adder dataflow (top_add256_opini2 bit slice with a := Rsh_d,
    b := Bn extended by public 0 -> Bn[N] = public 1, carry-in fc[0] = public
    1 = sub). cout = carry out of bit N = NOT borrow = (Rsh >= B) = the
    quotient bit, kept as standalone (* keep *) scalars (no fc[N+1] vector bit
    for abc to strand — the mul256 fct0/fct1 pattern)."""
    L = []
    o = L.append
    o(f"""
// ===== (N+1)-bit ripple subtract: T = Rsh + ~B + 1 (verified-adder dataflow, sub=1) =====
// fc[0] = carry-in = public 1 (share pair (1,0)); Bn bit {N} = ~0 = public 1.
wire [{N}:0] fc0, fc1;
assign fc0[0] = 1'b1;
assign fc1[0] = 1'b0;""")
    for j in range(N + 1):
        b0 = f"Bn0[{j}]" if j < N else "1'b1"   # Bn[N] = ~(B[N]=0) = public 1
        b1 = f"Bn1[{j}]" if j < N else "1'b0"
        cl0, cl1 = (f"assign fc0[{j+1}]", f"assign fc1[{j+1}]") if j < N else \
                   ("assign coutw0", "assign coutw1")
        o(f"""wire p0_{j} = Rsh_d0[{j}] ^ {b0};
wire p1_{j} = Rsh_d1[{j}] ^ {b1};
wire g0_{j}, g1_{j}, t0_{j}, t1_{j};
{leaf} u_g_{j} (
    .ina({{Rsh_d1[{j}], Rsh_d0[{j}]}}), .inb({{{b1}, {b0}}}),
    .rnd(r[{2*j}]), .s(s[{2*j}]), .clk(clk), .out({{g1_{j}, g0_{j}}}));
{leaf} u_t_{j} (
    .ina({{fc1[{j}], fc0[{j}]}}), .inb({{p1_{j}, p0_{j}}}),
    .rnd(r[{2*j+1}]), .s(s[{2*j+1}]), .clk(clk), .out({{t1_{j}, t0_{j}}}));
{cl0} = g0_{j} ^ t0_{j};
{cl1} = g1_{j} ^ t1_{j};""")
    o(f"// difference bits (only [{N-1}:0] needed: both R' branches are < B < 2^{N})")
    for j in range(N):
        o(f"assign T0[{j}] = p0_{j} ^ fc0[{j}];  assign T1[{j}] = p1_{j} ^ fc1[{j}];")
    return "\n".join(L)


def mux_body(leaf, rndreuse=False):
    """Borrow-mux R' = Rsh ^ (cout AND (Rsh^Treg)): broadcast-AND, the mul256
    PP-gating pattern (inb = broadcast coutr, ina = delayed xm)."""
    L = []
    o = L.append
    base = 2 * (N + 1)
    o(f"\n// ===== borrow-mux: w_m[j] = coutr AND xm[j]  (coutr broadcast to both shares) =====")
    for j in range(N):
        if rndreuse and j == 1:
            rk, sk = f"r[{base}]", f"s[{base}]"
            note = "  // BUG UNDER TEST: reuses u_m_0's randomness"
        else:
            rk, sk = f"r[{base+j}]", f"s[{base+j}]"
            note = ""
        o(f"""{leaf} u_m_{j} ({note}
    .ina({{xm_d1[{j}], xm_d0[{j}]}}), .inb({{coutr1, coutr0}}),
    .rnd({rk}), .s({sk}), .clk(clk), .out({{w_m1[{j}], w_m0[{j}]}}));""")
    return "\n".join(L)


def build(modname, leaf, comment, rndreuse=False, recomb=False):
    parts = [header(modname, leaf, comment, recomb=recomb),
             outputs_body(),
             sub_body(leaf),
             mux_body(leaf, rndreuse=rndreuse)]
    if recomb:
        parts.append("""
// BUG UNDER TEST: recombine the two shares of q bit 0. leak0 holds
// q[0]^q[1] (both shares) -> the XOR gate is sensitive in ShareSet{0}
// AND ShareSet{1} -> MATCHI glitch leakage. Driven onto share 0 of leak_o.
(* keep = "yes" *) reg leak0, leak1;
always @(posedge clk) begin
    leak0 <= q[0] ^ q[1];
    leak1 <= 1'b0;
end
assign leak_o = {leak1, leak0};""")
    parts.append("\nendmodule\n")
    return "\n".join(parts)


def emit(fn, text, leaf, expect_count):
    n = text.count(leaf + " u_")
    assert n == expect_count, f"{fn}: leaf {leaf} x{n}, expected {expect_count}"
    with open(fn, "w") as f:
        f.write(text)
    print(f"wrote {fn}: {n} {leaf} instances")


C_MAIN = (f"// {N}-bit masked DIV/MOD (EVM, B != 0: q = A/B, rem = A%B) — iterative\n"
          f"// restoring divider over {NG} O-PINI2 masked-AND leaves. VERIFIED TARGET.\n"
          "// Bubble-free gadget reuse across all iterations with genuine feedback\n"
          "// (the subtractor consumes the mux's previous output) — the OPINI regime.")
C_PINI = ("// LABEL CONTROL: identical netlist but instantiates the PINI-relabelled\n"
          "// leaf MSKand_opini2_d2_pini. This datapath REUSES gadgets bubble-free\n"
          "// with feedback, the structure MATCHI's transition rule guards for PINI\n"
          "// leaves (cf. ./top_chain_pini). Verdict recorded either way.")
C_RND = ("// NEGATIVE CONTROL (must FAIL): identical to the target except u_m_1\n"
         "// consumes the SAME random bits as u_m_0, active in the same cycles,\n"
         "// instead of its dedicated pair. MATCHI must report multi-use.")
C_RCB = ("// NEGATIVE CONTROL (must FAIL): identical to the target plus one share-\n"
         "// recombining register (leak0 <= q[0]^q[1]). MATCHI must flag the\n"
         "// gate sensitive in multiple shares (glitch leakage).")

emit(f"div{N}.v", build(f"div{N}", GADGET, C_MAIN), GADGET, NG)
emit(f"div{N}_pini.v", build(f"div{N}_pini", GADGET + "_pini", C_PINI),
     GADGET + "_pini", NG)
emit(f"div{N}_rndreuse.v", build(f"div{N}_rndreuse", GADGET, C_RND, rndreuse=True),
     GADGET, NG)
emit(f"div{N}_recomb.v", build(f"div{N}_recomb", GADGET, C_RCB, recomb=True),
     GADGET, NG)

# ---------------- MATCHI testbench ----------------
AB_W = 2 * N
RS_W = NG
AB_WW = (AB_W + 31) // 32
RS_WW = (RS_W + 31) // 32
tb = f"""// MATCHI testbench for the div{N} tops. Same convention as the verified
// adder/iszero/mul tbs: values are irrelevant to MATCHI (symbolic); only
// signal-activity timing is read from the VCD. Inputs re-randomized every
// cycle so the annotated activity windows match physics. Run length covers
// the deepest window (r [0,{R_HI}]) plus margin.
// Generated by gen_div256.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD div{N}
`endif
module tb ();
parameter HP = 5;
reg clk, rst, go;
reg [{AB_WW*32-1}:0] a, b;
reg [{RS_WW*32-1}:0] r, s;
wire [{AB_W-1}:0] q, rem;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .go(go),
             .a(a[{AB_W-1}:0]), .b(b[{AB_W-1}:0]),
             .r(r[{RS_W-1}:0]), .s(s[{RS_W-1}:0]), .q(q), .rem(rem)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < {AB_WW}; w = w + 1) begin
            a[w*32 +: 32] = $random;
            b[w*32 +: 32] = $random;
        end
        for (w = 0; w < {RS_WW}; w = w + 1) begin
            r[w*32 +: 32] = $random;
            s[w*32 +: 32] = $random;
        end
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; go = 1'b0;
    a = 0; b = 0; r = 0; s = 0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // cycle 0: one-cycle go pulse
    @(negedge clk); go = 1'b1; randfill;
    @(negedge clk); go = 1'b0; randfill;
    for (i = 0; i < {TB_CYC}; i = i + 1) begin
        @(negedge clk); randfill;
    end
    $finish;
end
endmodule
"""
with open(f"tb_div{N}.v", "w") as f:
    f.write(tb)
print(f"wrote tb_div{N}.v")

# ---------------- functional smoke testbench ----------------
NW = (N + 31) // 32
smoke = f"""// Functional smoke test for div{N} (NOT a security check — MATCHI is the
// separate verification step). Shares each operand with a random mask, pulses
// go, waits out the {N} restoring iterations, recombines the q/rem shares,
// compares against x/y and x%y. Fresh gadget randoms every cycle (the
// recombined outputs are mask-independent). B != 0 on every vector (EVM B=0
// semantics live in the ISZERO composition, not this unit).
// Generated by gen_div256.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [{2*N-1}:0] a, b;
reg [{RS_WW*32-1}:0] rr, ss;
wire [{2*N-1}:0] q, rem;

div{N} dut (.clk(clk), .rst(rst), .go(go), .a(a), .b(b),
            .r(rr[{RS_W-1}:0]), .s(ss[{RS_W-1}:0]), .q(q), .rem(rem));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < {RS_WW}; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [{N-1}:0] am, bm, gotq, gotr, expq, expr;
integer j;
task check(input [{N-1}:0] x, input [{N-1}:0] y);
    begin
        for (j = 0; j < {NW}; j = j + 1) begin
            am[j*32 +: 32] = $random;
            bm[j*32 +: 32] = $random;
        end
        for (j = 0; j < {N}; j = j + 1) begin
            a[2*j] = x[j] ^ am[j];  a[2*j+1] = am[j];
            b[2*j] = y[j] ^ bm[j];  b[2*j+1] = bm[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat ({SMOKE_SAMPLE}) @(negedge clk);
        for (j = 0; j < {N}; j = j + 1) begin
            gotq[j] = q[2*j] ^ q[2*j+1];
            gotr[j] = rem[2*j] ^ rem[2*j+1];
        end
        expq = x / y;
        expr = x % y;
        if (gotq !== expq || gotr !== expr) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  x   =%h", x);
            $display("  y   =%h", y);
            $display("  gotq=%h expq=%h", gotq, expq);
            $display("  gotr=%h expr=%h", gotr, expr);
        end else begin
            $display("PASS x/y=%h x%%y=%h", gotq, gotr);
        end
        repeat ({SMOKE_GAP}) @(negedge clk);   // past clr before the next check
    end
endtask

reg [{N-1}:0] xv, yv;
initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    check({{{{{N-1}{{1'b0}}}}, 1'b1}}, {{{{{N-1}{{1'b0}}}}, 1'b1}}); // 1 / 1
    for (j = 0; j < {NW}; j = j + 1) xv[j*32 +: 32] = $random;
    check(xv, {{{{{N-1}{{1'b0}}}}, 1'b1}});                     // x / 1 = x, rem 0
    check(xv, xv);                                              // x / x = 1, rem 0
    check({{{{{N-1}{{1'b0}}}}, 1'b1}}, {{{N}{{1'b1}}}});        // 1 / max = 0, rem 1
    check({{{N}{{1'b1}}}}, {{{{{N-2}{{1'b0}}}}, 2'b11}});       // max / 3
    for (j = 0; j < {NW}; j = j + 1) begin
        xv[j*32 +: 32] = $random;
        yv[j*32 +: 32] = $random;
    end
    yv[{N-1}:{N//2}] = 0;                                       // small-ish divisor
    if (yv == 0) yv = 7;
    check(xv, yv);                                              // random / random
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
"""
with open(f"tb_smoke_div{N}.v", "w") as f:
    f.write(smoke)
print(f"wrote tb_smoke_div{N}.v")

print(f"N={N} NG={NG} K={K} M1={M1} OUT_STABLE={OUT_STABLE} OUT_HI={OUT_HI} "
      f"CLR_AT={CLR_AT} R_HI={R_HI} S_HI={S_HI} TB_CYC={TB_CYC}")
