// MATCHI testbench for the divevm16 tops. Same convention as the verified
// adder/iszero/mul/div tbs: values are irrelevant to MATCHI (symbolic); only
// signal-activity timing is read from the VCD. Inputs re-randomized every
// cycle so the annotated activity windows match physics. Run length covers
// the deepest window (r [0,838]) plus margin.
// Generated by gen_divevm.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD divevm16
`endif
module tb ();
parameter HP = 5;
reg clk, rst, go;
reg [31:0] a, b;
reg [127:0] r, s;
wire [31:0] qe, reme;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .go(go),
             .a(a[31:0]), .b(b[31:0]),
             .r(r[96:0]), .s(s[96:0]), .qe(qe), .reme(reme)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < 1; w = w + 1) begin
            a[w*32 +: 32] = $random;
            b[w*32 +: 32] = $random;
        end
        for (w = 0; w < 4; w = w + 1) begin
            r[w*32 +: 32] = $random;
            s[w*32 +: 32] = $random;
        end
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; go = 1'b0;
    a = 0; b = 0; r = 0; s = 0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // cycle 0: one-cycle go pulse
    @(negedge clk); go = 1'b1; randfill;
    @(negedge clk); go = 1'b0; randfill;
    for (i = 0; i < 869; i = i + 1) begin
        @(negedge clk); randfill;
    end
    $finish;
end
endmodule
