// MATCHI testbench for the dexloop256 tops. Same convention as the verified
// swap/store tbs: values are irrelevant to MATCHI (symbolic); only signal-
// activity timing is read from the VCD. Two preload SSTOREs (storage becomes
// sensitive, sticky window), one tx_go, then randfill to $finish — windows
// never close inside the trace (keccak f2e50d60f rule).
// Generated by gen_dexloop.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD dexloop256
`endif
module tb ();
parameter HP = 5;
reg clk, rst, tx_go, we;
reg [1:0] waddr, raddr;
reg [511:0] x, mo, wdata;
reg [3583:0] r, s;
wire [511:0] aout, nri, nro, rdata;
wire [1:0] ok;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .tx_go(tx_go), .we(we), .waddr(waddr),
             .raddr(raddr), .wdata(wdata[511:0]),
             .x(x[511:0]), .mo(mo[511:0]),
             .r(r[3577:0]), .s(s[3577:0]),
             .aout(aout), .nri(nri), .nro(nro), .ok(ok), .rdata(rdata)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < 16; w = w + 1) begin
            x[w*32 +: 32] = $random;
            mo[w*32 +: 32] = $random;
            wdata[w*32 +: 32] = $random;
        end
        for (w = 0; w < 112; w = w + 1) begin
            r[w*32 +: 32] = $random;
            s[w*32 +: 32] = $random;
        end
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; tx_go = 1'b0; we = 1'b0;
    waddr = 0; raddr = 0; x = 0; mo = 0; wdata = 0; r = 0; s = 0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // preload SSTOREs: slot0 (reserveIn), slot1 (reserveOut)
    @(negedge clk); we = 1'b1; waddr = 2'd0; randfill;
    @(negedge clk); waddr = 2'd1; randfill;
    @(negedge clk); we = 1'b0; tx_go = 1'b1; randfill;
    @(negedge clk); tx_go = 1'b0; randfill;
    for (i = 0; i < 138321; i = i + 1) begin
        @(negedge clk); randfill;
    end
    $finish;
end
endmodule
