// MATCHI testbench for the 256-bit EQ tops. Same convention as
// tb_iszero256.v: values are irrelevant to MATCHI (symbolic); only
// signal-activity timing is read from the VCD. Inputs re-randomized every
// cycle. Run long enough to cover the deepest activity window (out [0,72]).
// Generated by gen_eq256.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD eq256
`endif
module tb ();
parameter HP = 5;
reg clk, rst, go;
reg [511:0] a, b;
reg [255:0] r, s;
wire [1:0] out;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .go(go),
             .a(a), .b(b), .r(r), .s(s), .out(out)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < 16; w = w + 1) begin
            a[w*32 +: 32] = $random;
            b[w*32 +: 32] = $random;
        end
        for (w = 0; w < 8;  w = w + 1) begin
            r[w*32 +: 32] = $random;
            s[w*32 +: 32] = $random;
        end
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; go = 1'b0;
    a = 512'h0; b = 512'h0; r = 256'h0; s = 256'h0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // cycle 0: one-cycle go pulse
    @(negedge clk); go = 1'b1; randfill;
    @(negedge clk); go = 1'b0; randfill;
    for (i = 0; i < 160; i = i + 1) begin
        @(negedge clk); randfill;
    end
    $finish;
end
endmodule
