// MATCHI testbench for the keccakf400 tops. Same convention as the verified
// adder/iszero/mul/div tbs: values are irrelevant to MATCHI (symbolic); only
// signal-activity timing is read from the VCD. Run length covers the deepest
// window (r [0,634]) plus margin.
// Generated by gen_keccakf.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD keccakf400
`endif
module tb ();
parameter HP = 5;
reg clk, rst, go;
reg [799:0] a;
reg [415:0] r, s;
wire [799:0] o;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .go(go), .a(a[799:0]),
             .r(r[399:0]), .s(s[399:0]), .o(o)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < 25; w = w + 1) a[w*32 +: 32] = $random;
        for (w = 0; w < 13; w = w + 1) begin
            r[w*32 +: 32] = $random;
            s[w*32 +: 32] = $random;
        end
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; go = 1'b0;
    a = 0; r = 0; s = 0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // cycle 0: one-cycle go pulse
    @(negedge clk); go = 1'b1; randfill;
    @(negedge clk); go = 1'b0; randfill;
    for (i = 0; i < 172; i = i + 1) begin
        @(negedge clk); randfill;
    end
    $finish;
end
endmodule
