// Functional smoke test for keccakf200 (NOT a security check — MATCHI is the
// separate verification step). Shares the state with a random mask, pulses
// go, waits out the 18 rounds, recombines the output shares, compares
// against the spec reference permutation (computed by gen_keccakf.py; for
// w=64 the reference is anchored on the XKCP zero-state test vector
// F1258F7940E1DDE7...). Fresh gadget randoms every cycle.
// Generated by gen_keccakf.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [399:0] a;
reg [223:0] rr, ss;
wire [399:0] o;

keccakf200 dut (.clk(clk), .rst(rst), .go(go), .a(a),
          .r(rr[199:0]), .s(ss[199:0]), .o(o));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 7; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [199:0] am, got;
integer j;
task check(input [199:0] x, input [199:0] expd);
    begin
        for (j = 0; j < 7; j = j + 1) am[j*32 +: 32] = $random;
        for (j = 0; j < 200; j = j + 1) begin
            a[2*j] = x[j] ^ am[j];  a[2*j+1] = am[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat (115) @(negedge clk);
        for (j = 0; j < 200; j = j + 1) got[j] = o[2*j] ^ o[2*j+1];
        if (got !== expd) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  in =%h", x);
            $display("  got=%h", got);
            $display("  exp=%h", expd);
        end else begin
            $display("PASS lane00=%h", got[7:0]);
        end
        repeat (30) @(negedge clk);   // past clr before the next check
    end
endtask

initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    check(200'h00000000000000000000000000000000000000000000000000, 200'heaafabc5d2692c85a3ea4c1311b8e9aa1e175cb31c8426283c);
    check(200'h8d0741093d69097653ec3934e9cc93f9dafee46fa0e664dee3, 200'h7fb8b39ae914465da2c34ed239198a4bf709a1f21a758d131c);
    check(200'h5e2676622265d2aa974cb8b21677347a3bcd53a6470f6a5b03, 200'h4d13bff435a67b2206dca304ad240e66ef7cf3d43c228878b6);
    check(200'h8a7cd545c23d0035b1d6b99640b4af90898384cf75c4cfb9fc, 200'hda4052cd970499c7747a83f82961b0a98082ba5db7f642f2aa);
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
