// Functional smoke test for store16x4 (NOT a security check). Writes 4 known
// words as fresh sharings, reads each back recombined, pages 3->0, checks
// word 0 now recombines to word 3's value and every other word is intact.
// Generated by gen_store256.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, we = 0, pg_go = 0;
reg [1:0] waddr, raddr, pg_from, pg_to;
reg [31:0] wdata;
wire [31:0] rdata;

store16x4 dut (.clk(clk), .rst(rst), .we(we), .waddr(waddr), .wdata(wdata),
          .raddr(raddr), .rdata(rdata),
          .pg_go(pg_go), .pg_from(pg_from), .pg_to(pg_to));

always #5 clk = ~clk;

reg [15:0] vals [0:3];
reg [15:0] mask, got, expd;
integer i, j, errors;

task sstore(input [1:0] ad, input [15:0] v);
    begin
        for (j = 0; j < 1; j = j + 1) mask[j*32 +: 32] = $random;
        for (j = 0; j < 16; j = j + 1) begin
            wdata[2*j] = v[j] ^ mask[j];  wdata[2*j+1] = mask[j];
        end
        @(negedge clk); we = 1'b1; waddr = ad;
        @(negedge clk); we = 1'b0;
    end
endtask

task sload_check(input [1:0] ad, input [15:0] v);
    begin
        @(negedge clk); raddr = ad;
        @(negedge clk);  // registered read port
        @(negedge clk);
        for (j = 0; j < 16; j = j + 1) got[j] = rdata[2*j] ^ rdata[2*j+1];
        if (got !== v) begin
            errors = errors + 1;
            $display("FAIL addr=%0d got=%h exp=%h", ad, got, v);
        end else $display("PASS addr=%0d %h", ad, got);
    end
endtask

initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    for (i = 0; i < 4; i = i + 1) begin
        for (j = 0; j < 1; j = j + 1) vals[i][j*32 +: 32] = $random;
        sstore(i[1:0], vals[i]);
    end
    for (i = 0; i < 4; i = i + 1) sload_check(i[1:0], vals[i]);
    // page 3 -> 0, then re-check everything
    @(negedge clk); pg_go = 1'b1; pg_from = 2'd3; pg_to = 2'd0;
    @(negedge clk); pg_go = 1'b0;
    repeat (4) @(negedge clk);
    sload_check(2'd0, vals[3]);
    for (i = 1; i < 4; i = i + 1) sload_check(i[1:0], vals[i]);
    // overwrite word 0 again and confirm
    for (j = 0; j < 1; j = j + 1) vals[0][j*32 +: 32] = $random;
    sstore(2'd0, vals[0]);
    sload_check(2'd0, vals[0]);
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
