// Functional smoke test for eq256 (NOT a security check — MATCHI is the
// separate verification step). Shares both 256-bit operands with independent
// random masks, holds the inputs steady, waits out the XOR stage + 8-level
// tree, recombines the EQ output shares, compares against (x == y).
// Fresh gadget randoms every cycle.
// Generated by gen_eq256.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [511:0] a, b;
reg [255:0] r, s;
wire [1:0] out;

eq256 dut (.clk(clk), .rst(rst), .go(go), .a(a), .b(b), .r(r), .s(s), .out(out));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 8; k = k + 1) begin
        r[k*32 +: 32] = $random;
        s[k*32 +: 32] = $random;
    end
end

reg [255:0] am, bm;
reg got, expd;
integer j;
task check(input [255:0] x, input [255:0] y);
    begin
        for (j = 0; j < 8; j = j + 1) begin
            am[j*32 +: 32] = $random;
            bm[j*32 +: 32] = $random;
        end
        for (j = 0; j < 256; j = j + 1) begin
            a[2*j]   = x[j] ^ am[j];
            a[2*j+1] = am[j];
            b[2*j]   = y[j] ^ bm[j];
            b[2*j+1] = bm[j];
        end
        repeat (200) @(negedge clk);   // >> tree depth (~24 cycles)
        got  = out[0] ^ out[1];
        expd = (x == y) ? 1'b1 : 1'b0;
        if (got !== expd) begin
            errors = errors + 1;
            $display("FAIL  x=%h y=%h got=%b exp=%b", x, y, got, expd);
        end else begin
            $display("PASS  eq=%b", got);
        end
    end
endtask

reg [255:0] xv;
initial begin
    errors = 0;
    #40 rst = 0;
    check(256'h0, 256'h0);                                     // 0 == 0 -> 1
    check(256'h1, 256'h0);                                     // differ in LSB -> 0
    for (j = 0; j < 8; j = j + 1) xv[j*32 +: 32] = $random;
    check(xv, xv);                                             // x == x -> 1
    check(xv, xv ^ (256'h1 << 255));                           // differ in MSB -> 0
    check(xv, ~xv);                                            // complement -> 0
    check({256{1'b1}}, {256{1'b1}});                           // max == max -> 1
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
