// Functional smoke test for keccakf100 (NOT a security check — MATCHI is the
// separate verification step). Shares the state with a random mask, pulses
// go, waits out the 16 rounds, recombines the output shares, compares
// against the spec reference permutation (computed by gen_keccakf.py; for
// w=64 the reference is anchored on the XKCP zero-state test vector
// F1258F7940E1DDE7...). Fresh gadget randoms every cycle.
// Generated by gen_keccakf.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [199:0] a;
reg [127:0] rr, ss;
wire [199:0] o;

keccakf100 dut (.clk(clk), .rst(rst), .go(go), .a(a),
          .r(rr[99:0]), .s(ss[99:0]), .o(o));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 4; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [99:0] am, got;
integer j;
task check(input [99:0] x, input [99:0] expd);
    begin
        for (j = 0; j < 4; j = j + 1) am[j*32 +: 32] = $random;
        for (j = 0; j < 100; j = j + 1) begin
            a[2*j] = x[j] ^ am[j];  a[2*j+1] = am[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat (103) @(negedge clk);
        for (j = 0; j < 100; j = j + 1) got[j] = o[2*j] ^ o[2*j+1];
        if (got !== expd) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  in =%h", x);
            $display("  got=%h", got);
            $display("  exp=%h", expd);
        end else begin
            $display("PASS lane00=%h", got[3:0]);
        end
        repeat (30) @(negedge clk);   // past clr before the next check
    end
endtask

initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    check(100'h0000000000000000000000000, 100'h10aae77d05820f26dabedc566);
    check(100'he74ea95439c6a91bc462c4205, 100'h3753a297ca89eb65a48489dae);
    check(100'h5f6e9ce0b9b1f7cd2ea5ecfe2, 100'hb961cbf9414fe614be45bd4f0);
    check(100'hc68e58d248ba68a6ee4f53a90, 100'ha0668ab03a217f202ef7dadba);
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
