// Functional smoke test for div16 (NOT a security check — MATCHI is the
// separate verification step). Shares each operand with a random mask, pulses
// go, waits out the 16 restoring iterations, recombines the q/rem shares,
// compares against x/y and x%y. Fresh gadget randoms every cycle (the
// recombined outputs are mask-independent). B != 0 on every vector (EVM B=0
// semantics live in the ISZERO composition, not this unit).
// Generated by gen_div256.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [31:0] a, b;
reg [63:0] rr, ss;
wire [31:0] q, rem;

div16 dut (.clk(clk), .rst(rst), .go(go), .a(a), .b(b),
            .r(rr[49:0]), .s(ss[49:0]), .q(q), .rem(rem));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 2; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [15:0] am, bm, gotq, gotr, expq, expr;
integer j;
task check(input [15:0] x, input [15:0] y);
    begin
        for (j = 0; j < 1; j = j + 1) begin
            am[j*32 +: 32] = $random;
            bm[j*32 +: 32] = $random;
        end
        for (j = 0; j < 16; j = j + 1) begin
            a[2*j] = x[j] ^ am[j];  a[2*j+1] = am[j];
            b[2*j] = y[j] ^ bm[j];  b[2*j+1] = bm[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat (779) @(negedge clk);
        for (j = 0; j < 16; j = j + 1) begin
            gotq[j] = q[2*j] ^ q[2*j+1];
            gotr[j] = rem[2*j] ^ rem[2*j+1];
        end
        expq = x / y;
        expr = x % y;
        if (gotq !== expq || gotr !== expr) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  x   =%h", x);
            $display("  y   =%h", y);
            $display("  gotq=%h expq=%h", gotq, expq);
            $display("  gotr=%h expr=%h", gotr, expr);
        end else begin
            $display("PASS x/y=%h x%%y=%h", gotq, gotr);
        end
        repeat (60) @(negedge clk);   // past clr before the next check
    end
endtask

reg [15:0] xv, yv;
initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    check({{15{1'b0}}, 1'b1}, {{15{1'b0}}, 1'b1}); // 1 / 1
    for (j = 0; j < 1; j = j + 1) xv[j*32 +: 32] = $random;
    check(xv, {{15{1'b0}}, 1'b1});                     // x / 1 = x, rem 0
    check(xv, xv);                                              // x / x = 1, rem 0
    check({{15{1'b0}}, 1'b1}, {16{1'b1}});        // 1 / max = 0, rem 1
    check({16{1'b1}}, {{14{1'b0}}, 2'b11});       // max / 3
    for (j = 0; j < 1; j = j + 1) begin
        xv[j*32 +: 32] = $random;
        yv[j*32 +: 32] = $random;
    end
    yv[15:8] = 0;                                       // small-ish divisor
    if (yv == 0) yv = 7;
    check(xv, yv);                                              // random / random
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
