// Functional smoke test for swap256 (NOT a security check — MATCHI is the
// separate verification step). Shares each operand with a random mask, pulses
// go, waits out mul + div + compare, recombines all four outputs, compares
// against the reference constant-product swap computed in 256-bit Verilog
// arithmetic (EVM wrap semantics). Fresh gadget randoms every cycle. denom =
// ri + x != 0 on every vector (the DEX-path precondition, cf. div256 header).
// Generated by gen_swap256.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [511:0] x, ri, ro, mo;
reg [3583:0] rr, ss;
wire [511:0] aout, nri, nro;
wire [1:0] ok;

swap256 dut (.clk(clk), .rst(rst), .go(go), .x(x), .ri(ri), .ro(ro), .mo(mo),
             .r(rr[3577:0]), .s(ss[3577:0]),
             .aout(aout), .nri(nri), .nro(nro), .ok(ok));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 112; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [255:0] xm, rim, rom, mom;
reg [255:0] got_aout, got_nri, got_nro;
reg got_ok;
reg [255:0] denom, num, expaout, expnri, expnro;
reg expok;
integer j;
task check(input [255:0] vx, input [255:0] vri,
           input [255:0] vro, input [255:0] vmo);
    begin
        // reference swap (256-bit wrap arithmetic = EVM semantics)
        denom = vri + vx;
        num = vro * vx;
        expaout = num / denom;      // tb guarantees denom != 0
        expnri = denom;
        expnro = vro - expaout;
        expok = (expaout >= vmo);
        // share the operands with fresh random masks
        for (j = 0; j < 8; j = j + 1) begin
            xm[j*32 +: 32] = $random;  rim[j*32 +: 32] = $random;
            rom[j*32 +: 32] = $random; mom[j*32 +: 32] = $random;
        end
        for (j = 0; j < 256; j = j + 1) begin
            x[2*j]  = vx[j] ^ xm[j];    x[2*j+1]  = xm[j];
            ri[2*j] = vri[j] ^ rim[j];  ri[2*j+1] = rim[j];
            ro[2*j] = vro[j] ^ rom[j];  ro[2*j+1] = rom[j];
            mo[2*j] = vmo[j] ^ mom[j];  mo[2*j+1] = mom[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat (138270) @(negedge clk);
        for (j = 0; j < 256; j = j + 1) begin
            got_aout[j] = aout[2*j] ^ aout[2*j+1];
            got_nri[j]  = nri[2*j] ^ nri[2*j+1];
            got_nro[j]  = nro[2*j] ^ nro[2*j+1];
        end
        got_ok = ok[0] ^ ok[1];
        if (got_aout !== expaout || got_nri !== expnri ||
            got_nro !== expnro || got_ok !== expok) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  x=%h ri=%h ro=%h mo=%h", vx, vri, vro, vmo);
            $display("  aout got=%h exp=%h", got_aout, expaout);
            $display("  nri  got=%h exp=%h", got_nri, expnri);
            $display("  nro  got=%h exp=%h", got_nro, expnro);
            $display("  ok   got=%b exp=%b", got_ok, expok);
        end else begin
            $display("PASS swap: aout=%h nri=%h nro=%h ok=%b",
                     got_aout, got_nri, got_nro, got_ok);
        end
        repeat (60) @(negedge clk);   // past clr before the next check
    end
endtask

reg [255:0] v1, v2, v3, v4;
initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    // 1. small AMM pool: 2000*100/1100 = 181, mo=0 -> ok=1
    check(256'd100, 256'd1000, 256'd2000, 256'd0);
    // 2. same trade, mo = exact expected aout -> ok=1 (>= boundary)
    check(256'd100, 256'd1000, 256'd2000, (256'd2000*256'd100)/(256'd1000+256'd100));
    // 3. same trade, mo = expected aout + 1 -> ok=0 (slippage trips)
    check(256'd100, 256'd1000, 256'd2000, (256'd2000*256'd100)/(256'd1000+256'd100) + 256'd1);
    // 4. x=1, ri=0: denom=1, aout=ro, nro=0
    for (j = 0; j < 8; j = j + 1) v1[j*32 +: 32] = $random;
    check(256'd1, 256'd0, v1, v1);
    // 5. x=0: num=0, aout=0, nro=ro, ok=(0>=mo)
    for (j = 0; j < 8; j = j + 1) v2[j*32 +: 32] = $random;
    check(256'd0, 256'd7, v2, 256'd0);
    // 6. random full-width (wrap semantics), small-ish denom for busy quotient
    for (j = 0; j < 8; j = j + 1) begin
        v1[j*32 +: 32] = $random;
        v2[j*32 +: 32] = $random;
        v3[j*32 +: 32] = $random;
        v4[j*32 +: 32] = $random;
    end
    v2[255:128] = 0;                 // ri small-ish
    v1[255:128] = 0;                 // x small-ish -> denom small, != 0
    if ((v1 + v2) == 0) v1 = v1 + 256'd3;
    check(v1, v2, v3, v4);
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
