// Functional smoke test for dexloop16 (NOT a security check — MATCHI is the
// separate step). Full storage round-trip per vector: SSTORE the two shared
// reserves, pulse tx_go (the unit SLOADs them itself), wait out the swap,
// check the direct outputs, then SLOAD the written-back reserves out of the
// scratchpad and check them against the reference too. Fresh gadget randoms
// every cycle. denom = ri + x != 0 on every vector (DEX-path precondition).
// Generated by gen_dexloop.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, tx_go = 0, we = 0;
reg [1:0] waddr, raddr;
reg [31:0] x, mo, wdata;
reg [223:0] rr, ss;
wire [31:0] aout, nri, nro, rdata;
wire [1:0] ok;

dexloop16 dut (.clk(clk), .rst(rst), .tx_go(tx_go), .we(we), .waddr(waddr),
             .raddr(raddr), .wdata(wdata), .x(x), .mo(mo),
             .r(rr[217:0]), .s(ss[217:0]),
             .aout(aout), .nri(nri), .nro(nro), .ok(ok), .rdata(rdata));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 7; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [15:0] xm, mom, wm;
reg [15:0] got_aout, got_nri, got_nro, got_slot;
reg got_ok;
reg [15:0] denom, num, expaout, expnri, expnro;
reg expok;
integer j;

task sstore(input [1:0] slot, input [15:0] v);
    begin
        for (j = 0; j < 1; j = j + 1) wm[j*32 +: 32] = $random;
        for (j = 0; j < 16; j = j + 1) begin
            wdata[2*j] = v[j] ^ wm[j];  wdata[2*j+1] = wm[j];
        end
        @(negedge clk); we = 1'b1; waddr = slot;
        @(negedge clk); we = 1'b0;
    end
endtask

task sload(input [1:0] slot);
    begin
        raddr = slot;
        repeat (3) @(negedge clk);
        for (j = 0; j < 16; j = j + 1)
            got_slot[j] = rdata[2*j] ^ rdata[2*j+1];
    end
endtask

task check(input [15:0] vx, input [15:0] vri,
           input [15:0] vro, input [15:0] vmo);
    begin
        // reference swap (16-bit wrap arithmetic = EVM semantics)
        denom = vri + vx;
        num = vro * vx;
        expaout = num / denom;      // tb guarantees denom != 0
        expnri = denom;
        expnro = vro - expaout;
        expok = (expaout >= vmo);
        // SSTORE the reserves (the previous tx's state)
        sstore(2'd0, vri);
        sstore(2'd1, vro);
        // share the calldata operands with fresh random masks
        for (j = 0; j < 1; j = j + 1) begin
            xm[j*32 +: 32] = $random;  mom[j*32 +: 32] = $random;
        end
        for (j = 0; j < 16; j = j + 1) begin
            x[2*j]  = vx[j] ^ xm[j];    x[2*j+1]  = xm[j];
            mo[2*j] = vmo[j] ^ mom[j];  mo[2*j+1] = mom[j];
        end
        @(negedge clk); tx_go = 1'b1;
        @(negedge clk); tx_go = 1'b0;
        repeat (994) @(negedge clk);
        for (j = 0; j < 16; j = j + 1) begin
            got_aout[j] = aout[2*j] ^ aout[2*j+1];
            got_nri[j]  = nri[2*j] ^ nri[2*j+1];
            got_nro[j]  = nro[2*j] ^ nro[2*j+1];
        end
        got_ok = ok[0] ^ ok[1];
        if (got_aout !== expaout || got_nri !== expnri ||
            got_nro !== expnro || got_ok !== expok) begin
            errors = errors + 1;
            $display("FAIL outputs");
            $display("  x=%h ri=%h ro=%h mo=%h", vx, vri, vro, vmo);
            $display("  aout got=%h exp=%h", got_aout, expaout);
            $display("  nri  got=%h exp=%h", got_nri, expnri);
            $display("  nro  got=%h exp=%h", got_nro, expnro);
            $display("  ok   got=%b exp=%b", got_ok, expok);
        end else begin
            $display("PASS outputs: aout=%h nri=%h nro=%h ok=%b",
                     got_aout, got_nri, got_nro, got_ok);
        end
        // storage round-trip: the written-back reserves must be in the pad
        repeat (10) @(negedge clk);   // strictly after writeback + clr
        sload(2'd0);
        if (got_slot !== expnri) begin
            errors = errors + 1;
            $display("FAIL slot0 (nri) got=%h exp=%h", got_slot, expnri);
        end else $display("PASS slot0 (nri) = %h", got_slot);
        sload(2'd1);
        if (got_slot !== expnro) begin
            errors = errors + 1;
            $display("FAIL slot1 (nro) got=%h exp=%h", got_slot, expnro);
        end else $display("PASS slot1 (nro) = %h", got_slot);
        repeat (60) @(negedge clk);
    end
endtask

reg [15:0] v1, v2, v3, v4;
initial begin
    errors = 0;
    waddr = 0; raddr = 0; x = 0; mo = 0; wdata = 0;
    #40 rst = 0;
    @(negedge clk);
    // 1. small AMM pool: 2000*100/1100 = 181, mo=0 -> ok=1
    check(16'd100, 16'd1000, 16'd2000, 16'd0);
    // 2. same trade, mo = exact expected aout -> ok=1 (>= boundary)
    check(16'd100, 16'd1000, 16'd2000, (16'd2000*16'd100)/(16'd1000+16'd100));
    // 3. same trade, mo = expected aout + 1 -> ok=0 (slippage trips)
    check(16'd100, 16'd1000, 16'd2000, (16'd2000*16'd100)/(16'd1000+16'd100) + 16'd1);
    // 4. x=1, ri=0: denom=1, aout=ro, nro=0
    for (j = 0; j < 1; j = j + 1) v1[j*32 +: 32] = $random;
    check(16'd1, 16'd0, v1, v1);
    // 5. x=0: num=0, aout=0, nro=ro, ok=(0>=mo)
    for (j = 0; j < 1; j = j + 1) v2[j*32 +: 32] = $random;
    check(16'd0, 16'd7, v2, 16'd0);
    // 6. random full-width (wrap semantics), small-ish denom for busy quotient
    for (j = 0; j < 1; j = j + 1) begin
        v1[j*32 +: 32] = $random;
        v2[j*32 +: 32] = $random;
        v3[j*32 +: 32] = $random;
        v4[j*32 +: 32] = $random;
    end
    v2[15:8] = 0;                 // ri small-ish
    v1[15:8] = 0;                 // x small-ish -> denom small, != 0
    if ((v1 + v2) == 0) v1 = v1 + 16'd3;
    check(v1, v2, v3, v4);
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
