// MATCHI testbench for the store256x8 tops: 8 writes (fresh sharings), a page
// 7->0 through the paging path, then continuous reads sweeping all words.
// Values are irrelevant to MATCHI (symbolic); activity timing matters:
// a_act = we cycles, out_act = first write .. end of trace.
// Generated by gen_store256.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD store256x8
`endif
module tb ();
parameter HP = 5;
reg clk, rst, we, pg_go;
reg [2:0] waddr, raddr, pg_from, pg_to;
reg [511:0] wdata;
wire [511:0] rdata;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .we(we), .waddr(waddr),
             .wdata(wdata[511:0]), .raddr(raddr), .rdata(rdata),
             .pg_go(pg_go), .pg_from(pg_from), .pg_to(pg_to)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < 16; w = w + 1) wdata[w*32 +: 32] = $random;
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; we = 1'b0; pg_go = 1'b0;
    waddr = 0; raddr = 0; pg_from = 0; pg_to = 0; wdata = 0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // SSTORE a fresh sharing into every word
    for (i = 0; i < 8; i = i + 1) begin
        @(negedge clk); we = 1'b1; waddr = i[2:0]; randfill;
    end
    @(negedge clk); we = 1'b0; randfill;
    // page word 7 -> word 0 (through the paging lanes)
    @(negedge clk); pg_go = 1'b1; pg_from = 3'd7; pg_to = 3'd0; randfill;
    @(negedge clk); pg_go = 1'b0; randfill;
    // continuous SLOAD sweep (read-port transitions across all words)
    for (i = 0; i < 6*8; i = i + 1) begin
        @(negedge clk); raddr = i % 8; randfill;
    end
    // interleaved write/read tail
    for (i = 0; i < 8; i = i + 1) begin
        @(negedge clk); we = 1'b1; waddr = i[2:0]; raddr = (8 - 1 - i); randfill;
        @(negedge clk); we = 1'b0; randfill;
    end
    repeat (10) @(negedge clk);
    $finish;
end
endmodule
