// Functional smoke test for keccakf1600 (NOT a security check — MATCHI is the
// separate verification step). Shares the state with a random mask, pulses
// go, waits out the 24 rounds, recombines the output shares, compares
// against the spec reference permutation (computed by gen_keccakf.py; for
// w=64 the reference is anchored on the XKCP zero-state test vector
// F1258F7940E1DDE7...). Fresh gadget randoms every cycle.
// Generated by gen_keccakf.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [3199:0] a;
reg [1599:0] rr, ss;
wire [3199:0] o;

keccakf1600 dut (.clk(clk), .rst(rst), .go(go), .a(a),
          .r(rr[1599:0]), .s(ss[1599:0]), .o(o));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 50; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [1599:0] am, got;
integer j;
task check(input [1599:0] x, input [1599:0] expd);
    begin
        for (j = 0; j < 50; j = j + 1) am[j*32 +: 32] = $random;
        for (j = 0; j < 1600; j = j + 1) begin
            a[2*j] = x[j] ^ am[j];  a[2*j+1] = am[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat (151) @(negedge clk);
        for (j = 0; j < 1600; j = j + 1) got[j] = o[2*j] ^ o[2*j+1];
        if (got !== expd) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  in =%h", x);
            $display("  got=%h", got);
            $display("  exp=%h", expd);
        end else begin
            $display("PASS lane00=%h", got[63:0]);
        end
        repeat (30) @(negedge clk);   // past clr before the next check
    end
endtask

initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    check(1600'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 1600'heaf1ff7b5ceca24975f644e97f30a13b16f53526e70465c21841f924a2c509e4940c7922ae3a26148c3ee88a1ccf32c8b87c5a554fd00ecb613670957bc4661164befef28cc970f205e5635a21d9ae6101f22f1a11a5569f43b831cd0347c82681a57c16dbcf555fa9a6e6260d712103eb5aa93f2317d63530935ab7d08ffc64ad30a6f71b19059c8c5bda0cd6192e7690fee5a0a44647c4ff97a42d7f8e6fd48b284e056253d057bd1547306f80494dd598261ea65aa9ee84d5ccf933c0478af1258f7940e1dde7);
    check(1600'h0abd6acf6d9caa4743fe55d89d5e7c2784225062763d768c964d7919e5334d01b53b4d65cbd3217bf2cdd507db6cb2dea6731e9f66b77a502d9fb8b67bda99afa49d2d962aafbc2ee215648a644de7c1d9d7f614452f63370a10e259ad0799f452c557ef021e3b11db60e2bf55223424ef8aa4dd9dcc6a11fe16449d505bd538977f9ce89d52496c3bc9eef525e3fb738590f34503b13929dd8cb4d6a56d6c1f2d8b4e6b7c6b29873b079305d428fc5ede2f4d570c4c67f11d4a532c45660c20f5c27a546b55d81f, 1600'h271a30a4ad7131d6d6c780e5d4137efc55e3b05a844eaeb6ffd788f41a7287a14d088e1dc3ebd4cad36320506e8bc00ac5b2cc2bb8f8cb3ba34dc0387cae389bcd46eb3f4d431ec7ca6c2c2ee3944f62aac4b927546c7deb15e6ae43bb766363b420193dda745f5c14acef7321b2a6003d8deb8b17c597652e48bb0486baae9b1bb29e371472e4f599371d78275ea6c3ea2386e23821ed48ca660a514e6c7ae85d0caa36464bb74958407b755dbf6e257d4bf31ba65e9ffa25a9bcc2b4f97911dddc744cafa17f3d);
    check(1600'h7fe46d081ab890ce32842eb410768db3af859697f8a35b181438654702f7bbc6331cadfc02842465070c207f7b1763c17281ceaa689c071bb36804bae19fe723101cdb631a065664b633bfd4afd36ee1ef8df08fe393733693cd31ed2cd0d0bb474a4000c61c9e1c4ac8c1bde8cbb7a459c4757c7bce481c34b94cbaa1fc00092b6d4863a54d326d0672d31ea20b8dc09abedf0f7e75b0b45c6eab1514295c825cfaf4ed34490f04211de0baffa22adec854f1e110a90b3624524ec2b1e4da8f37763ed66aa394fa, 1600'ha8ab13f32174696c513174097a77bd8fd8283299bd53cf0923e204b574c741828988c26521cba324e132e776c3579cd2291a2b50e492e1df8fda6328d6406c0fda230ef9661a544b4e1f35e668056db5727c8457e314fd554367b2899fb041b7c1c3d3b3fd278a2ca0235248a71a4a9743158b34b757fd62f2ee046659b73289c26ac64cb33b0d7fecc79b83ceb5e83240e85c0430612e2202a9f54afb65c996959f86d3aa618be9899c3350a8599774dd90e4e51d7769d44639a8549ab35917492d651ff0abc372);
    check(1600'hdf5f57efa7c773f3da96013416d1c08336ee4ca2e6f7f01a60c552a494965c276776c5c9fa64afa60af671e224956a86f3748a9d63d795d1104174d3a419bc2878e1df05c4ae1a77e723b7e5731720c6dc81a04358567378d3f1026da80a95fb3d17946eaefa1403404bcd15a9481395bd530250f0e916b0f135b574c1736480d861b7b7400302e74e9e24c11418fd1f898a85831e8b43b685ed502bfcb88816bb8953b62c1c754742b9622893397eef0ad5e60ec5d0426512cdae613920bf39c35a5df646de5718, 1600'hb7bf6a64b720f186e153205d4f76a7fce5ade27de10e0f8a2f8532f70a805787c0a7d663a3fdd4b71b1e758219d2c322927bf0f9f716da63a07af1ef037d86005811d244bba15f78362e8ff1def4e59a750a254bf71685c95e75a1ce8a6bfddcc4652f8efcce9b5fea3d6deba67d1565f6917bbf6fb8d104b429c2a8fefdab056883368e33644798eccdde0942042366afa1b3f4f7800712661d058e539baf458f0d8d882bb26eb5d1f813b5588487a0b162e7933856e1971e526c1552e8ffb6fcb76bd71ee301bc);
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
