// Functional smoke test for sponge100 (NOT a security check — MATCHI is the
// separate verification step). Shares the incoming state AND the message with
// independent random masks, pulses go, waits out the 16 rounds, recombines
// the output shares, compares against absorb+permute computed by the spec
// reference (gen_sponge100.py — anchored on the verified keccakf100 unit's
// own zero-state vector 10aae77d05820f26dabedc566). Fresh gadget randoms
// every cycle.
// Generated by gen_sponge100.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [199:0] st;
reg [63:0] m;
reg [127:0] rr, ss;
wire [199:0] o;

sponge100 dut (.clk(clk), .rst(rst), .go(go), .st(st), .m(m),
          .r(rr[99:0]), .s(ss[99:0]), .o(o));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 4; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [99:0] am, got;
reg [31:0] bm;
integer j;
task check(input [99:0] x, input [31:0] mx, input [99:0] expd);
    begin
        for (j = 0; j < 4; j = j + 1) am[j*32 +: 32] = $random;
        bm = $random;
        for (j = 0; j < 100; j = j + 1) begin
            st[2*j] = x[j] ^ am[j];  st[2*j+1] = am[j];
        end
        for (j = 0; j < 32; j = j + 1) begin
            m[2*j] = mx[j] ^ bm[j];  m[2*j+1] = bm[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat (103) @(negedge clk);
        for (j = 0; j < 100; j = j + 1) got[j] = o[2*j] ^ o[2*j+1];
        if (got !== expd) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  st =%h m=%h", x, mx);
            $display("  got=%h", got);
            $display("  exp=%h", expd);
        end else begin
            $display("PASS out=%h", got);
        end
        repeat (30) @(negedge clk);   // past clr before the next check
    end
endtask

initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    // st=0 m=0 (first block, empty message: absorbed = PAD only)
    check(100'h0000000000000000000000000, 32'h00000000, 100'hc22a11a2b0809077ec40b0a76);
    // st=0, m=deadbeef (first block with message)
    check(100'h0000000000000000000000000, 32'hdeadbeef, 100'h6deccd1f227023702f790d4a6);
    // chained block: random incoming state + random message
    check(100'h47a02703034896e8dfe956cc5, 32'h8190db2c, 100'h829b7dc3cf50e62a4093e36f6);
    // chained block: second random vector
    check(100'hd186cec79567a5862fd85a938, 32'h9f909d4f, 100'hb746d1e1ddb5b4092b01bd59b);
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
