// Functional smoke test for keccakf400 (NOT a security check — MATCHI is the
// separate verification step). Shares the state with a random mask, pulses
// go, waits out the 20 rounds, recombines the output shares, compares
// against the spec reference permutation (computed by gen_keccakf.py; for
// w=64 the reference is anchored on the XKCP zero-state test vector
// F1258F7940E1DDE7...). Fresh gadget randoms every cycle.
// Generated by gen_keccakf.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [799:0] a;
reg [415:0] rr, ss;
wire [799:0] o;

keccakf400 dut (.clk(clk), .rst(rst), .go(go), .a(a),
          .r(rr[399:0]), .s(ss[399:0]), .o(o));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 13; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [399:0] am, got;
integer j;
task check(input [399:0] x, input [399:0] expd);
    begin
        for (j = 0; j < 13; j = j + 1) am[j*32 +: 32] = $random;
        for (j = 0; j < 400; j = j + 1) begin
            a[2*j] = x[j] ^ am[j];  a[2*j+1] = am[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat (127) @(negedge clk);
        for (j = 0; j < 400; j = j + 1) got[j] = o[2*j] ^ o[2*j+1];
        if (got !== expd) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  in =%h", x);
            $display("  got=%h", got);
            $display("  exp=%h", expd);
        end else begin
            $display("PASS lane00=%h", got[15:0]);
        end
        repeat (30) @(negedge clk);   // past clr before the next check
    end
endtask

initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    check(400'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 400'hb38e714c71ff58ee633e6e146d955d8159a15246e7760ec9dc7560520337bf8feff078705bd1eca0e89f14f50fa940ac09f5);
    check(400'hec9377bb1f833aef9092269e82ddfc27e249d4a02a2a050af4177d33fc70d928b4b94318ba519bb29c043ae960bbed054f15, 400'h8bc74de49147237e219edd29d3747eafa99d054c448f2aed364ebc316fa3f88fdd57fdfd675f6dc1abcc4e5592c73d323772);
    check(400'h52bd2901a8f46284b8f9cac112f12fb478a62dd7acf8fbf5996e84fdfc21c6fd919109bed073cc97c4935fd110c210b9f4a0, 400'h017afde3b98c2f7fa203e3c704d1400c97b612d45731bb3337cebc323a0fe1f075b541a87610a38694a5fd44a9195f2bce88);
    check(400'h569ac9297cb407b591364b99a58788292279d63dae5a225cf0a8188d3fbd2fa8c1ce872ee49c9ddd470a9b6c829f0b889669, 400'hf4f0cdaf57c02636e4a1e81bfbd777bd91119a864579af7d9cc0587de05f69b210640291b1dfc7d4b4c0349c281894feee33);
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
