// Functional smoke test for divevm256 (NOT a security check — MATCHI is the
// separate verification step). Shares each operand with a random mask, pulses
// go, waits out the 256 restoring iterations, recombines the qe/reme shares,
// compares against EVM semantics: q = (y==0) ? 0 : x/y, rem = (y==0) ? 0 : x%y.
// B=0 vectors are INCLUDED — that gating is exactly what this unit adds over
// the bare div core. Fresh gadget randoms every cycle (the recombined outputs
// are mask-independent).
// Generated by gen_divevm.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [511:0] a, b;
reg [1567:0] rr, ss;
wire [511:0] qe, reme;

divevm256 dut (.clk(clk), .rst(rst), .go(go), .a(a), .b(b),
               .r(rr[1536:0]), .s(ss[1536:0]), .qe(qe), .reme(reme));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 49; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [255:0] am, bm, gotq, gotr, expq, expr;
integer j;
task check(input [255:0] x, input [255:0] y);
    begin
        for (j = 0; j < 8; j = j + 1) begin
            am[j*32 +: 32] = $random;
            bm[j*32 +: 32] = $random;
        end
        for (j = 0; j < 256; j = j + 1) begin
            a[2*j] = x[j] ^ am[j];  a[2*j+1] = am[j];
            b[2*j] = y[j] ^ bm[j];  b[2*j+1] = bm[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat (135179) @(negedge clk);
        for (j = 0; j < 256; j = j + 1) begin
            gotq[j] = qe[2*j] ^ qe[2*j+1];
            gotr[j] = reme[2*j] ^ reme[2*j+1];
        end
        if (y == 0) begin
            expq = 0;
            expr = 0;
        end else begin
            expq = x / y;
            expr = x % y;
        end
        if (gotq !== expq || gotr !== expr) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  x   =%h", x);
            $display("  y   =%h", y);
            $display("  gotq=%h expq=%h", gotq, expq);
            $display("  gotr=%h expr=%h", gotr, expr);
        end else begin
            $display("PASS q=%h rem=%h (y==0:%0d)", gotq, gotr, y == 0);
        end
        repeat (60) @(negedge clk);   // past clr before the next check
    end
endtask

reg [255:0] xv, yv;
initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    check({{255{1'b0}}, 1'b1}, {{255{1'b0}}, 1'b1}); // 1 / 1
    check({{255{1'b0}}, 1'b1}, {256{1'b0}});            // 1 / 0 = 0, rem 0 (EVM)
    check({256{1'b0}}, {256{1'b0}});                        // 0 / 0 = 0, rem 0 (EVM)
    for (j = 0; j < 8; j = j + 1) xv[j*32 +: 32] = $random;
    check(xv, {256{1'b0}});                                     // x / 0 = 0, rem 0 (EVM)
    check(xv, {{255{1'b0}}, 1'b1});                         // x / 1 = x, rem 0
    check(xv, xv);                                                  // x / x = 1, rem 0
    check({256{1'b1}}, {{254{1'b0}}, 2'b11});           // max / 3
    for (j = 0; j < 8; j = j + 1) begin
        xv[j*32 +: 32] = $random;
        yv[j*32 +: 32] = $random;
    end
    yv[255:128] = 0;                                           // small-ish divisor
    if (yv == 0) yv = 7;
    check(xv, yv);                                                  // random / random
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
