// MATCHI testbench for the swap16 tops. Same convention as the verified
// adder/iszero/mul/div tbs: values are irrelevant to MATCHI (symbolic); only
// signal-activity timing is read from the VCD. Inputs re-randomized every
// cycle so the annotated activity windows match physics. Run length covers
// the deepest window (r [0,1527]) plus margin.
// Generated by gen_swap256.py; do not hand-edit.
`timescale 1ns/1ps
`ifndef TOPMOD
`define TOPMOD swap16
`endif
module tb ();
parameter HP = 5;
reg clk, rst, go;
reg [31:0] x, ri, ro, mo;
reg [223:0] r, s;
wire [31:0] aout, nri, nro;
wire [1:0] ok;
`ifdef RECOMB
wire [1:0] leak_o;
`endif

always #HP clk = ~clk;

`TOPMOD dut (.clk(clk), .rst(rst), .go(go),
             .x(x[31:0]), .ri(ri[31:0]),
             .ro(ro[31:0]), .mo(mo[31:0]),
             .r(r[217:0]), .s(s[217:0]),
             .aout(aout), .nri(nri), .nro(nro), .ok(ok)
`ifdef RECOMB
             , .leak_o(leak_o)
`endif
);

integer i, w;
task randfill;
    begin
        for (w = 0; w < 1; w = w + 1) begin
            x[w*32 +: 32] = $random;
            ri[w*32 +: 32] = $random;
            ro[w*32 +: 32] = $random;
            mo[w*32 +: 32] = $random;
        end
        for (w = 0; w < 7; w = w + 1) begin
            r[w*32 +: 32] = $random;
            s[w*32 +: 32] = $random;
        end
    end
endtask

initial begin
`ifdef DUMPFILE
    $dumpfile(`DUMPFILE); $dumpvars(0, tb);
`endif
    clk = 1'b1; rst = 1'b1; go = 1'b0;
    x = 0; ri = 0; ro = 0; mo = 0; r = 0; s = 0;
    #(6*HP);
    @(negedge clk); rst = 1'b0;
    #(4*HP);
    // cycle 0: one-cycle go pulse
    @(negedge clk); go = 1'b1; randfill;
    @(negedge clk); go = 1'b0; randfill;
    for (i = 0; i < 1025; i = i + 1) begin
        @(negedge clk); randfill;
    end
    $finish;
end
endmodule
