// Functional smoke test for the KECCAK256 SPONGE COMPOSITION over the
// verified keccakf1600 round unit (NOT a security check — the unit's MATCHI
// matrix is RESULT_KECCAKF1600.md; this tb adds ZERO gadgets and ZERO RTL).
// Message bits enter as a 2-share sharing; pad10*1 + capacity zeros are
// public constants XORed into SHARE 0 ONLY (share 1 stays 0 there) — the
// share-local rate/padding XOR of SWAP_DATAPATH.md. One permutation;
// digest = recombined lanes 0..3. Reference digests are spec-derived and
// double-anchored (XKCP zero-state + canonical keccak256("")).
// Generated by gen_keccak256_smoke.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [3199:0] a;
reg [1599:0] rr, ss;
wire [3199:0] o;

keccakf1600 dut (.clk(clk), .rst(rst), .go(go), .a(a),
          .r(rr[1599:0]), .s(ss[1599:0]), .o(o));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 50; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [1599:0] am;
reg [255:0] got;
integer j;
task check(input [1599:0] x, input [255:0] expd, input integer msgbits);
    begin
        // mask ONLY the message region: those bits arrive as a real sharing;
        // padding + capacity are public -> share 0 carries the constant,
        // share 1 is 0 there (share-local injection, no gadgets).
        for (j = 0; j < 50; j = j + 1) am[j*32 +: 32] = $random;
        for (j = 0; j < 1600; j = j + 1) begin
            if (j < msgbits) begin
                a[2*j] = x[j] ^ am[j];  a[2*j+1] = am[j];
            end else begin
                a[2*j] = x[j];          a[2*j+1] = 1'b0;
            end
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat (151) @(negedge clk);
        for (j = 0; j < 256; j = j + 1) got[j] = o[2*j] ^ o[2*j+1];
        if (got !== expd) begin
            errors = errors + 1;
            $display("FAIL msgbits=%0d", msgbits);
            $display("  got=%h", got);
            $display("  exp=%h", expd);
        end else begin
            $display("PASS digest(flat lanes 0..3)=%h msgbits=%0d", got, msgbits);
        end
        repeat (30) @(negedge clk);   // past clr before the next check
    end
endtask

initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    // empty message  (canonical c5d24601... digest)
    // canonical digest: c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470
    check(1600'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001,
          256'h70a4855d04d8fa7b3b2782ca53b600e5c003c7dcb27d7e923c23f7860146d2c5, 0);
    // mapping slot: keccak256(key || slot=3), EVM big-endian words
    // canonical digest: 91c112650fce6816d0490e5a6dbcd1d0650a1c6921591c3f120e1cbf31d4a20d
    check(1600'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000103000000000000000000000000000000000000000000000000000000000000000100edfe0000feca005eba00eeffc000efbeadde000000000000000000000000,
          256'h0da2d431bf1c0e123f1c5921691c0a65d0d1bc6d5a0e49d01668ce0f6512c191, 512);
    // random 64-byte message
    // canonical digest: 63fc47483bbba663fd1f0357c53d3ef6cd5a75213b6eb8388eedb984a8aca83e
    check(1600'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001ea5b6070bca93f6fba0b6d0094083e5b01c5469fd1c732325d13fff6259ff7ea473c231f6dc0d7fae6f5478c410387f3d351daf65705c44badb26764a592ec07,
          256'h3ea8aca884b9ed8e38b86e3b21755acdf63e3dc557031ffd63a6bb3b4847fc63, 512);
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
