// Functional smoke test for mul256 (NOT a security check — MATCHI is the
// separate verification step). Shares each operand with a random mask, pulses
// go, waits out the 256 carry-save iterations + final ripple, recombines the
// product shares, compares against (x*y) mod 2^256. Fresh gadget randoms every
// cycle (the recombined output is mask-independent).
// Generated by gen_mul256.py; do not hand-edit.
`timescale 1ns/1ps
module tb;
reg clk = 0, rst = 1, go = 0;
reg [511:0] a, b;
reg [1279:0] rr, ss;
wire [511:0] prod;

mul256 dut (.clk(clk), .rst(rst), .go(go), .a(a), .b(b),
            .r(rr[1275:0]), .s(ss[1275:0]), .prod(prod));

always #5 clk = ~clk;

integer k, errors;
always @(negedge clk) begin
    for (k = 0; k < 40; k = k + 1) begin
        rr[k*32 +: 32] = $random;
        ss[k*32 +: 32] = $random;
    end
end

reg [255:0] am, bm, got, expd;
integer j;
task check(input [255:0] x, input [255:0] y);
    begin
        for (j = 0; j < 8; j = j + 1) begin
            am[j*32 +: 32] = $random;
            bm[j*32 +: 32] = $random;
        end
        for (j = 0; j < 256; j = j + 1) begin
            a[2*j] = x[j] ^ am[j];  a[2*j+1] = am[j];
            b[2*j] = y[j] ^ bm[j];  b[2*j+1] = bm[j];
        end
        @(negedge clk); go = 1'b1;
        @(negedge clk); go = 1'b0;
        repeat (2580) @(negedge clk);
        for (j = 0; j < 256; j = j + 1) got[j] = prod[2*j] ^ prod[2*j+1];
        expd = x * y;               // Verilog truncates to 256 bits = mod 2^256
        if (got !== expd) begin
            errors = errors + 1;
            $display("FAIL");
            $display("  x  =%h", x);
            $display("  y  =%h", y);
            $display("  got=%h", got);
            $display("  exp=%h", expd);
        end else begin
            $display("PASS x*y mod 2^256: %h", got);
        end
        repeat (60) @(negedge clk);   // past clr before the next check
    end
endtask

reg [255:0] xv, yv;
initial begin
    errors = 0;
    #40 rst = 0;
    @(negedge clk);
    check({256{1'b0}}, {256{1'b0}});                    // 0 * 0
    check({{255{1'b0}}, 1'b1}, {{255{1'b0}}, 1'b1}); // 1 * 1
    for (j = 0; j < 8; j = j + 1) xv[j*32 +: 32] = $random;
    check(xv, {{255{1'b0}}, 1'b1});                     // x * 1 = x
    check({1'b1, {255{1'b0}}}, {{254{1'b0}}, 2'b10}); // 2^255 * 2 = 0 (wrap)
    check({256{1'b1}}, {256{1'b1}});                    // (-1)*(-1) = 1 mod 2^256
    for (j = 0; j < 8; j = j + 1) begin
        xv[j*32 +: 32] = $random;
        yv[j*32 +: 32] = $random;
    end
    check(xv, yv);                                              // random * random
    if (errors == 0) $display("SMOKE: ALL PASS");
    else             $display("SMOKE: %0d FAILURES", errors);
    $finish;
end
endmodule
