/-
Generated by tools/maskc/maskc.py from: a & b

PoC lowering rule: a two-input Boolean AND becomes the proved, first-order,
two-share DOM-AND template.  Source input order is a=0, b=1.
-/
import LeanSec.Gadgets.DomAnd

namespace LeanSec.Compiled.MaskedAnd

open Gadget

/-- The unmasked source-level function, with inputs in source order. -/
def sourceSpec (inputs : List Bool) : Bool :=
  inputs.getD 0 false && inputs.getD 1 false

/-- Masked circuit selected by the compiler's single DOM-AND lowering rule. -/
def circuit : Circuit := LeanSec.Gadgets.DomAnd.circuit

/-- The template instance, made explicitly to refer to the emitted circuit. -/
def gadget : GadgetInstance :=
  { LeanSec.Gadgets.DomAnd.gadget with circuit := circuit }

/-- Audit anchor: this generated instance is exactly the proved template. -/
theorem is_dom_and_template :
    gadget = LeanSec.Gadgets.DomAnd.gadget := by
  rfl

/-- Functional anchor: all input sharings and all randomness recombine to AND. -/
theorem recombine_anchor : recombinesTo gadget sourceSpec := by
  rw [is_dom_and_template]
  unfold sourceSpec
  exact LeanSec.Gadgets.DomAnd.recombines

set_option maxRecDepth 10000
set_option maxHeartbeats 4000000

/-- Security anchor: every set of at most one glitch-expanded probe is secure. -/
theorem probing_anchor : probingSecure gadget glitch 1 := by
  decide

set_option maxRecDepth 1000
set_option maxHeartbeats 200000

#print axioms recombine_anchor
#print axioms probing_anchor

end LeanSec.Compiled.MaskedAnd
