import LeanSec.Gadget

/-! GENERATED by tools/netlist2lean/netlist2lean.py from a SILVER-format
    NANG45 netlist (module `dom_and`).  DO NOT EDIT BY HAND — regenerate.
    The proved object below is DERIVED from the netlist SILVER verifies,
    not hand-transcribed.  See LeanSec/Netlist/TRUST.md. -/

namespace LeanSec.Netlist.DomAndGen

open LeanSec LeanSec.Gadget

def circuit : Circuit :=
  { gates := #[
      { kind := .inp 0 0, inputs := [] },    -- 0: AxDI[0] = inp 0 0
      { kind := .inp 0 1, inputs := [] },    -- 1: AxDI[1] = inp 0 1
      { kind := .inp 1 0, inputs := [] },    -- 2: BxDI[0] = inp 1 0
      { kind := .inp 1 1, inputs := [] },    -- 3: BxDI[1] = inp 1 1
      { kind := .rnd 0, inputs := [] },    -- 4: ZxDI = rnd 0
      { kind := .reg, inputs := [(19, 1)] },    -- 5: reg <- p00
      { kind := .reg, inputs := [(18, 1)] },    -- 6: reg <- p11
      { kind := .reg, inputs := [(17, 1)] },    -- 7: reg <- p01
      { kind := .reg, inputs := [(13, 1)] },    -- 8: reg <- p10
      { kind := .xor, inputs := [(5, 0), (7, 0)] },    -- 9: _06_
      { kind := .and, inputs := [(1, 0), (2, 0)] },    -- 10: _07_ (nand internal and)  -- internal (non-member)
      { kind := .not, inputs := [(10, 0)] },    -- 11: _07_
      { kind := .xor, inputs := [(4, 0), (11, 0)] },    -- 12: _08_ (xnor internal xor)  -- internal (non-member)
      { kind := .not, inputs := [(12, 0)] },    -- 13: _08_
      { kind := .and, inputs := [(0, 0), (3, 0)] },    -- 14: _09_ (nand internal and)  -- internal (non-member)
      { kind := .not, inputs := [(14, 0)] },    -- 15: _09_
      { kind := .xor, inputs := [(4, 0), (15, 0)] },    -- 16: _10_ (xnor internal xor)  -- internal (non-member)
      { kind := .not, inputs := [(16, 0)] },    -- 17: _10_
      { kind := .and, inputs := [(1, 0), (3, 0)] },    -- 18: _11_
      { kind := .and, inputs := [(2, 0), (0, 0)] },    -- 19: _12_
      { kind := .xor, inputs := [(6, 0), (8, 0)] }    -- 20: _13_
    ] }

def member (n : Node) : Bool :=
  (n.cycle == 0 && [0, 1, 2, 3, 4, 11, 13, 15, 17, 18, 19].contains n.gate) ||
  (n.cycle == 1 && [5, 6, 7, 8, 9, 20].contains n.gate)

def gadget : GadgetInstance :=
  { circuit := circuit
    horizon := 2
    d := 2
    inputCount := 2
    inputArrival := fun sharing share => .inp sharing share 0
    output := fun share =>
      if share == 0 then { gate := 9, cycle := 1 }
      else { gate := 20, cycle := 1 }
    member := member
    randomness := [.rnd 0 0, .rnd 0 1] }

end LeanSec.Netlist.DomAndGen
