import LeanSec.Gadget

/-! GENERATED by tools/netlist2lean/netlist2lean.py from a SILVER-format
    NANG45 netlist (module `hpc2_top`).  DO NOT EDIT BY HAND — regenerate.
    The proved object below is DERIVED from the netlist SILVER verifies,
    not hand-transcribed.  See LeanSec/Netlist/TRUST.md. -/
/- Primitive expansion nodes are members: conservative vs SILVER cells. -/

namespace LeanSec.Netlist.HPC2Gen

open LeanSec LeanSec.Gadget

def circuit : Circuit :=
  { gates := #[
      { kind := .inp 0 0, inputs := [] },    -- 0: AxDI[0] = inp 0 0
      { kind := .inp 0 1, inputs := [] },    -- 1: AxDI[1] = inp 0 1
      { kind := .inp 1 0, inputs := [] },    -- 2: BxDI[0] = inp 1 0
      { kind := .inp 1 1, inputs := [] },    -- 3: BxDI[1] = inp 1 1
      { kind := .rnd 0, inputs := [] },    -- 4: RxDI = rnd 0
      { kind := .reg, inputs := [(2, 1)] },    -- 5: reg <- BxDI[0]
      { kind := .reg, inputs := [(32, 1)] },    -- 6: reg <- \dut.inner.gen_ParProdI[0].gen_inner.REGin_aibi.in
      { kind := .reg, inputs := [(31, 1)] },    -- 7: reg <- \dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_w.in
      { kind := .reg, inputs := [(26, 1)] },    -- 8: reg <- \dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_u.in
      { kind := .reg, inputs := [(25, 1)] },    -- 9: reg <- \dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_v.in
      { kind := .reg, inputs := [(24, 1)] },    -- 10: reg <- \dut.inner.gen_ParProdI[0].gen_ParProdJ[1].gen_NotEq.REGin_w.in
      { kind := .reg, inputs := [(3, 1)] },    -- 11: reg <- BxDI[1]
      { kind := .reg, inputs := [(23, 1)] },    -- 12: reg <- \dut.inner.gen_ParProdI[1].gen_inner.REGin_aibi.in
      { kind := .reg, inputs := [(22, 1)] },    -- 13: reg <- \dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_v.in
      { kind := .reg, inputs := [(33, 1)] },    -- 14: reg <- \dut.inner.gen_ParProdI[1].gen_ParProdJ[0].gen_NotEq.REGin_u.in
      { kind := .reg, inputs := [(4, 1)] },    -- 15: reg <- RxDI
      { kind := .not, inputs := [(1, 0)] },    -- 16: _15_
      { kind := .not, inputs := [(0, 0)] },    -- 17: _16_
      { kind := .xor, inputs := [(14, 0), (7, 0)] },    -- 18: _17_ (xnor internal xor)
      { kind := .not, inputs := [(18, 0)] },    -- 19: _17_
      { kind := .xor, inputs := [(12, 0), (19, 0)] },    -- 20: _18_ (xnor internal xor)
      { kind := .not, inputs := [(20, 0)] },    -- 21: _18_
      { kind := .xor, inputs := [(2, 0), (4, 0)] },    -- 22: _19_
      { kind := .and, inputs := [(1, 0), (11, 0)] },    -- 23: _20_
      { kind := .and, inputs := [(0, 0), (9, 0)] },    -- 24: _21_
      { kind := .xor, inputs := [(4, 0), (3, 0)] },    -- 25: _22_
      { kind := .and, inputs := [(17, 0), (15, 0)] },    -- 26: _23_
      { kind := .xor, inputs := [(8, 0), (10, 0)] },    -- 27: _24_ (xnor internal xor)
      { kind := .not, inputs := [(27, 0)] },    -- 28: _24_
      { kind := .xor, inputs := [(6, 0), (28, 0)] },    -- 29: _25_ (xnor internal xor)
      { kind := .not, inputs := [(29, 0)] },    -- 30: _25_
      { kind := .and, inputs := [(1, 0), (13, 0)] },    -- 31: _26_
      { kind := .and, inputs := [(0, 0), (5, 0)] },    -- 32: _27_
      { kind := .and, inputs := [(16, 0), (15, 0)] }    -- 33: _28_
    ] }

def member (n : Node) : Bool :=
  (n.cycle == 0 && [2, 3, 4, 22, 25].contains n.gate) ||
  (n.cycle == 1 && [0, 1, 5, 9, 11, 13, 15, 16, 17, 23, 24, 26, 31, 32, 33].contains n.gate) ||
  (n.cycle == 2 && [6, 7, 8, 10, 12, 14, 18, 19, 20, 21, 27, 28, 29, 30].contains n.gate)

def gadget : GadgetInstance :=
  { circuit := circuit
    horizon := 3
    d := 2
    inputCount := 2
    inputArrival := fun sharing share =>
      if sharing == 0 then .inp sharing share 1
      else if sharing == 1 then .inp sharing share 0
      else .inp sharing share 0
    output := fun share =>
      if share == 0 then { gate := 30, cycle := 2 }
      else { gate := 21, cycle := 2 }
    member := member
    randomness := [.rnd 0 0, .rnd 0 1, .rnd 0 2] }

end LeanSec.Netlist.HPC2Gen
