import LeanSec.Netlist.HPC2Gen
import LeanSec.Netlist.ParserWitness

/-! GENERATED by tools/netlist2lean/netlist2lean.py from module `hpc2_top`.
    This module re-validates the generated primitive circuit against the
    parser's explicit root/cell-output order and cell-granular wiring. -/

namespace LeanSec.Netlist.ParserWitnessHPC2

open LeanSec LeanSec.Expansion
open LeanSec.Netlist.CellRefinement
open LeanSec.Netlist.CircuitRefinementGeneric
open LeanSec.Netlist.CircuitRefinementClosed
open LeanSec.Netlist.ParserWitness

def atomicCircuit : Circuit :=
  { gates := #[
      { kind := .inp 0 0, inputs := [] },    -- 0: root: input AxDI[0]
      { kind := .inp 0 1, inputs := [] },    -- 1: root: input AxDI[1]
      { kind := .inp 1 0, inputs := [] },    -- 2: root: input BxDI[0]
      { kind := .inp 1 1, inputs := [] },    -- 3: root: input BxDI[1]
      { kind := .rnd 0, inputs := [] },    -- 4: root: randomness RxDI
      { kind := .reg, inputs := [(2, 1)] },    -- 5: root: _29_.Q
      { kind := .reg, inputs := [(32, 1)] },    -- 6: root: _30_.Q
      { kind := .reg, inputs := [(31, 1)] },    -- 7: root: _31_.Q
      { kind := .reg, inputs := [(26, 1)] },    -- 8: root: _32_.Q
      { kind := .reg, inputs := [(25, 1)] },    -- 9: root: _33_.Q
      { kind := .reg, inputs := [(24, 1)] },    -- 10: root: _34_.Q
      { kind := .reg, inputs := [(3, 1)] },    -- 11: root: _35_.Q
      { kind := .reg, inputs := [(23, 1)] },    -- 12: root: _36_.Q
      { kind := .reg, inputs := [(22, 1)] },    -- 13: root: _37_.Q
      { kind := .reg, inputs := [(33, 1)] },    -- 14: root: _38_.Q
      { kind := .reg, inputs := [(4, 1)] },    -- 15: root: _39_.Q
      { kind := .not, inputs := [(1, 0)] },    -- 16: atomic INV_X1: _15_
      { kind := .not, inputs := [(0, 0)] },    -- 17: atomic INV_X1: _16_
      { kind := .const false, inputs := [] },    -- 18: atomic placeholder
      { kind := .and, inputs := [(14, 0), (7, 0)] },    -- 19: atomic XNOR2_X1: _17_
      { kind := .const false, inputs := [] },    -- 20: atomic placeholder
      { kind := .and, inputs := [(12, 0), (19, 0)] },    -- 21: atomic XNOR2_X1: _18_
      { kind := .and, inputs := [(2, 0), (4, 0)] },    -- 22: atomic XOR2_X1: _19_
      { kind := .and, inputs := [(1, 0), (11, 0)] },    -- 23: atomic AND2_X1: _20_
      { kind := .and, inputs := [(0, 0), (9, 0)] },    -- 24: atomic AND2_X1: _21_
      { kind := .and, inputs := [(4, 0), (3, 0)] },    -- 25: atomic XOR2_X1: _22_
      { kind := .and, inputs := [(17, 0), (15, 0)] },    -- 26: atomic AND2_X1: _23_
      { kind := .const false, inputs := [] },    -- 27: atomic placeholder
      { kind := .and, inputs := [(8, 0), (10, 0)] },    -- 28: atomic XNOR2_X1: _24_
      { kind := .const false, inputs := [] },    -- 29: atomic placeholder
      { kind := .and, inputs := [(6, 0), (28, 0)] },    -- 30: atomic XNOR2_X1: _25_
      { kind := .and, inputs := [(1, 0), (13, 0)] },    -- 31: atomic AND2_X1: _26_
      { kind := .and, inputs := [(0, 0), (5, 0)] },    -- 32: atomic AND2_X1: _27_
      { kind := .and, inputs := [(16, 0), (15, 0)] }    -- 33: atomic AND2_X1: _28_
    ] }

/-- Parsed roots and standard-cell outputs in dependency order. -/
def parsedOutputs : List Nat :=
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 21, 22, 23, 24, 25, 26, 28, 30, 31, 32, 33]

set_option maxRecDepth 10000 in
set_option maxHeartbeats 8000000 in
/-- Kernel-checked re-validation of the generated circuit and cell wiring. -/
def supportedCellExpansion :
    SupportedCellExpansion LeanSec.Netlist.HPC2Gen.circuit atomicCircuit := by
  refine {
    outputs := parsedOutputs
    expandedZeroOrdered := zeroOrdered_of_finite (by
      unfold LeanSec.Netlist.HPC2Gen.circuit
      decide)
    atomicZeroOrdered := zeroOrdered_of_finite (by
      unfold atomicCircuit
      decide)
    expandedOutputBound := outputBound_of_finite (by
      unfold LeanSec.Netlist.HPC2Gen.circuit parsedOutputs
      decide)
    atomicOutputBound := outputBound_of_finite (by
      unfold atomicCircuit parsedOutputs
      decide)
    step := ?_ }
  intro index gate hgate
  exact match index with
  | 0 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 0
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 1 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 1
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 2 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 2
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 3 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 3
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 4 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 4
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 5 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 5
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 6 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 6
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 7 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 7
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 8 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 8
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 9 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 9
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 10 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 10
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 11 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 11
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 12 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 12
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 13 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 13
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 14 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 14
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 15 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 15
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 16 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .invX1
        1 1 1 1
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 17 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .invX1
        0 0 0 0
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 18 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .xnor2X1
        14 14 7 7
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit]
          rw [orderedFrontier]
          simp [SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 19 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .xnor2X1
        12 12 18 19
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit]
          rw [orderedFrontier]
          simp [SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 20 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .xor2X1
        2 2 4 4
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 21 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .and2X1
        1 1 11 11
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 22 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .and2X1
        0 0 9 9
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 23 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .xor2X1
        4 4 3 3
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 24 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .and2X1
        17 17 15 15
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 25 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .xnor2X1
        8 8 10 10
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit]
          rw [orderedFrontier]
          simp [SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 26 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .xnor2X1
        6 6 25 28
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit]
          rw [orderedFrontier]
          simp [SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 27 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .and2X1
        1 1 13 13
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 28 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .and2X1
        0 0 5 5
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 29 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .and2X1
        16 16 15 15
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.HPC2Gen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | .succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (n)))))))))))))))))))))))))))))) => by simp [parsedOutputs] at hgate

/-- The E4 capstone now applies to this exact generated circuit. -/
theorem parsedOutputs_frontier_refinement :
    ∀ (index gate : Nat), parsedOutputs[index]? = some gate →
      glitchGates LeanSec.Netlist.HPC2Gen.circuit
          LeanSec.Netlist.HPC2Gen.circuit.gates.size gate =
        glitchGates atomicCircuit atomicCircuit.gates.size gate := by
  simpa only [supportedCellExpansion] using
    parser_generic_wholeCircuit_frontier_refinement supportedCellExpansion

end LeanSec.Netlist.ParserWitnessHPC2
