import LeanSec.Netlist.XorRefreshGen
import LeanSec.Netlist.ParserWitness

/-! GENERATED by tools/netlist2lean/netlist2lean.py from module `xor_refresh`.
    This module re-validates the generated primitive circuit against the
    parser's explicit root/cell-output order and cell-granular wiring. -/

namespace LeanSec.Netlist.ParserWitnessXorRefresh

open LeanSec LeanSec.Expansion
open LeanSec.Netlist.CellRefinement
open LeanSec.Netlist.CircuitRefinementGeneric
open LeanSec.Netlist.CircuitRefinementClosed
open LeanSec.Netlist.ParserWitness

def atomicCircuit : Circuit :=
  { gates := #[
      { kind := .inp 0 0, inputs := [] },    -- 0: root: input AxDI[0]
      { kind := .inp 0 1, inputs := [] },    -- 1: root: input AxDI[1]
      { kind := .inp 1 0, inputs := [] },    -- 2: root: input BxDI[0]
      { kind := .inp 1 1, inputs := [] },    -- 3: root: input BxDI[1]
      { kind := .rnd 0, inputs := [] },    -- 4: root: randomness RxDI
      { kind := .reg, inputs := [(12, 1)] },    -- 5: root: _04_.Q
      { kind := .reg, inputs := [(26, 1)] },    -- 6: root: _11_.Q
      { kind := .not, inputs := [(6, 0)] },    -- 7: root alias: _11_.QN
      { kind := .and, inputs := [(0, 0), (2, 0)] },    -- 8: atomic XOR2_X1: _00_
      { kind := .not, inputs := [(8, 0)] },    -- 9: atomic INV_X1: _01_
      { kind := .const false, inputs := [] },    -- 10: atomic placeholder
      { kind := .and, inputs := [(9, 0), (4, 0)] },    -- 11: atomic XNOR2_X1: _02_
      { kind := .and, inputs := [(11, 0), (11, 0)] },    -- 12: atomic BUF_X1: _03_
      { kind := .const false, inputs := [] },    -- 13: atomic placeholder
      { kind := .const false, inputs := [] },    -- 14: atomic placeholder
      { kind := .const false, inputs := [] },    -- 15: atomic placeholder
      { kind := .and, inputs := [(1, 0), (3, 0)] },    -- 16: atomic OR2_X1: _05_
      { kind := .const false, inputs := [] },    -- 17: atomic placeholder
      { kind := .and, inputs := [(1, 0), (3, 0)] },    -- 18: atomic NAND2_X1: _06_
      { kind := .and, inputs := [(16, 0), (18, 0)] },    -- 19: atomic AND2_X1: _07_
      { kind := .and, inputs := [(19, 0), (4, 0)] },    -- 20: atomic XOR2_X1: _08_
      { kind := .const false, inputs := [] },    -- 21: atomic placeholder
      { kind := .const false, inputs := [] },    -- 22: atomic placeholder
      { kind := .and, inputs := [(20, 0), (20, 0)] },    -- 23: atomic NOR2_X1: _09_
      { kind := .const false, inputs := [] },    -- 24: atomic placeholder
      { kind := .const false, inputs := [] },    -- 25: atomic placeholder
      { kind := .and, inputs := [(23, 0), (23, 0)] },    -- 26: atomic NOR2_X1: _10_
      { kind := .not, inputs := [(7, 0)] }    -- 27: atomic INV_X1: _12_
    ] }

/-- Parsed roots and standard-cell outputs in dependency order. -/
def parsedOutputs : List Nat :=
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 16, 18, 19, 20, 23, 26, 27]

set_option maxRecDepth 10000 in
set_option maxHeartbeats 8000000 in
/-- Kernel-checked re-validation of the generated circuit and cell wiring. -/
def supportedCellExpansion :
    SupportedCellExpansion LeanSec.Netlist.XorRefreshGen.circuit atomicCircuit := by
  refine {
    outputs := parsedOutputs
    expandedZeroOrdered := zeroOrdered_of_finite (by
      unfold LeanSec.Netlist.XorRefreshGen.circuit
      decide)
    atomicZeroOrdered := zeroOrdered_of_finite (by
      unfold atomicCircuit
      decide)
    expandedOutputBound := outputBound_of_finite (by
      unfold LeanSec.Netlist.XorRefreshGen.circuit parsedOutputs
      decide)
    atomicOutputBound := outputBound_of_finite (by
      unfold atomicCircuit parsedOutputs
      decide)
    step := ?_ }
  intro index gate hgate
  exact match index with
  | 0 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 0
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.XorRefreshGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 1 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 1
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.XorRefreshGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 2 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 2
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.XorRefreshGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 3 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 3
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.XorRefreshGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 4 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 4
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.XorRefreshGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 5 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 5
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.XorRefreshGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 6 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 6
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.XorRefreshGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 7 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 6
        (by
          repeat (rw [orderedFrontier]; try simp [LeanSec.Netlist.XorRefreshGen.circuit, SupportedCombCell.function])
          all_goals decide)
        (by
          repeat (rw [orderedFrontier]; try simp [atomicCircuit, SupportedCombCell.function])
          all_goals decide)
  | 8 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .xor2X1
        0 0 2 2
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.XorRefreshGen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 9 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .invX1
        8 8 8 8
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.XorRefreshGen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 10 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .xnor2X1
        9 9 4 4
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.XorRefreshGen.circuit]
          rw [orderedFrontier]
          simp [SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 11 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .bufX1
        10 11 10 11
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          repeat (rw [orderedFrontier]; try simp [LeanSec.Netlist.XorRefreshGen.circuit, SupportedCombCell.function])
          all_goals decide)
        (by
          repeat (rw [orderedFrontier]; try simp [atomicCircuit, SupportedCombCell.function])
          all_goals decide)
  | 12 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .or2X1
        1 1 3 3
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          repeat (rw [orderedFrontier]; try simp [LeanSec.Netlist.XorRefreshGen.circuit, SupportedCombCell.function])
          all_goals decide)
        (by
          repeat (rw [orderedFrontier]; try simp [atomicCircuit, SupportedCombCell.function])
          all_goals decide)
  | 13 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .nand2X1
        1 1 3 3
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.XorRefreshGen.circuit]
          rw [orderedFrontier]
          simp [SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 14 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .and2X1
        12 16 13 18
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.XorRefreshGen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 15 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .xor2X1
        14 19 4 4
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.XorRefreshGen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 16 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .nor2X1
        15 20 15 20
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          repeat (rw [orderedFrontier]; try simp [LeanSec.Netlist.XorRefreshGen.circuit, SupportedCombCell.function])
          all_goals decide)
        (by
          repeat (rw [orderedFrontier]; try simp [atomicCircuit, SupportedCombCell.function])
          all_goals decide)
  | 17 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .nor2X1
        16 23 16 23
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          repeat (rw [orderedFrontier]; try simp [LeanSec.Netlist.XorRefreshGen.circuit, SupportedCombCell.function])
          all_goals decide)
        (by
          repeat (rw [orderedFrontier]; try simp [atomicCircuit, SupportedCombCell.function])
          all_goals decide)
  | 18 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .invX1
        7 7 7 7
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.XorRefreshGen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | .succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (n))))))))))))))))))) => by simp [parsedOutputs] at hgate

/-- The E4 capstone now applies to this exact generated circuit. -/
theorem parsedOutputs_frontier_refinement :
    ∀ (index gate : Nat), parsedOutputs[index]? = some gate →
      glitchGates LeanSec.Netlist.XorRefreshGen.circuit
          LeanSec.Netlist.XorRefreshGen.circuit.gates.size gate =
        glitchGates atomicCircuit atomicCircuit.gates.size gate := by
  simpa only [supportedCellExpansion] using
    parser_generic_wholeCircuit_frontier_refinement supportedCellExpansion

end LeanSec.Netlist.ParserWitnessXorRefresh
