import LeanSec.Netlist.ScanDffWitnessGen

/-!
# End-to-end witness for one translator-emitted SDFF_X1

`ScanDffGen.circuit` is generated by the production translator from
`tools/netlist2lean/netlists/scan_dff.v`.  The generated parser witness checks
the concrete output order and ternary scan-mux step.  This module relates that
emitted index layout to the local reference `scanDffCircuit` layout.
-/

namespace LeanSec.Netlist.ParserWitnessScanDff

open LeanSec LeanSec.Execution LeanSec.Expansion
open LeanSec.Netlist.ScanCellRefinement

/-- Environment for the production translator's source numbering: D is
`inp 0 0`, SI is `inp 1 0`, and the automatically classified SE is `ctl 0`. -/
def emittedScanPinEnv (d se si : Bool) : Env
  | .inp 0 0 _ => d
  | .inp 1 0 _ => si
  | .ctl 0 _ => se
  | _ => false

/-- Index isomorphism from the generated ordering
`[D, SI, SE, Q, mux]` to the reference ordering `[D, SE, SI, mux, Q]`. -/
def emittedToReferenceGate : Nat → Nat
  | 0 => dGate
  | 1 => scanInputGate
  | 2 => scanEnableGate
  | 3 => scanQGate
  | 4 => scanMuxGate
  | gate => gate

/-- Direct shape check over the artifact emitted by `netlist2lean.py`: Q is a
latency-one register driven by the explicit ternary mux, not by D directly. -/
theorem emitted_sdff_shape :
    LeanSec.Netlist.ScanDffGen.circuit =
      { gates := #[
          { kind := .inp 0 0, inputs := [] },
          { kind := .inp 1 0, inputs := [] },
          { kind := .ctl 0, inputs := [] },
          { kind := .reg, inputs := [(4, 1)] },
          { kind := .mux, inputs := [(2, 0), (0, 0), (1, 0)] }
        ] } := by
  rfl

/-- The translator-emitted mux computes the same Boolean function as the
reference scan mux. -/
theorem emitted_sdff_combinational_function (d se si : Bool) :
    eval LeanSec.Netlist.ScanDffGen.circuit 1 (emittedScanPinEnv d se si)
        { gate := 4, cycle := 0 } =
      eval scanDffCircuit 1 (scanPinEnv d se si)
        { gate := scanMuxGate, cycle := 0 } := by
  cases d <;> cases se <;> cases si <;> decide

/-- The translator-emitted Q computes the same latency-one scan-DFF function
as the reference expansion. -/
theorem emitted_sdff_q_function (d se si : Bool) :
    eval LeanSec.Netlist.ScanDffGen.circuit 2 (emittedScanPinEnv d se si)
        { gate := 3, cycle := 1 } =
      eval scanDffCircuit 2 (scanPinEnv d se si)
        { gate := scanQGate, cycle := 1 } := by
  cases d <;> cases se <;> cases si <;> decide

/-- After the explicit index isomorphism, the emitted mux frontier is exactly
the proved reference scan-mux frontier, including SI. -/
theorem emitted_sdff_mux_frontier_matches_scanDffCircuit :
    (glitchGates LeanSec.Netlist.ScanDffGen.circuit
        LeanSec.Netlist.ScanDffGen.circuit.gates.size 4).map
        emittedToReferenceGate =
      glitchGates scanDffCircuit scanDffCircuit.gates.size scanMuxGate := by
  decide

/-- Named emitted SI node: gate 1 occurs in the emitted scan-aware frontier
and maps to reference `scanInputGate` (gate 2). -/
theorem emitted_scanInput_in_frontier :
    1 ∈ glitchGates LeanSec.Netlist.ScanDffGen.circuit
      LeanSec.Netlist.ScanDffGen.circuit.gates.size 4 ∧
    emittedToReferenceGate 1 = scanInputGate := by
  decide

/-- The production member policy exposes both the sampled-data mux and Q. -/
theorem emitted_sdff_member_policy :
    LeanSec.Netlist.ScanDffGen.member { gate := 4, cycle := 0 } = true ∧
      LeanSec.Netlist.ScanDffGen.member { gate := 3, cycle := 1 } = true := by
  decide

/-- End-to-end summary: the emitted SDFF_X1 has the reference function and
frontier (up to its explicit gate-index isomorphism), and retains the scan mux
as a probeable member. -/
theorem emitted_sdff_matches_scanDffCircuit :
    (∀ d se si,
      eval LeanSec.Netlist.ScanDffGen.circuit 2 (emittedScanPinEnv d se si)
          { gate := 3, cycle := 1 } =
        eval scanDffCircuit 2 (scanPinEnv d se si)
          { gate := scanQGate, cycle := 1 }) ∧
    (glitchGates LeanSec.Netlist.ScanDffGen.circuit
        LeanSec.Netlist.ScanDffGen.circuit.gates.size 4).map
        emittedToReferenceGate =
      glitchGates scanDffCircuit scanDffCircuit.gates.size scanMuxGate ∧
    LeanSec.Netlist.ScanDffGen.member { gate := 4, cycle := 0 } = true := by
  exact ⟨emitted_sdff_q_function,
    emitted_sdff_mux_frontier_matches_scanDffCircuit,
    emitted_sdff_member_policy.1⟩

end LeanSec.Netlist.ParserWitnessScanDff
