import LeanSec.Netlist.DomAndGen
import LeanSec.Netlist.ParserWitness

/-! GENERATED by tools/netlist2lean/netlist2lean.py from module `dom_and`.
    This module re-validates the generated primitive circuit against the
    parser's explicit root/cell-output order and cell-granular wiring. -/

namespace LeanSec.Netlist.ParserWitnessDomAnd

open LeanSec LeanSec.Expansion
open LeanSec.Netlist.CellRefinement
open LeanSec.Netlist.CircuitRefinementGeneric
open LeanSec.Netlist.CircuitRefinementClosed
open LeanSec.Netlist.ParserWitness

def atomicCircuit : Circuit :=
  { gates := #[
      { kind := .inp 0 0, inputs := [] },    -- 0: root: input AxDI[0]
      { kind := .inp 0 1, inputs := [] },    -- 1: root: input AxDI[1]
      { kind := .inp 1 0, inputs := [] },    -- 2: root: input BxDI[0]
      { kind := .inp 1 1, inputs := [] },    -- 3: root: input BxDI[1]
      { kind := .rnd 0, inputs := [] },    -- 4: root: randomness ZxDI
      { kind := .reg, inputs := [(19, 1)] },    -- 5: root: _14_.Q
      { kind := .reg, inputs := [(18, 1)] },    -- 6: root: _15_.Q
      { kind := .reg, inputs := [(17, 1)] },    -- 7: root: _16_.Q
      { kind := .reg, inputs := [(13, 1)] },    -- 8: root: _17_.Q
      { kind := .and, inputs := [(5, 0), (7, 0)] },    -- 9: atomic XOR2_X1: _06_
      { kind := .const false, inputs := [] },    -- 10: atomic placeholder
      { kind := .and, inputs := [(1, 0), (2, 0)] },    -- 11: atomic NAND2_X1: _07_
      { kind := .const false, inputs := [] },    -- 12: atomic placeholder
      { kind := .and, inputs := [(4, 0), (11, 0)] },    -- 13: atomic XNOR2_X1: _08_
      { kind := .const false, inputs := [] },    -- 14: atomic placeholder
      { kind := .and, inputs := [(0, 0), (3, 0)] },    -- 15: atomic NAND2_X1: _09_
      { kind := .const false, inputs := [] },    -- 16: atomic placeholder
      { kind := .and, inputs := [(4, 0), (15, 0)] },    -- 17: atomic XNOR2_X1: _10_
      { kind := .and, inputs := [(1, 0), (3, 0)] },    -- 18: atomic AND2_X1: _11_
      { kind := .and, inputs := [(2, 0), (0, 0)] },    -- 19: atomic AND2_X1: _12_
      { kind := .and, inputs := [(6, 0), (8, 0)] }    -- 20: atomic XOR2_X1: _13_
    ] }

/-- Parsed roots and standard-cell outputs in dependency order. -/
def parsedOutputs : List Nat :=
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 15, 17, 18, 19, 20]

set_option maxRecDepth 10000 in
set_option maxHeartbeats 8000000 in
/-- Kernel-checked re-validation of the generated circuit and cell wiring. -/
def supportedCellExpansion :
    SupportedCellExpansion LeanSec.Netlist.DomAndGen.circuit atomicCircuit := by
  refine {
    outputs := parsedOutputs
    expandedZeroOrdered := zeroOrdered_of_finite (by
      unfold LeanSec.Netlist.DomAndGen.circuit
      decide)
    atomicZeroOrdered := zeroOrdered_of_finite (by
      unfold atomicCircuit
      decide)
    expandedOutputBound := outputBound_of_finite (by
      unfold LeanSec.Netlist.DomAndGen.circuit parsedOutputs
      decide)
    atomicOutputBound := outputBound_of_finite (by
      unfold atomicCircuit parsedOutputs
      decide)
    step := ?_ }
  intro index gate hgate
  exact match index with
  | 0 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 0
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 1 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 1
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 2 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 2
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 3 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 3
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 4 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 4
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 5 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 5
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 6 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 6
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 7 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 7
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 8 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 8
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 9 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .xor2X1
        5 5 7 7
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 10 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .nand2X1
        1 1 2 2
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit]
          rw [orderedFrontier]
          simp [SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 11 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .xnor2X1
        4 4 10 11
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit]
          rw [orderedFrontier]
          simp [SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 12 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .nand2X1
        0 0 3 3
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit]
          rw [orderedFrontier]
          simp [SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 13 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .xnor2X1
        4 4 12 15
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit]
          rw [orderedFrontier]
          simp [SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 14 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .and2X1
        1 1 3 3
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 15 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .and2X1
        2 2 0 0
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | 16 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .combinational .xor2X1
        6 6 8 8
        (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.DomAndGen.circuit,
            SupportedCombCell.function])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit,
            SupportedCombCell.function])
  | .succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (n))))))))))))))))) => by simp [parsedOutputs] at hgate

/-- The E4 capstone now applies to this exact generated circuit. -/
theorem parsedOutputs_frontier_refinement :
    ∀ (index gate : Nat), parsedOutputs[index]? = some gate →
      glitchGates LeanSec.Netlist.DomAndGen.circuit
          LeanSec.Netlist.DomAndGen.circuit.gates.size gate =
        glitchGates atomicCircuit atomicCircuit.gates.size gate := by
  simpa only [supportedCellExpansion] using
    parser_generic_wholeCircuit_frontier_refinement supportedCellExpansion

end LeanSec.Netlist.ParserWitnessDomAnd
