import LeanSec.Gadget

/-! GENERATED by tools/netlist2lean/netlist2lean.py from a SILVER-format
    NANG45 netlist (module `scan_dff_top`).  DO NOT EDIT BY HAND — regenerate.
    The proved object below is DERIVED from the netlist SILVER verifies,
    not hand-transcribed.  See LeanSec/Netlist/TRUST.md. -/

namespace LeanSec.Netlist.ScanDffGen

open LeanSec LeanSec.Gadget

def circuit : Circuit :=
  { gates := #[
      { kind := .inp 0 0, inputs := [] },    -- 0: D = inp 0 0
      { kind := .inp 1 0, inputs := [] },    -- 1: SI = inp 1 0
      { kind := .ctl 0, inputs := [] },    -- 2: SE = ctl 0
      { kind := .reg, inputs := [(4, 1)] },    -- 3: reg <- mux(SE, D, SI)
      { kind := .mux, inputs := [(2, 0), (0, 0), (1, 0)] }    -- 4: scan mux of u_scan
    ] }

def member (n : Node) : Bool :=
  (n.cycle == 0 && [0, 1, 2, 4].contains n.gate) ||
  (n.cycle == 1 && [3].contains n.gate)

def gadget : GadgetInstance :=
  { circuit := circuit
    horizon := 2
    d := 1
    inputCount := 2
    inputArrival := fun sharing share => .inp sharing share 0
    output := fun share =>
      { gate := 3, cycle := 1 }
    member := member
    randomness := [] }

end LeanSec.Netlist.ScanDffGen
