import LeanSec.Netlist.ScanDffGen
import LeanSec.Netlist.ScanParserWitness

/-! GENERATED by tools/netlist2lean/netlist2lean.py from module `scan_dff_top`.
    This module re-validates the generated primitive circuit against the
    parser's explicit root/cell-output order and cell-granular wiring. -/

namespace LeanSec.Netlist.ScanDffWitnessGen

open LeanSec LeanSec.Expansion
open LeanSec.Netlist.CellRefinement
open LeanSec.Netlist.CircuitRefinementGeneric
open LeanSec.Netlist.CircuitRefinementClosed
open LeanSec.Netlist.ParserWitness
open LeanSec.Netlist.ScanCellRefinement
open LeanSec.Netlist.ScanParserWitness

def atomicCircuit : Circuit :=
  { gates := #[
      { kind := .inp 0 0, inputs := [] },    -- 0: root: input D
      { kind := .inp 1 0, inputs := [] },    -- 1: root: input SI
      { kind := .ctl 0, inputs := [] },    -- 2: root: control SE
      { kind := .reg, inputs := [(4, 1)] },    -- 3: root: u_scan.Q
      { kind := .mux, inputs := [(2, 0), (0, 0), (1, 0)] }    -- 4: atomic SDFF_X1: u_scan
    ] }

/-- Parsed roots and standard-cell outputs in dependency order. -/
def parsedOutputs : List Nat :=
  [0, 1, 2, 3, 4]

set_option maxRecDepth 10000 in
set_option maxHeartbeats 8000000 in
/-- Kernel-checked re-validation of the generated circuit and cell wiring. -/
def supportedCellExpansion :
    SupportedScanCellExpansion LeanSec.Netlist.ScanDffGen.circuit atomicCircuit := by
  refine {
    outputs := parsedOutputs
    expandedZeroOrdered := zeroOrdered_of_finite (by
      unfold LeanSec.Netlist.ScanDffGen.circuit
      decide)
    atomicZeroOrdered := zeroOrdered_of_finite (by
      unfold atomicCircuit
      decide)
    expandedOutputBound := outputBound_of_finite (by
      unfold LeanSec.Netlist.ScanDffGen.circuit parsedOutputs
      decide)
    atomicOutputBound := outputBound_of_finite (by
      unfold atomicCircuit parsedOutputs
      decide)
    step := ?_ }
  intro index gate hgate
  exact match index with
  | 0 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 0
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.ScanDffGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 1 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 1
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.ScanDffGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 2 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 2
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.ScanDffGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 3 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .root 3
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.ScanDffGen.circuit])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit])
  | 4 => by
      simp [parsedOutputs] at hgate
      subst gate
      exact .scanMux .sdffX1
        2 2 0 0 1 1
        (by decide) (by decide) (by decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by unfold parsedOutputs; decide)
        (by
          rw [orderedFrontier]
          simp [LeanSec.Netlist.ScanDffGen.circuit, scanMuxFrontier])
        (by
          rw [orderedFrontier]
          simp [atomicCircuit, scanMuxFrontier])
  | .succ (.succ (.succ (.succ (.succ (n))))) => by simp [parsedOutputs] at hgate

/-- The E4 capstone now applies to this exact generated circuit. -/
theorem parsedOutputs_frontier_refinement :
    ∀ (index gate : Nat), parsedOutputs[index]? = some gate →
      glitchGates LeanSec.Netlist.ScanDffGen.circuit
          LeanSec.Netlist.ScanDffGen.circuit.gates.size gate =
        glitchGates atomicCircuit atomicCircuit.gates.size gate := by
  simpa only [supportedCellExpansion] using
    parser_scan_wholeCircuit_frontier_refinement supportedCellExpansion

end LeanSec.Netlist.ScanDffWitnessGen
