import LeanSec.Gadget

/-! GENERATED by tools/netlist2lean/netlist2lean.py from a SILVER-format
    NANG45 netlist (module `xor_refresh`).  DO NOT EDIT BY HAND — regenerate.
    The proved object below is DERIVED from the netlist SILVER verifies,
    not hand-transcribed.  See LeanSec/Netlist/TRUST.md. -/

namespace LeanSec.Netlist.XorRefreshGen

open LeanSec LeanSec.Gadget

def circuit : Circuit :=
  { gates := #[
      { kind := .inp 0 0, inputs := [] },    -- 0: AxDI[0] = inp 0 0
      { kind := .inp 0 1, inputs := [] },    -- 1: AxDI[1] = inp 0 1
      { kind := .inp 1 0, inputs := [] },    -- 2: BxDI[0] = inp 1 0
      { kind := .inp 1 1, inputs := [] },    -- 3: BxDI[1] = inp 1 1
      { kind := .rnd 0, inputs := [] },    -- 4: RxDI = rnd 0
      { kind := .reg, inputs := [(12, 1)] },    -- 5: reg <- b0
      { kind := .reg, inputs := [(26, 1)] },    -- 6: reg <- u1f
      { kind := .not, inputs := [(6, 0)] },    -- 7: QN of _11_
      { kind := .xor, inputs := [(0, 0), (2, 0)] },    -- 8: _00_
      { kind := .not, inputs := [(8, 0)] },    -- 9: _01_
      { kind := .xor, inputs := [(9, 0), (4, 0)] },    -- 10: _02_ (xnor internal xor)  -- internal (non-member)
      { kind := .not, inputs := [(10, 0)] },    -- 11: _02_
      { kind := .and, inputs := [(11, 0), (11, 0)] },    -- 12: _03_ (buf)
      { kind := .not, inputs := [(1, 0)] },    -- 13: _05_ (or !a)  -- internal (non-member)
      { kind := .not, inputs := [(3, 0)] },    -- 14: _05_ (or !b)  -- internal (non-member)
      { kind := .and, inputs := [(13, 0), (14, 0)] },    -- 15: _05_ (or !a&!b)  -- internal (non-member)
      { kind := .not, inputs := [(15, 0)] },    -- 16: _05_
      { kind := .and, inputs := [(1, 0), (3, 0)] },    -- 17: _06_ (nand internal and)  -- internal (non-member)
      { kind := .not, inputs := [(17, 0)] },    -- 18: _06_
      { kind := .and, inputs := [(16, 0), (18, 0)] },    -- 19: _07_
      { kind := .xor, inputs := [(19, 0), (4, 0)] },    -- 20: _08_
      { kind := .not, inputs := [(20, 0)] },    -- 21: _09_ (nor !a)  -- internal (non-member)
      { kind := .not, inputs := [(20, 0)] },    -- 22: _09_ (nor !b)  -- internal (non-member)
      { kind := .and, inputs := [(21, 0), (22, 0)] },    -- 23: _09_
      { kind := .not, inputs := [(23, 0)] },    -- 24: _10_ (nor !a)  -- internal (non-member)
      { kind := .not, inputs := [(23, 0)] },    -- 25: _10_ (nor !b)  -- internal (non-member)
      { kind := .and, inputs := [(24, 0), (25, 0)] },    -- 26: _10_
      { kind := .not, inputs := [(7, 0)] }    -- 27: _12_
    ] }

def member (n : Node) : Bool :=
  (n.cycle == 0 && [0, 1, 2, 3, 4, 8, 9, 11, 12, 16, 18, 19, 20, 23, 26].contains n.gate) ||
  (n.cycle == 1 && [5, 6, 7, 27].contains n.gate)

def gadget : GadgetInstance :=
  { circuit := circuit
    horizon := 2
    d := 2
    inputCount := 2
    inputArrival := fun sharing share => .inp sharing share 0
    output := fun share =>
      if share == 0 then { gate := 5, cycle := 1 }
      else { gate := 27, cycle := 1 }
    member := member
    randomness := [.rnd 0 0, .rnd 0 1] }

end LeanSec.Netlist.XorRefreshGen
