#!/usr/bin/env python3
"""Minimal proof-carrying masking compiler for one two-input AND.

The accepted source language is deliberately tiny:

    <identifier> & <different-identifier>

Compilation selects LeanSec's proved two-share DOM-AND template and emits a
fresh Lean module containing the selected circuit/gadget and fresh functional
and first-order probing-security anchors.  Unsupported syntax is a hard error.
This is a compiler-flow PoC, not a general Boolean or hardware front-end.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
COMPILED_DIR = ROOT / "LeanSec" / "Compiled"
IDENT = r"[A-Za-z_][A-Za-z0-9_]*"
GENERATED_MARKER = "Generated by tools/maskc/maskc.py"


def fail(message: str) -> "NoReturn":
    print(f"maskc: error: {message}", file=sys.stderr)
    raise SystemExit(2)


def parse_and_spec(text: str) -> tuple[str, str]:
    """Parse the complete source language, rejecting all other expressions."""
    match = re.fullmatch(rf"\s*({IDENT})\s*&\s*({IDENT})\s*", text)
    if match is None:
        fail("the PoC accepts exactly '<identifier> & <identifier>'")
    left, right = match.groups()
    if left == right:
        fail("the two AND inputs must have different identifiers")
    return left, right


def module_name(raw: str) -> str:
    """Turn a CLI artifact name into one safe Lean module path component."""
    words = [word for word in re.split(r"[^A-Za-z0-9]+", raw) if word]
    if not words:
        fail("--name must contain an ASCII letter or digit")
    name = "".join(word[0].upper() + word[1:] for word in words)
    if not re.fullmatch(r"[A-Z][A-Za-z0-9]*", name):
        fail("--name must form a Lean module name beginning with a letter")
    return name


def emit_lean(name: str, left: str, right: str) -> str:
    namespace = f"LeanSec.Compiled.{name}"
    return f"""/-
Generated by tools/maskc/maskc.py from: {left} & {right}

PoC lowering rule: a two-input Boolean AND becomes the proved, first-order,
two-share DOM-AND template.  Source input order is {left}=0, {right}=1.
-/
import LeanSec.Gadgets.DomAnd

namespace {namespace}

open Gadget

/-- The unmasked source-level function, with inputs in source order. -/
def sourceSpec (inputs : List Bool) : Bool :=
  inputs.getD 0 false && inputs.getD 1 false

/-- Masked circuit selected by the compiler's single DOM-AND lowering rule. -/
def circuit : Circuit := LeanSec.Gadgets.DomAnd.circuit

/-- The template instance, made explicitly to refer to the emitted circuit. -/
def gadget : GadgetInstance :=
  {{ LeanSec.Gadgets.DomAnd.gadget with circuit := circuit }}

/-- Audit anchor: this generated instance is exactly the proved template. -/
theorem is_dom_and_template :
    gadget = LeanSec.Gadgets.DomAnd.gadget := by
  rfl

/-- Functional anchor: all input sharings and all randomness recombine to AND. -/
theorem recombine_anchor : recombinesTo gadget sourceSpec := by
  rw [is_dom_and_template]
  unfold sourceSpec
  exact LeanSec.Gadgets.DomAnd.recombines

set_option maxRecDepth 10000
set_option maxHeartbeats 4000000

/-- Security anchor: every set of at most one glitch-expanded probe is secure. -/
theorem probing_anchor : probingSecure gadget glitch 1 := by
  decide

set_option maxRecDepth 1000
set_option maxHeartbeats 200000

#print axioms recombine_anchor
#print axioms probing_anchor

end {namespace}
"""


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compile the PoC Boolean spec 'a & b' to proved DOM-AND Lean"
    )
    parser.add_argument("spec", help="source expression, currently exactly NAME & NAME")
    parser.add_argument(
        "--name", default="MaskedAnd", help="generated module/file name (default: MaskedAnd)"
    )
    parser.add_argument(
        "--force", action="store_true", help="replace an output previously generated by maskc"
    )
    args = parser.parse_args()

    left, right = parse_and_spec(args.spec)
    name = module_name(args.name)
    output = COMPILED_DIR / f"{name}.lean"
    if output.exists():
        if not args.force:
            fail(f"{output.relative_to(ROOT)} already exists (pass --force to replace it)")
        if GENERATED_MARKER not in output.read_text(encoding="utf-8")[:256]:
            fail(f"refusing to replace non-maskc module {output.relative_to(ROOT)}")

    COMPILED_DIR.mkdir(parents=True, exist_ok=True)
    output.write_text(emit_lean(name, left, right), encoding="utf-8")
    print(f"wrote {output.relative_to(ROOT)}")
    print(f"build with: lake build LeanSec.Compiled.{name}")


if __name__ == "__main__":
    main()
